CHANGELOG.md
lib/src/executable.dart
lib/src/runner/browser/browser_manager.dart
lib/src/runner/browser/iframe_test.dart
lib/src/runner/browser/server.dart
lib/src/runner/loader.dart
lib/src/util/stack_trace_mapper.dart
pubspec.yaml
test/runner/browser/runner_test.dart
test/runner/pub_serve_test.dart

Closes #21
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dart-lang/test/117)

Convert JS stack traces into Dart stack traces.

---

lib/src/runner/browser/compiler_pool.dart
lib/src/runner/browser/server.dart
test/runner/pub_serve_test.dart
test/runner/runner_test.dart

Closes #120 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dart-lang/test/122)

Fix a bunch of broken tests.

---

lib/src/runner/loader.dart
lib/src/util/dart.dart
lib/src/util/io.dart
lib/src/util/isolate_wrapper.dart

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dart-lang/test/268)

Add support for checked mode

---

CHANGELOG.md
pubspec.yaml

Widen the analyzer constraint to include 0.26.0.

---

CHANGELOG.md
pubspec.yaml

See dart-lang/http_multi_server#1.

Update the dependency on http_multi_server.

---

CHANGELOG.md
lib/src/matcher/iterable_matchers.dart
lib/src/matcher/operator_matchers.dart
lib/src/matcher/util.dart
lib/unittest.dart
pubspec.yaml

I can't figure out how to get Rietveld to base this on the right branch, so here's a PR instead.

Fix all strong mode warnings in 0.11.x.

---

CHANGELOG.md
lib/src/matcher/operator_matchers.dart
pubspec.yaml

See dart-lang/matcher@400e87928fdceeee883c95c8a81e96fdacfdc399

Fix _wrapArgs.

---

lib/src/runner/loader.dart

This will be useful for Bolt, which has out-of-band information about
what platforms each given test is intended to run on.

Allow the platforms to be constrained in Loader.

---

README.md

Stop mentioning the Dart editor.

---

test/util/forkable_stream_test.dart
test/util/stream_queue_test.dart

This reverts commit 4ca058ced016c2808dacc2f27f7e74006fea7a7a.

Revert "Delete tests of features in pkg/async"

---

CHANGELOG.md
lib/src/backend/declarer.dart
pubspec.yaml
test/backend/declarer_test.dart

Throw a better error for async groups.

---

lib/src/runner.dart
lib/src/runner/browser/browser_manager.dart
lib/src/runner/browser/chrome.dart
lib/src/runner/browser/dartium.dart
lib/src/runner/browser/platform.dart
lib/src/runner/debugger.dart
lib/src/runner/environment.dart
lib/src/runner/plugin/environment.dart
lib/src/runner/plugin/platform.dart
lib/src/runner/reporter/json.dart

I think most of these breakages are due to the 1325b69 merge being
slightly busted.

Fix a number of broken tests.

---

CHANGELOG.md
lib/src/backend/metadata.dart
pubspec.yaml
test/runner/configuration/tags_test.dart

Fix a Metadata bug.

---

CHANGELOG.md
lib/src/backend/declarer.dart
lib/src/backend/invoker.dart
lib/src/utils.dart
lib/test.dart
test/frontend/add_tear_down_test.dart
test/utils.dart

Add an addTearDown() function.

---

CHANGELOG.md
README.md
lib/src/backend/test_platform.dart
lib/src/runner.dart
lib/src/runner/debugger.dart
lib/src/runner/vm/environment.dart
lib/src/runner/vm/platform.dart
pubspec.yaml
test/runner/pause_after_load_test.dart

This doesn't fully support the JSON reporter yet.
See #50

Support debugging VM tests.

---

CHANGELOG.md
lib/src/runner/reporter/compact.dart
lib/src/runner/reporter/expanded.dart
pubspec.yaml
test/runner/browser/runner_test.dart
test/runner/compact_reporter_test.dart
test/runner/configuration/platform_test.dart
test/runner/configuration/presets_test.dart
test/runner/configuration/tags_test.dart
test/runner/expanded_reporter_test.dart
test/runner/name_test.dart
test/runner/pub_serve_test.dart
test/runner/runner_test.dart
test/runner/set_up_all_test.dart
test/runner/skip_expect_test.dart
test/runner/tear_down_all_test.dart

Print "[E]" after failing tests.

---

CHANGELOG.md
lib/src/runner/browser/chrome.dart
lib/src/runner/browser/platform.dart
test/frontend/matcher/completion_test.dart
test/frontend/matcher/prints_test.dart
test/frontend/matcher/throws_test.dart
test/runner/configuration/presets_test.dart

Fix remaining failing tests.

---

README.md

Hopefully preventing others from running into issues with getting the tests to run on Linux.

adding content_shell documentation

---

lib/src/runner.dart
lib/src/runner/browser/platform.dart

This allows this package to be compiled with dartdevc

fix the strong mode errors under lib

---

lib/src/runner.dart
lib/src/runner/browser/chrome.dart
lib/test.dart
test/frontend/expect_test.dart

fix a few analysis warnings:
- remove unused imports
- ignore some (intentional) instances of dead code

fix a few analysis warnings

---

pubspec.yaml

- rev to analyzer `0.30.0`
- fix https://github.com/dart-lang/test/issues/592

rev to analyzer 0.30.0

---

CHANGELOG.md
lib/test.dart
test/runner/runner_test.dart

Fix onPlatform when used on a group().

---

CHANGELOG.md
lib/src/frontend/future_matchers.dart
test/frontend/matcher/completion_test.dart

This closes https://github.com/dart-lang/test/issues/24

Add Matcher for doesNotComplete

---

CHANGELOG.md
lib/src/runner/browser/platform.dart
lib/src/runner/load_suite.dart
lib/src/runner/loader.dart

Only print browser errors once per browser.

---

lib/src/runner/plugin/platform_helpers.dart
test/runner/browser/runner_test.dart

Increase the deserialize timeout and remove the corresponding test.

Reduce flakiness

---

test/runner/pub_serve_test.dart

Added dartdevc to most of the tests.
Note that I didn't add it to the stack trace tests as those don't seem to pass currently, we can talk offline about what the expectation is for those.

add dartdevc tests to the pub serve tests

---

lib/src/frontend/expect_async.dart
lib/src/runner/browser/browser_manager.dart
lib/src/runner/browser/chrome.dart
lib/src/runner/browser/content_shell.dart
lib/src/runner/browser/dartium.dart
lib/src/runner/configuration.dart
lib/src/runner/configuration/args.dart
lib/src/runner/configuration/load.dart
lib/src/runner/configuration/suite.dart
lib/src/runner/parse_metadata.dart
lib/src/utils.dart

Use non-comment generic method syntax

---

CHANGELOG.md
lib/src/frontend/spawn_hybrid.dart
pubspec.yaml
test/runner/hybrid_test.dart

Fix spawnHybridUri() in the browser

---

.travis.yml

This makes it possible to commit reviewed code to a branch when working
on a larger change that's composed of multiple pull requests.

Run Travis builds on feature branches

---

CHANGELOG.md
doc/configuration.md
lib/src/runner/browser/platform.dart
lib/src/runner/configuration.dart
lib/src/runner/configuration/load.dart
lib/src/runner/configuration/platform_settings.dart
lib/src/runner/loader.dart
lib/src/runner/plugin/customizable_platform.dart
lib/src/utils.dart
pubspec.yaml
test/runner/configuration/custom_platform_test.dart
test/runner/configuration/global_test.dart

Add an override_platforms config field

---

doc/configuration.md
lib/src/runner/node/platform.dart
test/runner/configuration/custom_platform_test.dart

Support configuring the Node platform

---

doc/configuration.md
lib/src/runner/executable_settings.dart
lib/src/runner/node/platform.dart
pubspec.yaml
test/runner/configuration/custom_platform_test.dart

Add an arguments field to executable settings

---

CHANGELOG.md
lib/src/runner/browser/browser.dart
pubspec.yaml

Include browser standard output in crash messages

---

lib/src/frontend/expect.dart
pubspec.yaml

Now enabled in analyzer as of
https://github.com/dart-lang/sdk/commit/0a6253312f
Dart SDK 2.0.0-dev.12.0

Add @alwaysThrows annotation to fail

---

CHANGELOG.md
pubspec.yaml

Publishing the current stuff so I can roll it internally.

Bump to 0.12.30 before publishing.

---

CHANGELOG.md
lib/src/frontend/expect.dart

Type fail() to return Null

---

CHANGELOG.md
README.md
lib/src/runner/plugin/platform_helpers.dart
pubspec.yaml
test/runner/node/runner_test.dart

Support operating system selectors under Node.js

---

CHANGELOG.md
lib/src/runner/loader.dart
pubspec.yaml
test/runner/tag_test.dart

Don't load test suites with excluded tags

---

lib/src/runner/loader.dart
lib/src/util/io.dart
test/runner/node/runner_test.dart
test/runner/runner_test.dart

Refuse to run VM or Node tests with --precompiled

---

CHANGELOG.md
lib/src/frontend/format_stack_trace.dart
pubspec.yaml

Fix formatStackTrace() in dart path/to/test.dart

---

pubspec.yaml

There are no imports to this package.

Drop dev_dependency on http

---

lib/src/runner/browser/browser.dart
lib/src/runner/configuration/load.dart
lib/src/utils.dart
test/runner/runner_test.dart

Made members only used within a library private

Remove a number of unused members

---

CHANGELOG.md
lib/src/runner/configuration.dart
lib/src/runner/configuration/load.dart
lib/src/util/one_off_handler.dart
lib/src/util/path_handler.dart
pubspec.yaml

Fix several Dart 2 runtime type errors

---

test/runner/runner_test.dart
test/utils.dart

Towards https://github.com/dart-lang/test/issues/842
Compilation in Dart 2 is different which causes slightly different failure messages. Adding a conditional for Dart 2 and updating the corresponding checks.

Dart 2 fixes

---

CHANGELOG.md
doc/json_reporter.md
lib/src/runner/reporter/json.dart
pubspec.yaml
test/common.dart
test/cool_test.dart
test/runner/json_reporter_test.dart

See changelog for specifics, unblocks https://github.com/flutter/flutter/issues/18195
cc @DanTup

Report original test location in the json_reporter if different

---

CHANGELOG.md
README.md
lib/src/runner.dart
lib/src/runner/debugger.dart
lib/src/runner/plugin/platform.dart
lib/src/runner/vm/environment.dart
lib/src/runner/vm/platform.dart
pubspec.yaml
test/runner/pause_after_load_test.dart

Closes https://github.com/dart-lang/test/issues/50
The blocking issue still has not been fixed: https://github.com/dart-lang/sdk/issues/31308
Provide a warning to use the suggested work around.

Support VM debugging

---

CHANGELOG.md
lib/src/util/io.dart

See comments in https://github.com/dart-lang/test/pull/849

Enable the default reporter and colors always if !windows

---

CHANGELOG.md
lib/src/frontend/async_matcher.dart
lib/src/frontend/expect.dart
pubspec.yaml
test/backend/declarer_test.dart
test/backend/invoker_test.dart
test/frontend/matcher/throws_type_test.dart
test/runner/hybrid_test.dart

Updated test to make new output of Type mismatch errors

feature: update exported pkg:matcher to `0.12.3`

---

CHANGELOG.md
pubspec.yaml

This closes: https://github.com/dart-lang/test/issues/558

Prep for 1.0.0

---

CHANGELOG.md
lib/src/runner/browser/platform.dart
pubspec.yaml

See https://github.com/dart-lang/build/pull/1647 for context

Serve files outside the path during precompiled tests

---

analysis_options.yaml
pubspec.yaml

use lints from pedantic-1.1.0

---

CHANGELOG.md
lib/src/bootstrap/browser.dart
lib/src/bootstrap/node.dart
lib/src/bootstrap/vm.dart
lib/src/executable.dart
pubspec.yaml
test/runner/configuration/top_level_test.dart
test/runner/pub_serve_test.dart

fixes https://github.com/dart-lang/test/issues/929

remove transformer warnings, prepare to publish 1.3.1

---

CHANGELOG.md
lib/src/runner/reporter/json.dart
pubspec.yaml
test/runner/precompiled_test.dart

Fixes https://github.com/dart-lang/test/issues/931

Fix json reporter bug with precompiled + dartdevc

---

CHANGELOG.md

* Allow remote_listener to be closed and sent an event on close.

Updated CHANGELOG.md to 1.3.4

---

pkgs/test_core/pubspec.yaml

Final piece before publishing both test_core and test

Update test:api dep

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/runner_test.dart
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Fixes https://github.com/dart-lang/test/issues/943

Add back import of dart:async to fix Future reference

---

pkgs/test/pubspec.yaml
pkgs/test_core/pubspec.yaml

Also change test_core dep for package:test which I missed in the last cl (thought it was a ^ dep... not sure why it isn't but 🤷‍♂️ )

remove dev deps from test_core

---

.travis.yml
pkgs/test/mono_pkg.yaml
pkgs/test_api/mono_pkg.yaml
pkgs/test_core/mono_pkg.yaml
tool/travis.sh

Run analyzer (at a minimum) across all packages at their oldest supported SDK

travis: Run dartfmt only on dev

---

pkgs/test/pubspec.yaml

last update before publishing 1.6.2

depend on test_api 0.2.5

---

pkgs/test/test/runner/pause_after_load_test.dart

- Skip tests that require  https://github.com/dart-lang/vm_service_client/pull/46

Fix broken head

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/vm/environment.dart
pkgs/test_core/lib/src/runner/vm/platform.dart
pkgs/test_core/pubspec.yaml

closes https://github.com/dart-lang/test/issues/976

Migrate to vm_service_lib

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Closes https://github.com/dart-lang/test/issues/1047

Depend on latest analyzer

---

pkgs/test/pubspec.yaml

Remove overrides

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/node/platform.dart

This should close https://github.com/dart-lang/test/issues/1059

Fix issue with Utf8Decoder and Node platform

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Update test to use analyzer 0.38.0

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/chrome.dart
pkgs/test/pubspec.yaml

Closes https://github.com/dart-lang/test/issues/1043

Add `--disable-dev-shm-usage` to the default Chrome flags

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/README.md
pkgs/test_core/pubspec.yaml

test_core: allow the latest pkg:vm_service

---

pkgs/test/CHANGELOG.md
pkgs/test/README.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/runner_test.dart
pkgs/test_core/lib/src/runner/configuration/args.dart

Expose sharding functionality

---

pkgs/test/pubspec.yaml

Changelog was properly updated but forgot to rev the pubspec version.

Prep to publish

---

pkgs/test/test/runner/configuration/randomize_order_test.dart
pkgs/test/test/runner/configuration/suite_test.dart
pkgs/test/test/runner/runner_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/configuration.dart
pkgs/test_core/lib/src/runner/configuration/args.dart
pkgs/test_core/lib/src/runner/engine.dart
pkgs/test_core/lib/src/runner/suite.dart

Add a --test-randomize-ordering-seed flag to run tests in random order

Add test randomization

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/declarer.dart
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Closes https://github.com/flutter/flutter/issues/28840#issuecomment-469458482

Extend synthetic test timeout

---

.travis.yml
pkgs/test/CHANGELOG.md
pkgs/test/mono_pkg.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/configuration/args.dart
tool/travis.sh

Towards https://github.com/dart-lang/test/issues/1145

Deprecate PhantomJS

---

pkgs/test/pubspec.yaml
pkgs/test_api/pubspec.yaml
pkgs/test_core/pubspec.yaml

The breaking changes were handled in #1125

Allow the latest boolean_selector

---

pkgs/test/test/runner/browser/compact_reporter_test.dart
pkgs/test/test/runner/configuration/platform_test.dart
pkgs/test/test/runner/engine_test.dart
pkgs/test/test/utils.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/engine.dart

I will add a test once getting agreement on a fix here. 
This should resolve https://github.com/dart-lang/test/issues/1159

Shared loading and running pool

---

pkgs/test/lib/src/runner/browser/chrome.dart

Occasionally the test runner would try to connect to Chrome before the test url has been fully loaded. Add a retry which resolves the recent coverage flakiness we have been seing.

Fix flakiness

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

release test_api/test_core/test

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml

Closes https://github.com/dart-lang/test/issues/1193

allow the latest shelf_packages_handler

---

pkgs/test/test/runner/runner_test.dart

The extra newlines between some options has been removed.

Update usage output test for new args package

---

pkgs/test_core/lib/src/runner/runner_suite.dart
pkgs/test_core/lib/src/runner/suite.dart

Work around https://github.com/dart-lang/sdk/issues/41108
Work around https://github.com/dart-lang/sdk/issues/41114

Add explicit (unnecessary) casts

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/chrome.dart
pkgs/test/pubspec.yaml

Enable Chrome Headless for Coverage

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/chrome.dart

Closes https://github.com/dart-lang/test/issues/1214

Handle file URIs during coverage collection

---

pkgs/test/test/runner/runner_test.dart
pkgs/test_core/lib/src/runner/configuration/reporters.dart

Closes https://github.com/dart-lang/test/issues/1223

Update URL to point to correct documentation

---

pkgs/test_api/lib/src/remote_listener.dart
pkgs/test_api/pubspec.yaml
pkgs/test_core/lib/src/runner/plugin/remote_platform_helpers.dart
pkgs/test_core/lib/src/runner/vm/platform.dart
pkgs/test_core/pubspec.yaml

Updates to get tests running with correct weak/strong checks

---

pkgs/test/test/runner/browser/runner_test.dart
pkgs/test/test/runner/node/runner_test.dart

See https://github.com/dart-lang/sdk/issues/41949

Skip test broken by changing stack trace URI

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/browser_manager.dart
pkgs/test/lib/src/runner/browser/chrome.dart
pkgs/test/lib/src/runner/browser/phantom_js.dart
pkgs/test/lib/src/runner/browser/platform.dart
pkgs/test/pubspec.yaml
pkgs/test/test/runner/browser/chrome_test.dart
pkgs/test/test/runner/browser/phantom_js_test.dart

Closes https://github.com/dart-lang/test/issues/1227

Prevent Headless With Pause After Load

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

This is a non-breaking change: https://github.com/dart-lang/coverage/pull/305

Support the latest package:coverage

---

.travis.yml
pkgs/test/mono_pkg.yaml
pkgs/test/test/runner/hybrid_test.dart
pkgs/test/test/runner/json_reporter_test.dart
pkgs/test/test/runner/precompiled_test.dart
pkgs/test_api/mono_pkg.yaml
pkgs/test_core/lib/src/runner/reporter/json.dart
pkgs/test_core/mono_pkg.yaml

After this the only remaining tests that are failing (other than node tests that I can't run locally) are the hybrid tests.

fix precompiled and json reporter tests

---

pkgs/test_api/pubspec.yaml
pkgs/test_core/pubspec.yaml

No new features require changes in the test runner.

Allow the latest package:matcher

---

pkgs/test_core/lib/src/runner/configuration.dart

The collection literals read more as what the collection is rather than
how it's computed.

Refactor calls to addAll to collection literals

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Required to roll package:vm_service forward in DevTools

Update package:vm_service dependency

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/skip_expect_test.dart
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/test_api.dart
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Closes #1355
Prepare to publish.

Add markTestSkipped API

---

pkgs/test/lib/src/runner/browser/browser.dart
pkgs/test/tool/host.dart

I didn't update the pubspec/changlog as I think this can go out with https://github.com/dart-lang/test/pull/1366

migrate to runZonedGuarded

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/platform.dart
pkgs/test/lib/src/runner/node/platform.dart
pkgs/test/lib/src/util/package_map.dart
pkgs/test/pubspec.yaml
pkgs/test/test/runner/hybrid_test.dart
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/frontend/spawn_hybrid.dart
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/runner_test.dart
pkgs/test_core/lib/src/runner/spawn_hybrid.dart
pkgs/test_core/lib/src/util/package_config.dart
pkgs/test_core/pubspec.yaml

Should fix https://github.com/dart-lang/test/issues/1363
I simplified the logic a bunch here, pushing all resolution of the uri to the server side.

Fix spawnHybridUri for NNBD

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/platform.dart
pkgs/test/lib/src/runner/node/platform.dart
pkgs/test/lib/src/util/package_map.dart
pkgs/test/pubspec.yaml
pkgs/test/test/runner/hybrid_test.dart
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/frontend/spawn_hybrid.dart
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/runner_test.dart
pkgs/test_core/lib/src/runner/spawn_hybrid.dart
pkgs/test_core/lib/src/util/package_config.dart
pkgs/test_core/pubspec.yaml

Backport of https://github.com/dart-lang/test/pull/1369, fixes https://github.com/dart-lang/test/issues/1372
After merging I will create a PR from the `pre-nnbd` branch into master to update the changelog.

Backport spawnHybridUri fix for NNBD

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/io.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/spawn_hybrid.dart
pkgs/test_core/pubspec.yaml

Closes https://github.com/dart-lang/test/issues/1387

Backport fix for spawnHybridUri on windows (#1384)

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Closes https://github.com/dart-lang/test/issues/1400

allow the latest version of the glob package

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Closes https://github.com/dart-lang/test/issues/1409

Support the latest vm_service

---

.github/workflows/dart.yml
pkgs/test/mono_pkg.yaml
pkgs/test/test/runner/runner_test.dart
pkgs/test_api/mono_pkg.yaml
pkgs/test_core/mono_pkg.yaml
tool/ci.sh

Regenerate with the latest `mono_repo`.

Drop --enable-experiment=non-nullable

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

also updated test_descriptor, which is only a dev dep

update to the latest analyzer

---

pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/metadata.dart
pkgs/test_api/lib/src/frontend/async_matcher.dart
pkgs/test_api/lib/src/frontend/expect.dart
pkgs/test_api/lib/src/frontend/future_matchers.dart
pkgs/test_api/lib/src/frontend/stream_matcher.dart
pkgs/test_api/lib/src/frontend/stream_matchers.dart
pkgs/test_api/lib/src/frontend/utils.dart
pkgs/test_api/pubspec.yaml
pkgs/test_api/test/frontend/expect_test.dart
pkgs/test_api/test/frontend/never_called_test.dart
pkgs/test_api/test/frontend/tear_down_all_test.dart
pkgs/test_api/test/utils.dart

This reverts commit 01bfee94c654816b8fa53f07f28bfe84b81e7f6e.

Revert "Revert import removals (#1420)"

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/executable.dart
pkgs/test_core/lib/src/util/io.dart
pkgs/test_core/pubspec.yaml

Prepare to release "dot" releases of pkg:test_core and pkg:test
I plan to backport these as well...

Don't create stdinLines just to cancel it

---

pkgs/test_core/lib/src/runner/reporter/json.dart

Expand a map with the frame info into the full message with `...`. This
keeps the structure more clear and makes it obvious that no other side
effects happen.
Refactor the method finding the frame info. Use `firstWhereOrNull` over
a for loop to find the frame matching the suite path. Separate out two
returns to make it clear that there are always `null` values for some
keys in the map, but not others.

Use collection expansion to add frame info

---

analysis_options.yaml
pkgs/test/lib/src/runner/browser/platform.dart
pkgs/test/test/runner/node/runner_test.dart
pkgs/test_core/lib/src/runner/debugger.dart
pkgs/test_core/lib/src/runner/spawn_hybrid.dart

Also ignores the safe_html lints at least for now.

fix lints with the new pedantic

---

pkgs/test/bin/test.dart
pkgs/test/lib/src/executable.dart
pkgs/test/lib/src/runner/browser/browser_manager.dart
pkgs/test/lib/src/runner/node/platform.dart
pkgs/test/pubspec.yaml
pkgs/test/test/runner/precompiled_test.dart

There are no more opted out files after this 🥳

update to latest node_preamble and finish the migration of package:test

---

.github/workflows/dart.yml
integration_tests/nnbd_opted_out/mono_pkg.yaml
integration_tests/nnbd_opted_out/pubspec.yaml
integration_tests/nnbd_opted_out/test/spawn_hybrid_code_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/spawn_hybrid.dart
pkgs/test_core/pubspec.yaml
tool/ci.sh

Fixes https://github.com/dart-lang/test/issues/1363

use the current language version for spawnHybridCode

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/chrome.dart
pkgs/test/pubspec.yaml

Closes https://github.com/dart-lang/test/issues/1423

Fix chrome coverage hanging

---

pkgs/test_api/lib/src/frontend/tags.dart
pkgs/test_api/lib/test_api.dart
pkgs/test_core/lib/src/runner/plugin/customizable_platform.dart
pkgs/test_core/lib/test_core.dart

This is minor, just fixing some broken doc links.

Fix documentation links

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/vm/test_compiler.dart
pkgs/test_core/pubspec.yaml

Fixes https://github.com/dart-lang/test/issues/1516

fix race condition between vm test compilation and isolate spawning

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

This release allows the latest vm_service.
cc @bkonyi

release test_core and test

---

.github/workflows/dart.yml
CONTRIBUTING.md
pkgs/test/README.md
pkgs/test/doc/architecture.md
pkgs/test/doc/configuration.md
pkgs/test/doc/json_reporter.md
pkgs/test/mono_pkg.yaml
pkgs/test/test/runner/runner_test.dart
pkgs/test_api/lib/src/backend/invoker.dart
pkgs/test_api/lib/src/scaffolding/spawn_hybrid.dart
pkgs/test_api/mono_pkg.yaml
pkgs/test_api/test/backend/invoker_test.dart
pkgs/test_core/lib/src/executable.dart
tool/ci.sh

Fixes https://github.com/dart-lang/test/issues/1550

update all wording from `pub run test` to `dart test`

---

pkgs/test/lib/src/runner/node/platform.dart
pkgs/test/test/runner/hybrid_test.dart
pkgs/test/test/runner/json_reporter_test.dart
pkgs/test/test/runner/json_reporter_utils.dart
pkgs/test_core/lib/src/runner/configuration/args.dart
pkgs/test_core/lib/src/runner/reporter/expanded.dart

Feel free to merge this once approved

reformat with the latest sdk

---

pkgs/test_core/lib/src/runner/engine.dart

Instantiate the subscription without callbacks and then immediately add
the callbacks to avoid `late` for the local variable that needs to be
referenced within the callbacks.
This pattern became the preferred approach for null safe stream
subscriptions after this migration was done.

Make some StreamSubscription locals non-late

---

pkgs/test/lib/src/runner/browser/platform.dart

Assume that all browsers will execute JS and remove the conditionals
that existed to support the long-gone Dartium browser.
Small refactor in `_pubServeSuite` to use short-circuits for both
atypical cases of preferring JS stack traces and compile errors. This
makes the similar cases where we drain and ignore the content look
similar. Use `Stream.drain` over `Stream.listen` with a no-op handler.

Remove support for non-JS browsers

---

pkgs/test_core/pubspec.yaml

this was accidentally added to dependency_overrides

move lints pkg to dev_dependencies

---

pkgs/test_api/CHANGELOG.md
pkgs/test_api/README.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/README.md
pkgs/test_core/pubspec.yaml

Drop silly title
Link to pkg:test, which is likely what most folks want

test_api, test_core: update readmes

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/remote_listener.dart
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Restore compatibility with the Flutter tool

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/test_failure.dart
pkgs/test_api/pubspec.yaml
pkgs/test_core/pubspec.yaml

Make TestFailure implement Exception

---

.github/workflows/dart.yml
integration_tests/nnbd_opted_in/mono_pkg.yaml
integration_tests/nnbd_opted_out/mono_pkg.yaml
pkgs/test/CHANGELOG.md
pkgs/test/mono_pkg.yaml
pkgs/test/pubspec.yaml
pkgs/test_api/mono_pkg.yaml
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/mono_pkg.yaml
pkgs/test_core/pubspec.yaml
tool/ci.sh

- Latest mono_repo
- Support latest pkg:analyzer, release test, test_api

latest analyzer

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

release test_core 0.4.11 and test 1.20.1

---

pkgs/test_api/lib/scaffolding.dart

Also fix a bunch of spelling throughout the monorepo

Canonicalize APIs exported by pkg:test_api

---

pkgs/test/test/runner/runner_test.dart

Test was previously order dependent, it no longer is

fix runner test for multiple failures

---

.github/workflows/dart.yml
integration_tests/nnbd_opted_out/mono_pkg.yaml
pkgs/checks/mono_pkg.yaml
pkgs/test/mono_pkg.yaml
pkgs/test_api/mono_pkg.yaml
pkgs/test_core/mono_pkg.yaml
tool/ci.sh

Latest pkg:mono_repo
Add note to all mono_pkg files

Enable CI for pkg:checks

---

.github/workflows/dart.yml
pkgs/checks/lib/src/extensions/core.dart
pkgs/checks/mono_pkg.yaml
pkgs/checks/test/extensions/core_test.dart
tool/ci.sh

- Cleanup mono_repo yaml files
- Update to latest mono_repo
- check: 100% code coverage of core extensions

checks fun

---

pkgs/checks/test/extensions/function_test.dart
pkgs/checks/test/extensions/math_test.dart
pkgs/checks/test/test_shared.dart

- checks: test MathChecks
- checks: test FunctionChecks
- checks: improve output of toStringEquals test extension

more check checks

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

this will allow us to remove some overrides in that package as well

allow latest frontend_server_client

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Prepare to publish

---

.github/workflows/dart.yml
pkgs/checks/mono_pkg.yaml
pkgs/checks/pubspec.yaml
pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/mono_pkg.yaml
pkgs/test_core/pubspec.yaml
tool/ci.sh

Fixes https://github.com/dart-lang/test/issues/1765

Latest pkg:analyzer, prepare for releases

---

pkgs/checks/README.md

use yaml code block
use HTTPS URI for repo – will work for more users

checks: tweaks to readme

---

pkgs/test/README.md

Bug: https://github.com/dart-lang/.github/issues/32

Add scorecard badge to test repo.

---

pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml

Expand test_api pubspec description

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

prep packages to publish

---

.github/workflows/dart.yml
integration_tests/wasm/mono_pkg.yaml
tool/ci.sh

cc @joshualitt , tracking issue is https://github.com/dart-lang/test/issues/1790

disable wasm tests for now as they are failing

---

.github/dependabot.yml
.github/workflows/no-response.yml
.github/workflows/scorecards-analysis.yml

Dependabot
GitHub Action
No Response

blast_repo fixes

---

pkgs/checks/test/extensions/async_test.dart

Now with 100% code coverage on extensions

checks: finish async tests

---

.github/workflows/dart.yml

This reverts commit 986045c47abb1627a59b2a6f6cd99efed7d6397c.

Restore mono_repo config

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/platform.dart
pkgs/test/lib/src/runner/wasm/platform.dart
pkgs/test/lib/src/util/math.dart

fixes https://github.com/dart-lang/test/issues/1816

change the url secrets for browser tests to be alphanumeric characters

---

pkgs/checks/lib/src/extensions/iterable.dart
pkgs/checks/test/extensions/iterable_test.dart

Checks that every value in an iterable satisfies a given condition. If
any element fails the condition the "Which" will include details of the
inner failure.

Add Iterable.every extension

---

pkgs/checks/lib/src/extensions/string.dart
pkgs/checks/test/extensions/string_test.dart

Implemented based on `stringContainsInOrder` from `package:matcher`. Add
the condition and tests.

Add String.containsInOrder condition

---

.github/workflows/no-response.yml

Run no response daily

---

pkgs/checks/lib/src/extensions/core.dart
pkgs/checks/test/extensions/core_test.dart

Take an `Iterable<Condition<T>>` and succeed if any condition matches,
fail if all conditions do not match.

Add anyOf condition

---

pkgs/checks/lib/src/checks.dart
pkgs/checks/lib/src/collection_equality.dart
pkgs/checks/lib/src/extensions/async.dart
pkgs/checks/pubspec.yaml
pkgs/checks/test/extensions/async_test.dart
pkgs/checks/test/test_shared.dart

This has been in the analysis options for the entire repo, but not
applying to this package because the package was missing. Add the
dependency, and fix the lints that are newly surfaced.

Add missing dependency on package:lints

---

pkgs/checks/lib/src/extensions/string.dart
pkgs/checks/test/extensions/string_test.dart

Takes a RegExp and succeeds if the input string matches.

Add String.matches condition

---

pkgs/checks/CHANGELOG.md
pkgs/checks/LICENSE
pkgs/checks/pubspec.yaml

Add LICENSE, CHANGELOG, and a repository field.

Add missing pub requirements

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/executable_settings.dart
pkgs/test/pubspec.yaml
pkgs/test/test/runner/browser/chrome_test.dart

Closes https://github.com/dart-lang/test/issues/1862

Add support for CHROME_EXECUTABLE environment variable

---

pkgs/test/test/runner/browser/compact_reporter_test.dart
pkgs/test/test/runner/browser/expanded_reporter_test.dart
pkgs/test/test/runner/configuration/platform_test.dart
pkgs/test/test/runner/configuration/top_level_test.dart
pkgs/test/test/runner/github_reporter_test.dart
pkgs/test/test/runner/pause_after_load_test.dart
pkgs/test/test/runner/runner_test.dart
pkgs/test_core/lib/src/runner/configuration/args.dart

This just fixes the existing tests in preparation for adding new tests.

fix tests in the compiler branch

---

pkgs/test/README.md
pkgs/test/doc/configuration.md

~Note that the top level configuration here doesn't yet work, I will add support and tests in a separate PR.~ Nevermind it does work, added a test to the other PR

Add compiler docs

---

.github/workflows/publish.yaml
README.md
integration_tests/wasm/pubspec.yaml
legacy_tests/nnbd_opted_in/pubspec.yaml
legacy_tests/nnbd_opted_in_with_optout/pubspec.yaml
legacy_tests/nnbd_opted_out/pubspec.yaml
pkgs/checks/CHANGELOG.md
pkgs/test_core/CHANGELOG.md

Add auto-publish configuration

---

pkgs/checks/CHANGELOG.md
pkgs/checks/doc/migrating_from_matcher.md
pkgs/checks/pubspec.yaml
pkgs/test/test/foo_test.dart

pairwiseComparseTo -> pairwiseComparesTo

Fix typo in migration doc

---

pkgs/test/CHANGELOG.md

update changelog version in test to use ##

---

.github/workflows/dart.yml

Related to https://github.com/dart-lang/setup-dart/issues/79 - dogfood the new version of `setup-dart`.

dogfood the new setup-dart action

---

.github/dependabot.yml
.github/workflows/dart.yml
tool/ci.sh

- rev the the latest mono_repo and regenerate the workflow file
- update the dependabot config to apply an `autosubmit` label
---
<details>
<summary>Contribution guidelines</summary>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding …

update the mono_repo and dependabot configs

---

pkgs/test/lib/src/runner/browser/browser_manager.dart
pkgs/test_api/lib/src/backend/configuration/timeout.dart
pkgs/test_api/lib/src/backend/message.dart
pkgs/test_api/lib/src/backend/operating_system.dart
pkgs/test_api/lib/src/backend/platform_selector.dart
pkgs/test_api/lib/src/backend/remote_exception.dart
pkgs/test_api/lib/src/backend/state.dart
pkgs/test_core/lib/src/runner/spawn_hybrid.dart
pkgs/test_core/lib/src/runner/vm/platform.dart

Find switch statements which had all cases either immediately `return`
or `throw` and refactor them to returned switch expressions.

Use switch expressions for switch/return pattern

---

pkgs/test/tool/host.dart

See https://github.com/dart-lang/linter/issues/4474

Ignore a false positive for unreachable_from_main

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Closes https://github.com/dart-lang/test/issues/2044

allow the latest analyzer (6.x.x)

---

pkgs/checks/doc/migrating_from_matcher.md

Contributes to https://github.com/dart-lang/linter/issues/4460 and https://github.com/dart-lang/site-www/issues/4499

Update link from old linter site to dart.dev

---

integration_tests/wasm/test/hello_world_test.dart

See https://github.com/dart-lang/sdk/issues/53493

skip failing wasm tests

---

pkgs/test/CHANGELOG.md
pkgs/test/README.md
pkgs/test/pubspec.yaml

See https://github.com/dart-lang/site-www/issues/5215

Mention integration_test as an ignored directory

---

integration_tests/spawn_hybrid/pubspec.yaml
integration_tests/spawn_hybrid/test/hybrid_test.dart
integration_tests/spawn_hybrid/test/hybrid_test_io.dart
integration_tests/spawn_hybrid/test/subdir/hybrid_test.dart
pkgs/checks/lib/src/checks.dart
pkgs/checks/lib/src/collection_equality.dart
pkgs/checks/lib/src/extensions/async.dart
pkgs/checks/lib/src/extensions/core.dart
pkgs/checks/lib/src/extensions/function.dart
pkgs/checks/lib/src/extensions/iterable.dart
pkgs/checks/lib/src/extensions/map.dart
pkgs/checks/lib/src/extensions/math.dart
pkgs/checks/lib/src/extensions/string.dart
pkgs/checks/pubspec.yaml
pkgs/checks/test/context_test.dart
pkgs/checks/test/extensions/collection_equality_test.dart
pkgs/checks/test/extensions/core_test.dart
pkgs/checks/test/extensions/iterable_test.dart
pkgs/checks/test/extensions/map_test.dart
pkgs/checks/test/failure_message_test.dart
pkgs/test_api/pubspec.yaml

Remove a <R> type parameter from checks that seems unused

Update to latest version of lints

---

pkgs/test/test/runner/runner_test.dart

Hit a race condition with the auto submit bot in https://github.com/dart-lang/test/pull/2144 which caused it to land an untested commit. This fixes the tests.

fix broken tests

---

pkgs/test_core/lib/src/runner/vm/platform.dart

Fixes an issue that arises internally from https://github.com/dart-lang/test/pull/2148

fix precompiled vm tests loaded from a package: uri

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/util/package_config.dart
pkgs/test_core/pubspec.yaml

Should fix an internal breakage with the latest release

handle missing package config files

---

pkgs/test_core/lib/src/util/package_config.dart

See https://github.com/dart-lang/test/pull/2158#pullrequestreview-1780440589

small cleanup in try/catch, remove unused catch

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/scaffolding.dart
pkgs/test_core/pubspec.yaml

Oops! Thanks for the call out @yjbanov!

Also add `@doNotSubmit` to scaffolding.dart.

---

pkgs/test/pubspec.yaml

Topics help users on pub.dev discover packages, and related packages.
You can see a list of [topics here](https://pub.dev/topics).
You can also make your own topics.
Topics are added to pubspec.yaml as follows:
```
topics:
- my-topic
- some-other-topic
```
See also: https://dart.dev/tools/pub/pubspec#topics

Add `topics` to  package "test" `pubspec.yaml`

---

integration_tests/wasm/test/hello_world_test.dart
pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/wasm_compiler_pool.dart
pkgs/test_core/pubspec.yaml

Fixes https://github.com/dart-lang/test/issues/2240

enable asserts in dart2wasm tests

---

pkgs/test_api/test/import_restrictions_test.dart

ContextLocator is deprecated in favor of AnalysisContextCollection.

Migrate off deprecated Analyzer API

---

.github/workflows/dart.yml
integration_tests/wasm/mono_pkg.yaml
tool/ci.sh

Update `integration_tests/wasm/mono_pkg.yaml` based on
`integration_tests/regression/mono_pkg.yaml` and re-run `mono_repo
generate`.

Run dart2wasm integration test on Windows

---

.github/workflows/dart.yml
integration_tests/regression/pubspec.yaml
integration_tests/spawn_hybrid/pubspec.yaml
integration_tests/wasm/pubspec.yaml
pkgs/checks/CHANGELOG.md
pkgs/checks/pubspec.yaml
pkgs/matcher/lib/mirror_matchers.dart
pkgs/matcher/lib/src/type_matcher.dart
pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml
pubspec.yaml

Allow latest pkg:analyzer, bump min SDK to stable release

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/vm/test_compiler.dart
pkgs/test_core/pubspec.yaml

The experiment flag will be on by default so it is not passed as argument anymore.
Accompanying Dart CL: https://dart-review.googlesource.com/c/sdk/+/429920

[native assets] Graduate to preview
