dart-lang/test

README.md

only constant values can be used in annotations, `new` is invalid here
in the 2nd case it's not necessary but doesn't hurt either

minor fixes in README.md example code

---

pubspec.yaml

I tried `pub downgrade` and I got the error
`Class 'LazyTrace' has no instance method 'foldFrames' with matching arguments.`
After limiting stack_trace to '^1.2.1' it worked again.

stack_trace 1.2.0 isn't compatible with test.

---

README.md

The label should be `transformers`, not `transformer`.

Fix typo in sample YAML

---

CHANGELOG.md
lib/test_controller.js
pubspec.yaml

Some tests, especially those using HTML imports, aren't ready to be run
when readyState is set to "complete".
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dart-lang/test/121)

Revert 06cf6268b35a426e326079a1a829df3839b43038.

---

README.md

Fix link to `throwsA()`

---

lib/src/runner/browser/server.dart
test/runner/pub_serve_test.dart

When the  `--pub-serve` option is used, JavaScript source maps are fetched for test suites, which causes the test files to be compiled via dart2js.
These source maps are fetched unnecessarily when run in Dartium and content shell, which causes  unnecessary dart2js compilation.
This compilation can take a while, and makes running browser tests in Dartium and content shell while using `--pub-serve` much more sluggish.
* Only fetch the source maps for test suites if `browser.isJs` is true.
* Add test case with content shell that verifies that test suite load errors are still handled gracefully when `browser.isJs == false`.

When using --pub-serve, only compile tests when browser.isJS is true

---

lib/test.dart
test/backend/declarer_test.dart

There was an issue created, https://github.com/dart-lang/test/issues/372, that requested the ability to pass in an object as the description for the group and test methods.  
```
group(MyAwesomeClass, () {
...
});
```
This change allows a user to do that and is accompanied with unit tests exercising the intended change.

Allow object to be passed in as a group / test description

---

README.md

A `doc/configuration.md` file was just added to replace `doc/package_config.md`. The old file was changed to be a symlink pointing to the new file, but that doesn't work with GitHub navigation (click on the "the full documentation" link here: https://github.com/dart-lang/test#whole-package-configuration).
This updates the links in the README to point to the new `configuration.md`.
@nex3

Update README links to configuration documentation

---

.analysis_options
CHANGELOG.md
lib/html_config.dart
lib/vm_config.dart
pubspec.yaml

Looks like we hadn't run the analyzer against all the top-level
libraries.

Fix additional strong-mode warnings.

---

CHANGELOG.md
lib/src/backend/metadata.dart
pubspec.yaml
test/backend/metadata_test.dart

Properly preserve tags through Metadata.change().

---

lib/src/utils.dart

It was printing the wrong number of seconds for durations longer than a
minute.
Closes #463

Fix a bug in niceDuration().

---

lib/src/runner.dart
lib/src/runner/browser/compiler_pool.dart
lib/src/runner/browser/platform.dart
lib/src/runner/configuration.dart
lib/src/runner/debugger.dart
lib/src/runner/loader.dart
lib/src/runner/reporter/compact.dart
lib/src/runner/reporter/expanded.dart
lib/src/runner/reporter/json.dart
lib/src/runner/vm/platform.dart
test/runner/browser/loader_test.dart
test/runner/loader_test.dart

This introduces a zone-scoped `Configuration.current`. This makes it
much easier to propagate the configuration everywhere it needs to go,
especially to plugins.
For #457

Refactor Configuration.

---

CHANGELOG.md
lib/src/backend/declarer.dart
lib/src/runner/plugin/platform_helpers.dart
lib/src/runner/remote_listener.dart
pubspec.yaml

Stack traces are now only captured for the JSON reporter. Capturing
traces was slow enough to be a serious problem for test suites with many
tests.
Closes #457

Don't capture stack traces by default.

---

CHANGELOG.md
lib/src/runner/browser/browser_manager.dart
pubspec.yaml

If a web test emitted any kind of message after the browser manager was
closed, the debugging timer would reset and cause the VM not to exit for
an extra three seconds.

Fix a race condition in BrowserManager.

---

lib/src/backend/metadata.dart
lib/src/runner.dart
lib/src/runner/browser/browser_manager.dart
lib/src/runner/browser/compiler_pool.dart
lib/src/runner/browser/platform.dart
lib/src/runner/configuration.dart
lib/src/runner/configuration/load.dart
lib/src/runner/configuration/suite.dart
lib/src/runner/engine.dart
lib/src/runner/load_suite.dart
lib/src/runner/loader.dart
lib/src/runner/parse_metadata.dart
lib/src/runner/plugin/platform.dart
lib/src/runner/plugin/platform_helpers.dart
lib/src/runner/reporter/compact.dart
lib/src/runner/reporter/expanded.dart
lib/src/runner/reporter/json.dart
lib/src/runner/runner_suite.dart
lib/test.dart
pubspec.yaml
test/runner/browser/loader_test.dart
test/runner/configuration/configuration_test.dart
test/runner/configuration/suite_test.dart
test/runner/engine_test.dart
test/runner/load_suite_test.dart
test/runner/loader_test.dart
test/utils.dart

This tracks configuration that makes sense to apply to test suites, as
opposed to Configuration which applies to an entire run and Metadata
which applies to individual tests. This is intended to make it easier
for load separate configurations for separate targets in a live test
runner.
@goderbauer

Factor out a SuiteConfiguration object.

---

CHANGELOG.md
doc/json_reporter.md
json_reporter.schema.json
lib/src/runner/browser/browser.dart
lib/src/runner/browser/browser_manager.dart
lib/src/runner/browser/chrome.dart
lib/src/runner/browser/content_shell.dart
lib/src/runner/browser/dartium.dart
lib/src/runner/browser/static/host.dart
lib/src/runner/browser/static/host.dart.js
lib/src/runner/debugger.dart
lib/src/runner/engine.dart
lib/src/runner/environment.dart
lib/src/runner/plugin/environment.dart
lib/src/runner/reporter/json.dart
lib/src/util/io.dart
pubspec.yaml

Add debugging support for the JSON reporter.

---

CHANGELOG.md
lib/src/runner/browser/dartium.dart
pubspec.yaml

Dartium wasn't emitting any standard IO on Windows, which caused us to
stall out waiting for the Observatory URL in debug mode.
See dart-lang/sdk#28034
Closes #425

Fix Dartium debugging on Windows.

---

CHANGELOG.md
lib/src/frontend/expect_async.dart

This worked with the old expectAsync(), but was broken when the new
functions were introduced. It was causing an analysis error in the
tests.

Make expectAsync work with optional arguments.

---

lib/src/executable.dart
lib/src/runner/configuration.dart
lib/src/runner/configuration/args.dart
test/runner/configuration/configuration_test.dart
test/runner/configuration/top_level_test.dart

This is necessary to make configuration work with Google's internal
build system.

Add a hidden --configuration flag.

---

lib/src/frontend/spawn_hybrid.dart
pubspec.yaml
test/runner/hybrid_test.dart

Users can pass stayAlive: true to keep them open, but this helps ensure
that they won't accidentally have a bunch of isolates hanging around
between tests.
Closes #109

Default to eagerly closing hybrid isolates.

---

pubspec.yaml

dart-lang/vm_service_client#13 has now landed.

Remove a dependency override.

---

CHANGELOG.md
doc/json_reporter.md
json_reporter.schema.json
lib/src/executable.dart
lib/src/runner.dart
lib/src/runner/browser/browser_manager.dart
lib/src/runner/debugger.dart
lib/src/runner/environment.dart
lib/src/runner/plugin/environment.dart
lib/src/runner/reporter/json.dart
lib/src/runner/vm/environment.dart
lib/src/runner/vm/platform.dart
pubspec.yaml
test/runner/json_debugging_test.dart
test/runner/json_reporter_test.dart

This adds a JSON-RPC 2.0-via-WebSocket protocol for communicating with
the test runner and telling it to resume running tests after breakpoints
are added. Talking to the runner via JavaScript methods in the browser
is still supported for backwards-compatibility, but is deprecated.
Closes #50

Add JSON reporter support for debugging VM tests.

---

lib/src/frontend/throws_matcher.dart

Fixes error when running with pub.
Failed to precompile test:test:
'package:test/src/frontend/throws_matcher.dart': error: line 17 pos 41: unexpected token ';'

Drop semicolon following annotation

---

CHANGELOG.md
lib/src/backend/invoker.dart
lib/test.dart
test/backend/invoker_test.dart

This prints debugging information only if the test actually fails.

Add a printOnFailure() function.

---

lib/src/runner/engine.dart
lib/src/runner/plugin/platform_helpers.dart
pubspec.yaml

If the StreamChannel returned by PlatformPlugin.loadChannel() emits an
error through sink.close(), that error is now properly treated as an
error in the load suite for that channel.
Closes #542

Gracefully handle platform errors on close.

---

CHANGELOG.md
pubspec.yaml

We're using a feature that was introduced in
1.6.0 (Disconnector.disconnect's return value).
Closes #556

Fix the stream_channel dependency.

---

lib/src/runner/browser/browser.dart

Verified on Ubuntu 14.04:
➜  test git:(LinuxFixes) ✗ pub run test
00:20 +92: test/runner/hybrid_test.dart: spawnHybridCode() kills the isolate when the test closes the channel
Skip: Enable when sdk#28081 is fixed.
00:20 +92 ~1: test/runner/hybrid_test.dart: spawnHybridCode() kills the isolate when the hybrid isolate closes the channel
Skip: Enable when sdk#28081 is fixed.
01:23 +343 ~2: test/runner/browser/content_shell_test.dart: starts content shell with the given URL
Skip: Failing with mysterious WebSocket issues.
09:16 +919 ~3: All tests passed!
Also verified no impact on Mac.

Correctly kill Dartium on Linux

---

lib/src/backend/test_platform.dart
lib/src/runner.dart
lib/src/runner/configuration.dart
lib/src/runner/configuration/args.dart
lib/src/runner/configuration/load.dart
lib/src/runner/configuration/reporters.dart
lib/src/runner/configuration/values.dart
test/runner/configuration/configuration_test.dart

Adding hooks for new reporters and test platforms. These hooks are not intended to be a part of the external API and thus are aptly documented.

Extensible reporters and test platforms

---

.travis.yml
test/runner/load_suite_test.dart

Runs the following tests:
- dartanalyzer
- dartfmt
- vm tests excluding all browser tags
- dartium tests
Note that the dev SDK appears to leave pub running after a successful run of tests. This will need to be investigated further.
Passing travis run: https://travis-ci.org/grouma/test/builds/221886642

Add Travis support

---

lib/bootstrap/browser.dart
lib/bootstrap/vm.dart
lib/pub_serve.dart

This proposed change takes the code generated by the pub serve transformer and migrates all the business logic into two new "public" entry points. The methods exposed are marked as `@deprecated` (just to discourage direct use) and have a comment explaining that they should not be used directly. I also prefixed the names with `internal` as yet another signal not to rely on these files directly.
The future dartdevc transformer also doesn't support importing files from lib/src directly which are not included transitively by at least one public entry point (defined as a .dart file under `lib` but not `lib/src`). We could solve this in a couple other ways, but I think this is the most logical.
This also simplifies the transformer implementation, and more importantly it makes it so the …

Create psuedo-public entrypoints for bootstrapping vm/browser tests.

---

test/runner/compact_reporter_test.dart

Travis processes tests much slower which can result in additional lines in a report. Use containsAllInOrder to account for this issue.

Fix Travis flakiness

---

lib/src/executable.dart

Some internal coverage tools require the process to remain open. Hack to ensure Travis is not flaky while not impacting these internal tools.

Exit early on Travis

---

lib/src/backend/invoker.dart
test/backend/invoker_test.dart

Trivial PR to fix a small typo in warning message suggesting to use complete stack traces.

Fix recieve -> receive typo

---

CHANGELOG.md
lib/src/frontend/throws_matcher.dart
pubspec.yaml
test/frontend/matcher/throws_test.dart

throws* matchers now support () -> Future

---

doc/configuration.md
lib/src/runner/configuration/load.dart
test/runner/configuration/top_level_error_test.dart
test/runner/configuration/top_level_test.dart

Adds a configuration field for chain-stack-traces. See the following issue for more details.
https://github.com/dart-lang/test/issues/615

Add file configuration for chain-stack-traces

---

lib/src/runner/browser/content_shell.dart

Content shell version 50 has an updated sandbox console message. See:
https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md

Update content shell startup check for version 50

---

lib/src/backend/invoker.dart
test/backend/invoker_test.dart

Fix a spelling mistake of 'receive' -> 'receive'.

Update the failure message emitted by invoker.dart

---

lib/pub_serve.dart
lib/src/bootstrap/browser.dart
lib/src/bootstrap/vm.dart

The dartdevc support in pub no longer requires files to be imported by an entry point, so these can be moved under `lib/src` now. I also removed the `@deprecated` annotation since we don't need to send that extra signal any more to not depend on these files (it should be more clean by convention now).

move bootstrap code to lib/src

---

CHANGELOG.md
lib/src/runner/plugin/platform_helpers.dart
test/runner/browser/runner_test.dart

In Dartium and Content-Shell, run time errors can cause the test to hang as we wait to deserialize the test suite. Add a timeout to prevent this. 
Ideally we would propagate any console errors but I have been unsuccessful in doing so.

Add timeout for deserializing a test suite

---

.travis.yml
dart_test.yaml
test/runner/browser/loader_test.dart
test/runner/json_reporter_test.dart
test/runner/signal_test.dart

As far as I can tell, all tests are passing other than the few that are skipped due to dart-lang/sdk#29693 and an as-yet-unidentified issue with signal-handling for browsers that seems to only appear on Travis. It's possible that there will be some flakes, though; if that seems to happen frequently, we may want to delay landing this until #618 is done.

Enable browser tests on Travis.

---

lib/src/runner/browser/content_shell.dart

The latest version of Content-Shell on Mac has a bug in which error messages do not properly propagate. If we see evidence of this issue, we then must assume Content-Shell started up correctly. Also, as an additional safety measure, provide a timeout while we try to read the error stream. It is assumed that if we did not find a critical error while waiting on the error stream, Content-Shell started successfully.
This will resolve: https://github.com/dart-lang/angular_test/issues/63

Fix for content shell on Mac

---

analysis_options.yaml
lib/src/runner/parse_metadata.dart
lib/src/util/string_literal_iterator.dart
pubspec.yaml

Enable associated lint
Verified the new lower bound (v0.26.4 from Dec 7, 2015) works

Move off src imports from pkg/analyzer

---

.travis.yml
pubspec.yaml

Dartium tests are included in the sharded tests so explicitly running with platform Dartium should be redundant. Also remove 1.22.1 given the SDK release today.
We should have a discussion around which versions of the SDK we would like to run the browser tests. I'm under the opinion that we lose some confidence and only run browser tests for the stable SDK. I'm not a fan of the very long Travis runs. It also negatively impacts other teams as we starve Travis of resources.

Trim Travis tests

---

CHANGELOG.md
lib/src/backend/invoker.dart
lib/src/utils.dart
test/backend/declarer_test.dart
test/frontend/add_tear_down_test.dart

We used to create a new error zone for each call to
waitForOutstandingCallbacks(), which meant that asynchronous errors
couldn't be safely passed around within a single test. Now we have a
single error handler that manually checks the zone in which the error
was thrown.

Run tear-downs in the same error zone as tests.

---

CHANGELOG.md
pubspec.yaml

The IPv6 change was incorrectly stated to be with release 22+1. Updating changelog and preparing for release.

Prepare for release

---

CHANGELOG.md
doc/configuration.md
lib/src/frontend/stream_matcher.dart
lib/src/frontend/test_chain.dart
lib/src/frontend/throws_matcher.dart
lib/src/runner/browser/browser_manager.dart
lib/src/runner/configuration.dart
lib/src/runner/configuration/load.dart
lib/src/runner/plugin/platform_helpers.dart
lib/src/runner/remote_listener.dart
lib/src/runner/reporter/compact.dart
lib/src/runner/reporter/expanded.dart
lib/src/runner/reporter/json.dart
lib/src/runner/runner_test.dart
lib/src/util/stack_trace_mapper.dart
lib/src/utils.dart
test/frontend/test_chain_test.dart
test/runner/compact_reporter_test.dart
test/runner/configuration/top_level_error_test.dart

- Allow StackTraceMapper to be serialized and deserialized
- Send StackTraceMapper to remote isolate
- Move all test chaining to the remote isolate
- Enable new configurations for stack trace folding
- Add corresponding tests
This will close https://github.com/dart-lang/test/issues/416

Configurable package folding

---

CHANGELOG.md
analysis_options.yaml
lib/src/frontend/stream_matcher.dart
lib/src/frontend/throws_matcher.dart
lib/src/runner/reporter/json.dart
pubspec.yaml

These warnings will cause issues with Google3. Upgrading the warnings to errors and resolving the issues.

Remove unused imports

---

CHANGELOG.md
pubspec.yaml

Widens version constraint on `analyzer` to play nice w/ latest alpha.  (Required by linter.)
@grouma

Bump to 0.12.24+1.

---

.travis.yml
CHANGELOG.md
lib/src/executable.dart
pubspec.yaml

Forcing an exit on Travis is negatively impacting those that collect code coverage after a test is run. The belief is that this hack is necessary only for a subset of tests within package:test itself. Updating the logic so that it makes use of a more specific environment variable.

Fix travis hack

---

CHANGELOG.md
lib/src/runner/plugin/platform_helpers.dart
pubspec.yaml

Extending deserialize timeout as it was impacting long running coverage tests within Google3.

Extend timeout

---

lib/src/frontend/expect_async.dart

Fixes #674
dynamic is treated as the bottom type for function arguments, but this
will soon change. Null will continue to be the bottom type.
The question we are asking is "Is this a function that takes one
argument", when dynamic is no longer the bottom type the question will
become "Is this a function that takes one dynamic argument", and a
function which take one argument of a specific type does *not* take a
dynamic argument.

Replace implicit dynamic with Null in arity checks

---

CHANGELOG.md
lib/dart.js
pubspec.yaml

Exposing a way for tests to send a load exception to the test server. This will be used by DDC tests here: https://github.com/dart-lang/sdk/blob/0edc00171a9881d330b633cf0f43b0654e2653c1/pkg/dev_compiler/lib/js/legacy/dart_library.js#L16

Load Exception

---

dart_test.yaml

Submits in the recent past have been flaky. It looks like these are isolated to Node and Pub tests. Increasing these timeouts to hopefully reduce the chance of failures.

Reduce Travis flakiness

---

lib/src/runner.dart
lib/src/runner/browser/platform.dart
lib/src/runner/configuration.dart
lib/src/runner/configuration/args.dart
lib/src/runner/configuration/load.dart
lib/src/runner/configuration/suite.dart
lib/src/runner/loader.dart
test/runner/browser/loader_test.dart
test/runner/configuration/suite_test.dart
test/runner/configuration/top_level_error_test.dart

This will make it easier to define custom test platforms (both via #391
and #99) in the future. Because those platforms will be loaded based on
the configuration, requiring knowledge of them to parse the user's
platform arguments would produce an unresolvable circular dependency.

Store test platforms as strings in Configuration

---

lib/src/backend/declarer.dart
lib/src/backend/metadata.dart
lib/src/backend/platform_selector.dart
lib/src/executable.dart
lib/src/runner.dart
lib/src/runner/configuration.dart
lib/src/runner/configuration/args.dart
lib/src/runner/configuration/load.dart
lib/src/runner/configuration/platform_selection.dart
lib/src/runner/configuration/suite.dart
lib/src/runner/loader.dart
lib/src/runner/parse_metadata.dart
lib/src/runner/remote_listener.dart
lib/test.dart
test/backend/metadata_test.dart
test/runner/browser/loader_test.dart
test/runner/configuration/platform_test.dart
test/runner/configuration/suite_test.dart
test/runner/parse_metadata_test.dart
test/utils.dart

We want users to be able to dynamically define new platforms, which
means we need infrastructure in place for piping those platforms to
places that previously assumed TestPlatform.all was a full list of
available platforms. PlatformSelector is the trickiest example, since
it's parsed in a number of different places and needs to provide useful
feedback to users when they use an undefined platform.
This splits parsing and platform validation into two separate steps.
Validation will be done immediately after parsing when the selectors
come from top-level annotations or parameters passed to test() or
group(), but selectors defined in configuration files are now parsed
only after all configuration is parsed. This will allow new platforms to
be defined *and* referenced in configuration files. …

Don't use TestPlatform.all in PlatformSelector

---

lib/src/backend/declarer.dart
lib/src/backend/metadata.dart
lib/src/backend/platform_selector.dart
lib/src/runner/configuration/suite.dart
lib/src/runner/loader.dart
lib/src/runner/parse_metadata.dart
lib/src/runner/plugin/platform_helpers.dart
lib/src/runner/remote_listener.dart
lib/test.dart
test/backend/metadata_test.dart
test/runner/parse_metadata_test.dart
test/utils.dart

This makes it easier to add platforms that extend existing platforms
without running into serialization headaches. It also cleans up the
Declarer API and means we're sending less redundant data between
isolates.
See #391

Validate platform selectors against string sets

---

CHANGELOG.md
lib/src/frontend/spawn_hybrid.dart
pubspec.yaml
test/runner/hybrid_test.dart

This makes it possible to use the same spawnHybridUri() call from
multiple test files that are in different places in the filesystem.

Allow spawnHybridUri() to take root-relative URLs

---

pubspec.yaml

I hit an error earlier when running tests in a repo whose dependencies hadn't been updated in a while:
> ```
> NoSuchMethodError: No static method 'capture' with matching arguments declared in class 'Chain'.
> Receiver: Type: class 'Chain'
> Tried calling: capture(Closure: () => dynamic, when: true)
> Found: capture(() => dynamic, {ChainHandler onError})
> #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:196)
> #1      Invoker._onRun (package:test/src/backend/invoker.dart:336)
> ...
> ```
The `when` parameter to `Chain.capture` is currently used in [invoker.dart#L388](https://github.com/dart-lang/test/blob/master/lib/src/backend/invoker.dart#L388), which wasn't added until stack_trace [1.6.0](https://github.com/dart-lang/stack_trace/blob/master/CHANGELOG.md#160). …

Fix lower bound of stack_trace

---

CHANGELOG.md
lib/src/runner/browser/browser.dart
pubspec.yaml

We declared an incorrect constraint for package stack_trace. This was fixed in https://github.com/dart-lang/test/pull/714
Also fixing potential test hangs by manually closing IO streams.
Preparing for a new release.

Fix test hang and prep for release - 0.12.26+1

---

CHANGELOG.md
lib/src/runner/reporter/compact.dart
lib/src/runner/reporter/expanded.dart
lib/src/util/io.dart
lib/src/utils.dart
pubspec.yaml
test/runner/compact_reporter_test.dart
test/runner/configuration/top_level_test.dart
test/runner/pause_after_load_test.dart

Use Stdout.terminalColumns for line length

---

CHANGELOG.md
lib/src/backend/declarer.dart
lib/src/backend/invoker.dart
lib/src/runner/remote_listener.dart
lib/test.dart
pubspec.yaml
test/frontend/add_tear_down_test.dart
test/runner/json_reporter_test.dart

addTearDown() now adds a tearDownAll() rather than adding a plain
tearDown() when called from within setUpAll() (or tearDownAll()). This
is technically a behavioral change, but the old behavior was so
useless I doubt anyone was relying on it.
Closes #712

Make addTearDown() play nice with setUpAll()

---

lib/src/runner/browser/browser_manager.dart
lib/src/runner/configuration/load.dart
lib/src/runner/loader.dart
pubspec.yaml
test/frontend/add_tear_down_test.dart

Context: https://github.com/dart-lang/sdk/issues/29630

Fix fuzzy arrow warnings since they will become errors before too long.

---

CHANGELOG.md
lib/src/runner/remote_listener.dart
pubspec.yaml

In strong mode, a generic type instantiated with dynamic is not a
subtype of all types. You can't pass a List<dynamic> to something
expecting, say, List<int>.
These errors are usually detected statically, and most of those have
been fixed. However, sometimes this becomes a runtime cast, as in:
```dart
main() {
// Store a List<dynamic> in a variable of type dynamic.
dynamic d = [];
// Implicit runtime downcast from dynamic to List<String>.
List<String> s = d;
}
```
In order to ease the migration to strong mode, DDC has been ignoring
these cast failures when they involve certain commonly used types. We
are now in the process of actively fixing those errors.
More context: https://github.com/dart-lang/sdk/issues/27223

Fix a couple of strong mode runtime cast errors.

---

dart_test.yaml
doc/configuration.md

This folds frames from core libraries and packages we don't care
about, but leaves test frames as-is.
Also fix a related documentation error.

Use finer-grained stack trace folding configuration

---

lib/src/runner/hybrid_listener.dart

When https://github.com/dart-lang/sdk/issues/31963 is fixed, the analyzer will become more strict about reporting the `TOP_LEVEL_FUNCTION_LITERAL_BLOCK` hint.  This change will prevent the test package from triggering the hint once it is reported more strictly.

Prepare for fix of https://github.com/dart-lang/sdk/issues/31963

---

lib/src/runner/browser/dartium.dart

As Stream.firstWhere's `defaultValue` parameter is being renamed `orElse`, and this is the only use case in this package, and it's for Dartium, I reckon it will make a few things easier if we just refactor this line to use try/catch instead of `defaultValue`. This file will presumably be deleted after Dart 2.0 final is released.

Don't use Stream.firstWhere(defaultValue:) as it is being renamed

---

lib/src/runner/browser/post_message_channel.dart
pubspec.yaml

The memory leak occurs when window.parent is accessed through
dart:html, so we access it directly through JS interop instead.
Closes #724

Work around dart-lang/sdk#32113

---

CHANGELOG.md
lib/src/runner/browser/chrome.dart
pubspec.yaml

We are seeing issues with the increased SDK size and headless: https://github.com/dart-lang/test/issues/772#issuecomment-367910465
Disabling headless for now to unblock our users. We can add an option in the future.

Remove headless flag

---

CHANGELOG.md
lib/src/runner/node/platform.dart
pubspec.yaml

This wasn't caught by Travis due to our workaround for #599.

Fix a hang when a Node test failed to compile

---

CHANGELOG.md
doc/configuration.md
lib/src/runner/browser/chrome.dart
lib/src/runner/executable_settings.dart
test/runner/configuration/custom_platform_test.dart

Also re-enable headless mode by default.
See #772 for an example of a failure that only occurs in headless
mode.

Allow Chrome's headless mode to be configured

---

CHANGELOG.md
lib/src/runner/browser/dartium.dart
lib/src/runner/remote_listener.dart
pubspec.yaml

- Provide work around for dart-lang/sdk/issues/32556
- Prep for release

Workaround for async SDK issue

---

CHANGELOG.md
lib/src/runner.dart
lib/src/runner/browser/platform.dart
pubspec.yaml

Essentially, this just passes the `--precompiled` directory through to the `Loader` as the `root`, which causes the server to serve that directory directly.
This means no special handlers are set up for the precompiled js, and the precompiled directory is treated as the source of truth, not the root directory (the root dir is not served at all any more). All tests are assumed to be precompiled if the --precompiled flag is passed, and no compilation will ever happen by package:test in that scenario.
I still need to test this with bazel to make sure it still works there as well, and I'm sure I probably broke some package:test tests as well, but sending this out for now to get a first look.

simplify --precompiled to serve the precompiled directory directly 

---

test/runner/browser/runner_test.dart
test/runner/pub_serve_test.dart

Fixes https://github.com/dart-lang/test/issues/800

Stop using document.query in tests – use document.querySelector

---

CHANGELOG.md
lib/src/runner/loader.dart
lib/src/runner/node/platform.dart
test/runner/node/runner_test.dart
test/runner/precompiled_test.dart

Closes https://github.com/dart-lang/test/issues/766
This does also require the root .packages file which build_runner doesn't provide but I will do that next.

Add support for --precompiled node tests

---

.travis.yml
CHANGELOG.md
pubspec.yaml

Usage of 1.23 is almost non-existent
Increase CI velocity on Travis

Require at least Dart 1.24

---

CHANGELOG.md
lib/src/runner/node/platform.dart
pubspec.yaml
test/runner/precompiled_test.dart

This was using the basename of the file before, oops!

fix node tests in subdirs

---

CHANGELOG.md
lib/src/runner/browser/platform.dart

Previously it only included the main js file directly and not the packages/test/dart.js file which does all the load exception handling.

Fix default custom html handler

---

lib/src/runner/configuration/suite.dart
lib/src/runner/plugin/platform_helpers.dart

Fixes for Dart 2 runtime failures that showed up during internal testing.
- type '_InternalLinkedHashMap<Object, SuiteConfiguration>' is not a subtype of type 'Map<BooleanSelector, SuiteConfiguration>'
- type 'Future<dynamic>' is not a subtype of type 'Future<Group>'

Fix for Dart 2 runtime failures

---

CHANGELOG.md
lib/src/frontend/never_called.dart
pubspec.yaml

Closes #824
Makes test/frontend/never_called_test work with --preview-dart-2

Make neverCalled return Null instead of T

---

lib/test.dart
pubspec.yaml

See https://github.com/flutter/flutter-intellij/issues/2055 for the context.

Require meta 1.1.5 and use @isTest and @isTestGroup to mark test() and group().

---

lib/src/frontend/expect.dart

As far as I can tell the comment doesn't make sense -- you don't pay the microtask hit unless you await the future.
Fixes https://github.com/dart-lang/test/issues/830

Use a new future instead of a cached future from another zone

---

test/frontend/matcher/throws_type_test.dart

Fixes #840
Invoke an non-existing method after casting an object to `dynamic` to get
the behavior.

Avoid constructing our own NoSuchMethodError

---

CHANGELOG.md
lib/src/runner/browser/browser_manager.dart
pubspec.yaml

```
type 'WebSocketChannel' is not a subtype of type 'StreamChannel<String>' of 'channel'
```
Cast the `WebSocketChannel` to indicate that all values in each
direction will be `String`.
```
type 'CloseGuaranteeChannel<dynamic>' is not a subtype of type 'VirtualChannel'
```
Avoid using the `suiteChannel` variable for two types. It needs to start
as a `VirtualChannel` which has the `id` field, and then later be a
`StreamChannel`.
```
type 'RunnerSuite' is not a subtype of type 'FutureOr<Future<RunnerSuite>>'
```
Avoid the attempted Future flattenting which was never correct but was
supported in the Dart 1 VM.

More Dart 2 runtime semantic fixes

---

lib/src/runner/compiler_pool.dart
lib/src/util/io.dart

We no longer support an SDK old enough that any of the reference issues
are still a problem.

Drop sanitizeForWindows workaround

---

CHANGELOG.md
lib/src/runner/configuration/reporters.dart
lib/src/util/io.dart
pubspec.yaml

Enable the compact reporter and colors based on `stdout.supportsAnsiEscapes` instead of platform.
Tested in a regular windows command prompt, vscode console on windows, appveyor, and my local windows box. All appear to work as expected.
Fixes https://github.com/dart-lang/test/issues/847.

Change the default reporter logic to use `stdout.supportsAnsiEscapes`

---

lib/src/runner/engine.dart
test/runner/json_reporter_test.dart

More towards https://github.com/dart-lang/test/issues/842
The json reporter produces a different output order when running with Dart 2 due to the new sync-async behavior. Update the tests to account for this behavior while still ensuring the expectations match the documentation. Also remove Furture.sync async sillyness.

Fix reporter tests for Dart 2

---

lib/src/backend/declarer.dart
lib/src/backend/invoker.dart
lib/src/runner/loader.dart
lib/src/runner/plugin/hack_register_platform.dart
lib/src/runner/remote_listener.dart
lib/src/runner/runner_suite.dart
lib/src/utils.dart

The typedef was misused to mean either `Function` or `Function()` in
various places and worked because the difference was not checked. The
doc comment was also incorrect because there were places it was used
where a return value was explicitly necessary. Replace with an inline
function type definition using the appropriate choice for the location.
Where possible also replace with Function types that flow through the
required return types.

Drop AsyncFunction typedef

---

.travis.yml
lib/src/runner/configuration.dart
lib/src/runner/engine.dart
test/runner/compact_reporter_test.dart
test/runner/configuration/top_level_test.dart
test/runner/expanded_reporter_test.dart

More towards https://github.com/dart-lang/test/issues/842
- The SDK has changed the stack traces so look for another identifier on verbose traces
- sync-async is now on by default so add in an additional await to make some tests pass. Why this is necessary should be investigated. Tracking with: https://github.com/dart-lang/test/issues/865

Fixes for latest SDK (dev.61 - default sync-async)

---

lib/src/frontend/retry.dart
lib/src/runner/compiler_pool.dart
lib/test.dart
test/runner/loader_test.dart

More towards https://github.com/dart-lang/test/issues/842
- Export `@Retry` annotation (this is technically broken now but the corresponding tests only fail under preview-dart-2)
- Fix type issue with mapping over dynamic values

More Dart 2 fixes

---

analysis_options.yaml
test/backend/declarer_test.dart
test/backend/invoker_test.dart
test/common.dart
test/frontend/expect_async_test.dart
test/runner/browser/loader_test.dart
test/runner/hybrid_test.dart
test/runner/json_reporter_test.dart
test/runner/load_suite_test.dart
test/runner/loader_test.dart
test/runner/pub_serve_test.dart
test/util/string_literal_iterator_test.dart
test/utils.dart
tool/host.dart

- Fix syntax for upgrading errors in the analysis options
- Ignore todo hints since they are very noisy
- Enable check for implicit casts
- Fix a bunch of implicit casts in the test directory

Enable check for implicit casts

---

README.md
lib/src/executable.dart
lib/src/runner.dart
lib/src/runner/debugger.dart
lib/src/runner/hybrid_listener.dart
lib/src/runner/parse_metadata.dart
lib/src/runner/version.dart
lib/src/runner/vm/platform.dart
lib/src/util/remote_exception.dart
test/backend/declarer_test.dart
test/backend/invoker_test.dart
test/frontend/expect_async_test.dart
test/runner/compact_reporter_test.dart
test/util/one_off_handler_test.dart
test/util/path_handler_test.dart

Searched for lines matching `var \w+;`. This is a much weaker version of
no-implicit-dynamic. This catches a bunch of places where we otherwise
had dynamic calls and tightens up types a bit. Where we are relying on
being able to parse to multiple types and then throw a specific
excpetion or return null on bad types I added an explicit `dynamic`.

Add types to a bunch of uninitalized variables

---

test/runner/browser/loader_test.dart
test/runner/json_reporter_test.dart

We no longer use `mapMap` so the hints aren't printed. Fix the tests to
allow for the "Compiled" message from dart2js. Update the reason for
skipping one test which has an incorrect line number - we will need to
investigate why this line is wrong.
Allow Matcher usage in the `_print` call since the "Compiled" message is
unpredictable.

Re-enable some skipped tests for a stale issue

---

lib/src/runner/plugin/platform_helpers.dart
lib/src/runner/remote_listener.dart
lib/src/runner/runner_test.dart
tool/host.dart

The latest version of `stream_channel` made the type explicit on the
method signature whereas before it was implicit with an `as` cast inside
the method. Most clients wouldn't be impacted is but this package is
because of it's use of `implicit-casts: false`.

Add explicit casts for virtual channel IDs

---

test/runner/hybrid_test.dart

Towards #842
See https://github.com/dart-lang/sdk/issues/33388

Skip hybrid tests against the browser

---

lib/src/runner/browser/browser.dart

This hack was causing tests to be flaky. For example `pub run test` would have failures in `test/runner/browser/chrome_test.dart` but running the test directly resulted in no failures.

Remove Dartium hack

---

CHANGELOG.md
doc/json_reporter.md
json_reporter.schema.json
lib/src/runner/reporter/json.dart
pubspec.yaml
test/runner/json_reporter_test.dart

Fixes #889.
I bumped the protocol version since it's a change, even though it shouldn't be breaking in any way. I moved the expected start event down in the test so I can put the real `pid` in it (so it's tested to be correct, rather than just stripped out) though not sure if there's a better way to do this.
I have some test failures locally that I don't think are related to this (maybe it's Dart2?), but let me know if you disagree and I'll do some more digging:
```
dantup-macbookpro:test dantup$ pub run test
01:12 +365 -1: test/runner/configuration/custom_platform_test.dart: override_platforms can override a browser with a basename-only executable [E]              
Expected: <0>
Actual: <1>
Process `dart bin/test.dart` had an unexpected exit code.
package:test/src/frontend/expect.dart …
```

Add pid to start event; bump protocol version to 0.1.1; package version to 1.1.0

---

lib/src/runner/compiler_pool.dart

We'll stop getting messages like "Option '--enable-checked-mode' is not
needed in Dart 2.0."

Drop --checked arg to dart2js

---

CHANGELOG.md
lib/src/runner/vm/platform.dart
pubspec.yaml
test/runner/precompiled_test.dart

When using the `--precompiled` flag we will now first check for an `<original-test-path>.vm_test.vm.app.dill` file, and if present load that directly in the isolate. Otherwise the `<original-test-path>.vm_test.dart` file will be used.

Add support for loading precompiled kernel files for vm tests

---

test/runner/browser/runner_test.dart
test/runner/node/runner_test.dart

- Update expecation now that dart2js produces different color output.
- Skip tests against a graceful fallback for invalid code that can no
longer parse.

Fix tests against the latest SDK

---

CHANGELOG.md
lib/html_config.dart
lib/html_enhanced_config.dart
lib/src/matcher/core_matchers.dart
lib/vm_config.dart
pubspec.yaml
test/core_matchers_test.dart

We still have a lot of tests in the SDK repository using `unittest`.
We need either a version of `unittest` that will run when we remove the old-style constants, or to disable all those tests (rewriting is an option, just an expensive one).

Fix constants on legacy `unittest` branch.

---

test/runner/runner_test.dart

Update expectations around stack traces that changed with the latest SDK.
Closes https://github.com/dart-lang/test/issues/909

Fix failing tests due to SDK release

---

lib/src/runner/compiler_pool.dart
pubspec.yaml

Decoding input bytes by doing `.map(utf8.decode)` assumes that input byte chunks are split at encoded code-unit boundaries.
It's safer to use `.transform(utf8.decoder)` which allows encodings to be split accross input chunks.
Also changed `.listen(f).asFuture()` to the equivalent `.forEach(f)`.

Strengthen UTF-8 decoding.

---

CHANGELOG.md
lib/src/runner/parse_metadata.dart
pubspec.yaml
test/runner/parse_metadata_test.dart
test/runner/runner_test.dart

Towards #915
The CFE will already reject this code if it is incorrect, we don't need
to also check for syntax errors.
- Remove the explict checks for `const`
- Remove the explicit checks for using valid constructor names and
argument types.
- Update test to remove most of the `const` in examples. Retain const
constructor calls since we can't yet parse the resulting expression if
it is omitted.
- Remove tests for the removed explicit checks.

Remove explicit checks for syntax errors

---

lib/src/runner/parse_metadata.dart
test/runner/parse_metadata_test.dart

- Use `??`, `??=`, and `?.` instead of `== null`.
- Use consistent single quotes

Fix some style nits in parse_metadata and test

---

CHANGELOG.md
lib/src/runner/reporter/json.dart

This should fix #918 (I've run the test on Windows and macOS and it passed on both; before this fix it failed on Windows). I believe calling `.path` on a `Uru` is not safe for file URIs, since it'll return a path in a URI format.
(~~this may mean the tests aren't running on any Windows bots~~ Looks like tests run on Travis but no Windows - I don't know if it'd be tricky to set up?)

Fix root_url/root_line/root_column for Windows

---

CHANGELOG.md
pubspec.yaml

This is necessary to allow packages that depend on test to pull in the latest version of analyzer, which includes support for the 2.1 features.

Prepare to publish version 1.3.2

---

CHANGELOG.md
lib/src/runner/parse_metadata.dart
test/runner/parse_metadata_test.dart

Fixes #915
When there is no `const` the expression is parsed as a
`MethodInvocation` instead of an `InstanceCreationExpression`. Update
all the places we were casting to the latter so that it can handle
either case.
Add some additional tests for import prefix cases.

Allow omitting const in parsed metadata

---

CHANGELOG.md
lib/src/backend/declarer.dart
lib/src/backend/invoker.dart
lib/src/runner/load_suite.dart
lib/src/util/io_stub.dart
lib/src/util/test.dart
lib/src/utils.dart
lib/test.dart
pubspec.yaml

Adds conditional imports and moves some code around to eliminate non-conditional imports of `dart:io` from `test.dart`.

Remove imports of `dart:io` from `test.dart` unless its available

---

analysis_options.yaml
test/runner/browser/chrome_test.dart
test/runner/browser/firefox_test.dart
test/runner/browser/internet_explorer_test.dart
test/runner/browser/loader_test.dart
test/runner/browser/phantom_js_test.dart
test/runner/browser/safari_test.dart
test/runner/node/runner_test.dart
test/runner/pub_serve_test.dart

Clean up a few violations that weren't corrected by dartfmt --fix.
Dartfmt would eventually fix these but a new version of the tool needs
to be published.

Add unnecessary new/const lints

---

test/runner/runner_test.dart
test/utils.dart

- Remove APIs that are no longer used.
- Switch to `TypeMatcher` instead of manual implementation for exception
matchers.
- Drop `isDart2` since we only run in Dart 2 mode everywhere.

Clean up test utils

---

pkgs/test_core/pubspec.yaml

I should really pay more attention before opening PRs...

Let test_core depend on latest test_api

---

pkgs/test/pubspec.yaml
pkgs/test/test/util/string_literal_iterator_test.dart
pkgs/test_core/pubspec.yaml

The breaking changes between analyzer 0.33.x and 0.34.x do not affect
test or test_core.

Allow use of analyzer version 0.34.x.

---

pkgs/test/README.md
pkgs/test/doc/architecture.md
pkgs/test/doc/configuration.md

Many of the dartdocs.org links were broken, redirecting incorrectly to bad pub.dartlang.org/documentation URIs.
Additionally, shorten many links to use [shortcut reference links](https://spec.commonmark.org/0.28/#shortcut-reference-link), where the reference ID was very similar to the link text. This makes the text more legible in its source format.

Fix DartDocs links

---

pkgs/test/test/runner/configuration/custom_platform_test.dart
pkgs/test_api/lib/src/util/remote_exception.dart
pkgs/test_api/test/backend/declarer_test.dart

In version `1.5.0` of `source_span` the output for multi-line spans was
updated to output the content and highlight a section with lines on the
left instead of the old `^^^^^` format. Update the expectations
accordingly to expect that a bit of the multi-line content is printed.

Fix travis - analyzer and source_span updates

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Prepare to release a new version of `test_api`, `test_core` and `test`.

Prep for release

---

pkgs/test_core/lib/src/runner/parse_metadata.dart
pkgs/test_core/pubspec.yaml

I will separetly look in to the migration, this is to get travis
unblocked for other commits.

Ignore a new deprecation from analyzer package

---

pkgs/test/test/runner/hybrid_test.dart

The linked SDK issue is resolved.

Re-enable tests for spawnHybridUri

---

pkgs/test/test/runner/hybrid_test.dart
pkgs/test_api/lib/src/util/remote_exception.dart

We have removed most of the special handling around
`IsolateSpawnException` so it shouldn't matter if the exposed exception
implements that interface. On the web, for the `spawnHybridUri` or
`spawnHybridCode` case the web code shouldn't be able to see the type to
test for it anyway.

Don't deserialize to IsolateSpawnException

---

pkgs/test/test/runner/parse_metadata_test.dart
pkgs/test_core/lib/src/runner/parse_metadata.dart

Gives an actionable error in a case where we'd otherwise get a stack
trace.

Disallow non-literal strings in annotations

---

pkgs/test_core/lib/src/runner/parse_metadata.dart
pkgs/test_core/pubspec.yaml

As part of implementing the "UI as code" feature
(https://github.com/dart-lang/language/blob/master/accepted/future-releases/unified-collections/feature-specification.md)
the analyzer is deprecating the following classes and methods:
- ForStatement and ForEachStatement (ForStatement2 is now used for
both kinds of loops)
- ListLiteral.elements (use elements2, which has a more general return
type)
- AstVisitor.visitForEachStatement and AstVisitor.visitForStatement
(visitForStatement2 is now used for both kinds of loops)
- AstVisitor.visitMapLiteral and AstVisitor.visitSetLiteral
(visitSetOrMapLiteral is now used for both kinds of literals).
See deprecation CL: https://dart-review.googlesource.com/c/sdk/+/95665/

Prep for analyzer changes to support the "UI as code" feature.

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/bootstrap/vm.dart
pkgs/test_core/lib/src/runner/hybrid_listener.dart
pkgs/test_core/lib/src/runner/spawn_hybrid.dart
pkgs/test_core/lib/src/runner/vm/platform.dart
pkgs/test_core/pubspec.yaml

Version `1.7.0` adds the import so it's the minimum version required.
Allow versions through `2.x` since the breaking change will be to change
the import which will now be satisfied.

Update imports to allow stream_channel 2.0.0

---

pkgs/test/pubspec.yaml
pkgs/test_api/pubspec.yaml
pkgs/test_core/pubspec.yaml

- Don't surround versions with quotes unless they have a space.
- Remove the unnecessary lower bound for packages where the current
lower bound is not resolvable due to SDK constraints.
- Change single quotes to double quotes since they are preferred in
yaml.
- Remove version constraints from `test_api` to `test` and `test_core`
since we will always have path overrides to those packages.

Tweak pubspec constraint styles

---

pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/backend.dart
pkgs/test_api/lib/test_api.dart
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/backend.dart
pkgs/test_core/lib/src/runner/parse_metadata.dart
pkgs/test_core/lib/test_core.dart
pkgs/test_core/pubspec.yaml

Towards https://github.com/dart-lang/build/issues/1554 (makes that a trivial change in build_test)

expose the parseMetadata function and all required classes to use it

---

.travis.yml
mono_repo.yaml
pkgs/test/test/runner/runner_test.dart

We have had flakes on travis because this environment does not appear to be taking effect. This is probably because it's being overridden by the individual environments in each job.

Make the FORCE_TEST_EXIT env global

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/engine_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/engine.dart
pkgs/test_core/lib/src/runner/reporter/compact.dart
pkgs/test_core/lib/src/runner/reporter/expanded.dart
pkgs/test_core/pubspec.yaml

- Update engine to consider non-completed tests as a failure run
- Update `compact` and `expanded` reporters to list the non-completed tests
- Add corresponding test
- Rev version numbers
Closes https://github.com/dart-lang/test/issues/1003

Non-completed tests should cause failures

---

pkgs/test/CHANGELOG.md
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/frontend/expect_async.dart
pkgs/test_api/test/frontend/expect_async_test.dart

Allows using `expectAsync*` to wrap callbacks in context where they are
called with a `try/catch` without changing visible behavior.

Don't reroute exceptions thrown in expectAsync

---

pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/live_test_controller.dart

In some environments the state change events and the "test complete" event are sent over a stream that does not guarantee ordering (e.g. as independent HTTP requests when using package:sse).
Without this change, such tests will fail intermittently, when the "test complete" event happens to be delivered before the state change event.

Ensure that the test state transitions to complete before the test is considered complete.

---

pkgs/test_core/lib/src/runner/parse_metadata.dart
pkgs/test_core/pubspec.yaml

Since analyzer version 0.36.0, we no longer need to use elements2.
elements is equivalent.

Stop using deprecated analyzer API left over from "UI as code" migration.

---

pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/utils.dart
pkgs/test_api/pubspec.yaml

A recent change to the Dart SDK updated `HttpClientResponse`
to implement `Stream<Uint8List>` rather than implementing
`Stream<List<int>>`.
This forwards-compatible change updates calls to
`Stream.transform(StreamTransformer)` to instead call the
functionally equivalent `StreamTransformer.bind(Stream)`
API, which puts the stream in a covariant position and
thus causes the SDK change to be non-breaking.
https://github.com/dart-lang/sdk/issues/36900

Prepare for Uint8List SDK breaking change

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/vm/environment.dart
pkgs/test_core/lib/src/runner/vm/platform.dart
pkgs/test_core/pubspec.yaml

pkg:vm_service_lib is discontinued
Related to https://github.com/dart-lang/vm_service_drivers/issues/257

test_core: migrate to pkg:vm_service

---

pkgs/test/CHANGELOG.md
pkgs/test/README.md
pkgs/test/lib/src/runner/node/platform.dart
pkgs/test/pubspec.yaml

The old flag, `--categories=Server`, is deprecated and emits a warning
when used. The new flag is supported since at least 2.1.1
Since our pubspec already limits us to at least 2.2.0, remove the SDK
version check for using the flag.

Use supported --server-mode flag for dart2js

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/pub_serve_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/util/io.dart
pkgs/test_core/pubspec.yaml

This had been used to detect feature support so that the package could
have a wider SDK constraint and have enhanced features for newer SDKs.
Drop the dependency and code checking the SDK version because:
- We now typically bump the SDK constraint rather than support multiple
code paths.
- The remaining usage was for checking for DDC support in `pub serve`
which doesn't exist anymore - we haven't yet deleted the tests or
migrated them to use `build_runner serve`. This test and references to
the old approach with both compilers is retained to make it clear what
should be tested when we get around to migrating it.

Drop dependency on pub_semver

---

pkgs/test/lib/src/runner/node/platform.dart

This was added in https://github.com/dart-lang/test/pull/729 when the
`Socket` class was missing a method in an interface it declared it had -
this caused a problem when some code tried to tear if off.
According to https://github.com/dart-lang/sdk/issues/31504 that method
now exists and can be torn off - calling that method would still throw,
but that would also be true with a `DelegatignStreamSink` wrapper.

Remove unnecessary DelegatingStreamSink wrapping

---

pkgs/test/test/runner/runner_test.dart

The latest SDK must optimize away some of these no op futures. Change the structure of the async error test to better validate the chain logic.

Fix chain tests

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/live_test_controller.dart
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Externally there is no race condition as event order is guaranteed as we are using a websocket for the remote connection. Internally we make use of `package:sse`. As of  https://github.com/dart-lang/sse/pull/11 order is also guaranteed.

Remove state change race condition logic

---

pkgs/test/CHANGELOG.md
pkgs/test/doc/json_reporter.md
pkgs/test/lib/src/runner/browser/platform.dart
pkgs/test/pubspec.yaml
pkgs/test/test/runner/configuration/configuration_test.dart
pkgs/test/test/runner/runner_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner.dart
pkgs/test_core/lib/src/runner/configuration.dart
pkgs/test_core/lib/src/runner/configuration/args.dart
pkgs/test_core/lib/src/runner/reporter/json.dart
pkgs/test_core/lib/src/runner/vm/platform.dart
pkgs/test_core/pubspec.yaml

Move debug functionality to a --debug flag

---

.travis.yml
pkgs/test/CHANGELOG.md
pkgs/test/README.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/coverage_test.dart
pkgs/test/test/runner/runner_test.dart
pkgs/test/test/utils.dart
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner.dart
pkgs/test_core/lib/src/runner/configuration.dart
pkgs/test_core/lib/src/runner/configuration/args.dart
pkgs/test_core/lib/src/runner/engine.dart
pkgs/test_core/pubspec.yaml

Open to feedback on this. Here's how it works at the moment:
There's a new `--coverage` option that you can use to specify the output directory for your coverage. It will create a new output directory if one doesn't already exist.
The tests are run through the engine, and then get spit out to a coverage helper function. That coverage helper function:
**A)** Checks if it's a VM suite
**B)** Gathers coverage if it is
**C)** Outputs coverage to `${suite path}.vm.json`
So, for example, when I run:
```bash
pub run test --coverage hello_world test/vm/simple_repo_test.dart
```
A new file gets added at `hello_world/test/vm/simple_repo_test.dart.vm.json` with the coverage results!

Implement VM coverage gathering

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/coverage.dart
pkgs/test_core/lib/src/runner/coverage_stub.dart
pkgs/test_core/lib/src/runner/engine.dart
pkgs/test_core/pubspec.yaml

Closes https://github.com/dart-lang/test/issues/1090

Conditionally import coverage logic

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/solo_test.dart
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/declarer.dart
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

While using solo, mark non-solo tests as "skipped". This improves the reporting of these skipped tests.

Mark non-solo tests as "skipped"

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/configuration/reporters.dart
pkgs/test_core/lib/src/runner/reporter/compact.dart
pkgs/test_core/lib/src/runner/reporter/expanded.dart
pkgs/test_core/lib/src/runner/reporter/json.dart
pkgs/test_core/lib/src/util/print_sink.dart
pkgs/test_core/lib/test_core.dart

Towards #1100
The ExpandedReporter needs to work on the web platform. It worked before
because it only used `print` which works everywhere.
- Change the argument to `StringSink` which can be supported on every
platform.
- Remove the `dart:io` import from the expanded reporter.
- Make the `sink` argument non-optional for the expanded reporter.
- Add a `PrintSink` implementation that buffers writes until the content
ends with a newline and then calls `print`.

Switch from IOSink to StringSink

---

pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/invoker.dart
pkgs/test_api/pubspec.yaml

If a test times out at the default timeout, point to the docs for
changing timeouts in the error message.

Add a link to docs on changing timeout

---

pkgs/test_core/lib/src/runner/console.dart
pkgs/test_core/lib/src/runner/load_suite.dart
pkgs/test_core/lib/src/runner/runner_test.dart

This has the same intended purpose as `unawaited` so it can be easily
replaced. Technically even the `unawaited` is not necessary here since
none of the surrounding functions are `async`, but it is fine to use it
for documentation purposed.
Leave the utility in place for now since it will take some version bump
gymnastics to roll out.

Remove uses of "invoke" utility

---

pkgs/test/test/runner/test_chain_test.dart

With the split of `test` to `test_core` and `test_api` this test was incorrectly passing. This issue was only highlighted with the latest SDK change. Update the expectation which closes https://github.com/dart-lang/test/issues/1120

Fix test_chain_test at head

---

pkgs/test_api/lib/src/backend/metadata.dart
pkgs/test_core/lib/src/runner.dart
pkgs/test_core/lib/src/runner/loader.dart
pkgs/test_core/lib/src/runner/suite.dart

Prepare for a potential breaking change in `package:boolean_selector`.
Currently the `evaluate` method takes an argument which is either an
`Iterable<String>` or a `bool Function(String)` which matches the
`.toSet()contains` tearoff on that Iterable. We might tighten that to
always take a `bool Function(String)` since the tearoff is easy to
handle at the calling side.

Always pass a function to BooleanSelector.evaluate

---

pkgs/test/CHANGELOG.md
pkgs/test/README.md
pkgs/test/doc/configuration.md
pkgs/test/lib/src/runner/browser/platform.dart
pkgs/test/lib/src/runner/browser/static/default.html.tpl
pkgs/test/pubspec.yaml
pkgs/test/test/runner/browser/runner_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/configuration.dart
pkgs/test_core/lib/src/runner/configuration/load.dart

This allows for reusing one template file across all tests in use cases
where external scripts or html elements are required for all tests. The
possibility to still use local html files per test file is retained.
Fixes https://github.com/dart-lang/test/issues/39

Add custom-html-template-path config option

---

pkgs/test/CHANGELOG.md

We never published `1.9.5` so don't need any entry for it. The changes
don't need to be mentioned since they aren't the only thing and they
aren't user facing.

Drop changelog for unpublished version

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/compact_reporter_test.dart
pkgs/test/test/runner/expanded_reporter_test.dart

The stack trace changed in `1.24` and the tests were updated to allow
either format. Since we don't support that SDK anymore we can simplify
back to the single format that will be used.

Drop support for old stack trace format

---

pkgs/test/lib/src/executable.dart
pkgs/test/test/runner/json_reporter_test.dart
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/frontend/spawn_hybrid.dart
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/executable.dart
pkgs/test_core/lib/src/util/dart.dart
pkgs/test_core/lib/src/util/io.dart
pkgs/test_core/lib/test_core.dart
pkgs/test_core/pubspec.yaml

Remove TODO comments waiting for things that will never change or that
we don't intend to take action on.
- https://github.com/dart-lang/sdk/issues/22977 is closed as not
planned.
- Dart 2 does not support importing `dart:io` in cross platform code.
- Setting the exit code is not supported on web.
- We plan on keeping `executable.dart` under lib to allow reuse from
other packages internally.
- We don't plan on trying to support `spawnHybridUri` outside of the
test runner.
- `executable.main` is now declared to return a `Future`.
- We don't intend to take a dependency on `json_schema`.

Remove stale or inactionable TODO comments

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

- Bump to feature version change in `test`.
- Drop `-dev` from pubspecs.
- Pin to latest `test_core` from `test`.

Prepare to publish test_core and test

---

pkgs/test/pubspec.yaml
pkgs/test_api/pubspec.yaml
pkgs/test_core/pubspec.yaml

The field is no longer used by pub and triggers a warning on publish.

Drop author from pubspecs

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/platform_selector.dart
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Towards #1141
Work around the bug in the SDK by switching back to `..addAll`. After we
publish this version that works we can bump the min SDK.
Prepare to publish.

Avoid for-loop elements at the top level

---

.travis.yml
pkgs/test/CHANGELOG.md
pkgs/test/mono_pkg.yaml
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/platform_selector.dart
pkgs/test_api/mono_pkg.yaml
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/mono_pkg.yaml
pkgs/test_core/pubspec.yaml

Close #1141
Bump min SDK in all packages for safety. Restore use of for-loop
elements in a top level variable since they work in this SDK.

Bump min SDK to 2.4.0 for bug in for-loop elements

---

pkgs/test_api/lib/src/utils.dart

Usages were removed in https://github.com/dart-lang/test/pull/1119
Since there have since been version constraint bumps it is now safe to
remove entirely.

Drop invoke utility

---

pkgs/test/README.md
pkgs/test/test/runner/configuration/suite_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/configuration/args.dart
pkgs/test_core/lib/src/runner/engine.dart
pkgs/test_core/lib/src/runner/suite.dart

Added a differentiation between not defining the seed and it being 0 as a result of the randomization.
Before `Random.nextint(...)` could choose 0 as a seed, which wouldn't be printed even though it is a result of randomization (could be irritating). Moreover, when accessing the `SuiteConfiguration` there was no way of distinguishing whether the seed was chosen to be 0, randomized to 0 or not passed at all. Now it will be null if it has not been passed.
The current shuffling behaviour will not be affected with this change, just how we output the seed.
Also following the discussion here: https://github.com/dart-lang/test/issues/1124#issuecomment-566665995 I added a note to the README :)

Differentiate between test-randomize-ordering-seed=0 and null.

---

pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/coverage.dart
pkgs/test_core/lib/src/runner/coverage_stub.dart
pkgs/test_core/lib/src/runner/engine.dart
pkgs/test_core/lib/src/runner/load_suite.dart
pkgs/test_core/lib/src/runner/plugin/platform_helpers.dart
pkgs/test_core/lib/src/runner/runner_suite.dart
pkgs/test_core/lib/src/runner/vm/platform.dart
pkgs/test_core/pubspec.yaml

Towards https://github.com/dart-lang/test/issues/36
Update `deserializeSuite` to take an optional callback for coverage collection. Note that each platform e.g. VM, Browser etc. makes use of this helper. This sets the foundation for per platform custom coverage collection logic.

Flexible Coverage API

---

pkgs/test/CHANGELOG.md
pkgs/test/test/runner/loader_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/loader.dart

Partial resolution for https://github.com/dart-lang/test/issues/1159.
Retries loading test suites (in loader.dart). Retry configuration is currently based on the suite metadata - and is counted separately from the test retries (does not count as a retry for tests).
Should we configure this separately from normal test retries? It might be reasonable to do retries for loading errors by default for instance (as they are likely transient and caused by test infrastructure). Also you might want to be able to opt into retrying load errors but not test failures.
Note that I also added an artificial delay of 1 second between retries. This seems reasonable to allow for any external factors that might be causing the load error to work themselves out. We might want to also make that configurable or …

Allow retry load suites

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/hybrid_listener.dart

Closes #1007
Closes #1008
We already forward errors across the `StreamChannel` so it isn't
particularly useful to also have them printed to the output on the VM
hosting the runner.
We know that `listen` is only ever called in an Isolate that was spawned
from the runner and the `zone` is the root zone. The uncaught error
handler on the root zone will print the error and then kill the isolate,
we jump straight to killing the isolate instead. This Isolate is only
ever spawned without an `onError` handler that would override the
default.

Avoid unhandled errors in spawnHybridUri

---

pkgs/test/README.md
pkgs/test_api/lib/src/frontend/stream_matcher.dart

Closes #1015
Our recommendation is that code which wants to `await` the result of an
expectation should use `expectLater`. Update the docs and README to
reflect this.

Fix some documentation to use expectLater

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/vm/platform.dart
pkgs/test_core/lib/src/util/dart.dart
pkgs/test_core/pubspec.yaml

The `resolver` argument was only used from external packages which can
be migrated off this utility.
The `checked` argument was only used to allow `spawnHybrid` APIs to run
code without asserts, but we want all test code to run with asserts,
including server side utilities.

Remove arguments to runInIsolate utility

---

pkgs/test/test/runner/engine_test.dart
pkgs/test_core/lib/src/runner/engine.dart

Closes #865
The tests no longer fail without this.

Remove an unnecessary await on event loop

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/platform.dart
pkgs/test/lib/src/runner/node/platform.dart
pkgs/test/pubspec.yaml
pkgs/test/test/runner/browser/runner_test.dart
pkgs/test/test/runner/node/runner_test.dart
pkgs/test/test/runner/pub_serve_test.dart

These were disabled because non-hermetic URIs were present. They have
been replaced with `org-dartlang-sdk` URIs. Update the SDK URI base so
that the replacement works for these URIs.
The tests in `pub_serve_test.dart` are still skipped for other reasons
so we can't guarantee they are fixed correctly here. Once we unskip
those tests we wouldn't want to hide issues with the stack trace
mapping, so we'll remove that reason for the skip.

Fix stack trace mapping for SDK locations

---

pkgs/test/test/runner/runner_test.dart
pkgs/test_core/lib/src/runner/configuration/args.dart

We changed the behavior to allow passing an explicit `0` and treating
that differently from omitting the argument in #1150

Fix usage string for test-randomize-ordering-seed

---

pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/frontend/stream_matcher.dart
pkgs/test_api/pubspec.yaml
pkgs/test_api/test/frontend/stream_matcher_test.dart

Fixes https://github.com/dart-lang/test/issues/1183
Ran through an internal presubmit and everything came back green so this should be safe.

Cancel any StreamQueue that is created as a part of a stream matcher

---

pkgs/test_api/lib/src/backend/declarer.dart
pkgs/test_api/lib/src/remote_listener.dart

The doc comment explicitly mentions returning a value so the `void`
return is not sensible. Avoids strangeness of needing to add an extra
`as dynamic` to allow an `await`.
Remove a TODO - the `await` is important since the `main` could be
async.

Make Declarer.declare generic

---

pkgs/test/test/runner/timeout_test.dart
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/invoker.dart

Fixes #1188
A test is marked completed as soon as it fails. If a `tearDown` callback
also take too long, or never completes, we ignore the timeout and never
move on to more tests.

Allow a timeout following a completed test

---

.travis.yml
pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/platform.dart
pkgs/test/lib/src/runner/node/platform.dart
pkgs/test/lib/src/util/package_map.dart
pkgs/test/mono_pkg.yaml
pkgs/test/pubspec.yaml
pkgs/test/test/io.dart
pkgs/test/test/runner/precompiled_test.dart
pkgs/test_api/mono_pkg.yaml
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/compiler_pool.dart
pkgs/test_core/lib/src/util/stack_trace_mapper.dart
pkgs/test_core/mono_pkg.yaml
pkgs/test_core/pubspec.yaml

Towards https://github.com/dart-lang/test/issues/1177.
This relies on the new source_map_stack_trace here https://github.com/dart-lang/source_map_stack_trace/pull/11 which no longer requires you to pass a `PackageResolver`.
It also relies on the upcoming package_config 1.9.0.
Once package_config is published and this goes green I will merge and publish source_map_stack_trace, and then we can remove the git override here.

Drop package resolver from test_core and test, use package_config from test

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/util/string_literal_iterator.dart
pkgs/test_core/pubspec.yaml

In `2.8.0-dev.15.0` the `Iterator.current` returns `-1` instead of
`null` when there is no value. A better fix would be to avoid reading
`_runes.current` if the last `moveNext` returned `false`, but this would
be a larger refactoring.

Fix rune iteration

---

pkgs/test_api/lib/test_api.dart

Must be non-null for `handleUncaughtError`.

Add defaulting for StackTrace

---

pkgs/test/README.md

Make it clear that a timeout does not prevent long running tests.

Expand documentation on timeouts

---

pkgs/test_api/lib/src/frontend/expect.dart

Fixes a static error:
```
pkgs/test_api/lib/src/frontend/expect.dart:82:8: Error: A non-null value must be returned since the return type 'Future<dynamic>' doesn't allow null.
- 'Future' is from 'dart:async'.
Future _expect(actual, matcher,
```
The CFE does not appear to support `@alwaysThrows`, but a return type of
`Never` is the correct way to express this with null safety.

Use Never return type for function which throws

---

pkgs/test/README.md

Add an example of testing an exception to clarify the need for lazy evaluation of supplied tests.

Add exception testing example

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/util/io.dart
pkgs/test_core/pubspec.yaml

The previous code was working around the possibility of getting a `null`
OS, that that is never returned. Instead `OperatingSystem.none` is used.
Since we can't hit the null branch and exception, the entire initializer
can simplify to the static method call. This will be more clearly
correct after the null safety migration.

Simplify currentOS initialization

---

pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/frontend/future_matchers.dart
pkgs/test_api/pubspec.yaml

Closes #1224
Remove the last sentence which references `AsyncMatcher` by name since
that is an implementation detail, and the reference to `expect` was
confusing and contradicted the paragraph above.
Rephrase the paragraph about asynchronous matching to reference both
`expect` and `expectLater`. Expand on "the actual expectation" by
referencing the `matcher` argument explicitly.

Improve docs for async matchers

---

pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/invoker.dart
pkgs/test_api/lib/src/backend/live_test_controller.dart
pkgs/test_core/lib/src/runner/engine.dart
pkgs/test_core/lib/src/runner/runner_test.dart
pkgs/test_core/pubspec.yaml

The `_LiveTest` was already a very thin wrapper around
`LiveTestController` which exposed some of it's private members.
Instead, make `LiveTestController` implement `LiveTest` directly and
skip the extra level of classes that have cyclical references.
This is a small refactoring to make it easier to understand structure
and dependencies for future changes.

Merge _LiveTest into LiveTestController

---

pkgs/test/pubspec.yaml

- rev the dep on package: webkit_inspection_protocol (widen the supported range to `0.7.0`)
- fix https://github.com/dart-lang/test/issues/1235
Test pass locally and the project analyzes cleanly (w/ 0.5.0, 0.6.0, and 0.7.0).

rev the dep on package: webkit_inspection_protocol

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/platform.dart
pkgs/test/lib/src/runner/node/platform.dart
pkgs/test/pubspec.yaml
pkgs/test/test/io.dart
pkgs/test/test/runner/runner_test.dart
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/metadata.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/parse_metadata.dart
pkgs/test_core/lib/src/runner/vm/platform.dart
pkgs/test_core/lib/src/util/io.dart
pkgs/test_core/pubspec.yaml

- Adds a nullable `languageVersionComment` field to `Metadata`
- Adds a utility to get a language comment that matches the root packages version
- Adds explicit language version comments to all bootstrap files ensuring the versions matches that of the test (note this assumes tests live in the root package)
- Clean up the handling of serving bootstrap dart files in the browser platform which had diverged and was serving the wrong content.
Closes https://github.com/dart-lang/test/issues/1236
I am not sure of the proper way to test this exactly, suggestions welcome. I manually tested the vm stuff and it seems to work correctly in terms of opting in/out of strong mode.

Add language version comments to bootstrap files

---

pkgs/test_core/lib/src/runner/compiler_pool.dart

This starts getting web tests compiling through the test runner, if used in combination with https://github.com/dart-lang/test/pull/1240.
However I see some late initialization errors that need to be tracked down still, can follow up with that later.

Pass experiment flags to dart2js

---

pkgs/test/lib/src/runner/browser/platform.dart
pkgs/test/lib/src/runner/node/platform.dart
pkgs/test/pubspec.yaml
pkgs/test_api/pubspec.yaml
pkgs/test_core/lib/src/runner/package_version.dart
pkgs/test_core/lib/src/runner/vm/platform.dart
pkgs/test_core/lib/src/util/io.dart
pkgs/test_core/pubspec.yaml

This also adds more dependency overrides so the entire test isolate is migrated.
After this change, `DART_VM_OPTIONS="--enable-experiment=non-nullable" pub run test <some-test>` can pass even with null safety enabled 🎉 .
cc @kevmoo 
We do get these two warnings which I don't understand:
```
../test_core/lib/src/runner/parse_metadata.dart:56:43: Warning: Operand of null-aware operation '?.' has type 'LanguageVersionToken' which excludes null.
- 'LanguageVersionToken' is from 'package:_fe_analyzer_shared/src/scanner/token.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-3.0.0/lib/src/scanner/token.dart').
_languageVersionComment = result.unit.languageVersionToken?.value();
^
../test_core/lib/src/runner/parse_metadata.dart:63:30: Warning: Operand of null-aware …
```

Move package config dep to its own library

---

pkgs/test_core/lib/backend.dart
pkgs/test_core/lib/src/runner/package_version.dart
pkgs/test_core/lib/src/runner/parse_metadata.dart

Inference from legacy types defaults to the non-nullable type.  Add explicit types on the LHS to make these be non-nullable as they actually are.
Note that explicit casts on the RHS currently trip up the unnecessary cast lint, which I will file a separate issue about.

add explicit types on the lhs to override inference

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/reporter/json.dart
pkgs/test_core/pubspec.yaml

See https://github.com/flutter/flutter/issues/56457
If we get a null `runnerSuite` the attempt to read the `environment`
file will fail, resulting in a confusing error and stack trace. We can't
reproduce this locally so it isn't clear where the null may be coming
from.
Add additional information to the error thrown to try to narrow down the
places we need to search for a root cause.

Fail with specific error for null runnerSuite

---

pkgs/test/pubspec.yaml

This was missed when I bumped the dependency on `test_core` which
requires a new `test_api`. Solves an impossible pub get.

Bump test_api dep from test

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/backend.dart
pkgs/test_core/lib/src/runner/configuration.dart
pkgs/test_core/lib/src/runner/configuration/load.dart
pkgs/test_core/pubspec.yaml

* Expose the `Configuration` class and related classes.
* Expose the `load` and `loadFromString` methods for loading a `Configuration`
from yaml.
Towards https://github.com/dart-lang/build/issues/2684

expose the ability to load test configuration files from the test_core package

---

pkgs/test/lib/src/runner/browser/post_message_channel.dart
pkgs/test/pubspec.yaml
pkgs/test_api/lib/src/remote_listener.dart
pkgs/test_api/pubspec.yaml
pkgs/test_core/lib/src/bootstrap/vm.dart
pkgs/test_core/lib/src/runner/plugin/remote_platform_helpers.dart
pkgs/test_core/lib/src/runner/runner_suite.dart
pkgs/test_core/lib/src/runner/vm/platform.dart
pkgs/test_core/pubspec.yaml

- update pinned package deps for browser tests
- change serializeSuite return type to `StreamChannel<Object?>` since browser tests seem to send nulls here.
- migrate some `dynamic` things to `Object?`

start working on browser test bootstrap fixes

---

pkgs/test/test/runner/hybrid_test.dart
pkgs/test_core/lib/src/runner/hybrid_listener.dart

`Null` is no longer the base type so this type check was no longer valid.

Fix some hybrid_tests.dart

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/platform.dart
pkgs/test/lib/src/runner/node/platform.dart
pkgs/test/pubspec.yaml
pkgs/test/test/io.dart
pkgs/test/test/runner/runner_test.dart
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/metadata.dart
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/parse_metadata.dart
pkgs/test_core/lib/src/runner/vm/platform.dart
pkgs/test_core/lib/src/util/io.dart
pkgs/test_core/pubspec.yaml

Fixes https://github.com/dart-lang/test/issues/1255
Backport of the null_safety commit to support this https://github.com/dart-lang/test/commit/5312b230d7100bc7bdbf98b2b9ad500177f74185
- Adds an optional `languageVersionComment` field to `Metadata`
- Adds a utility to get a language comment that matches the root packages version
- Adds explicit language version comments to all bootstrap files ensuring the versions matches that of the test (note this assumes tests live in the root package)
- Clean up the handling of serving bootstrap dart files in the browser platform which had diverged and was serving the wrong content.

Add language version comments to bootstrap files (#1240)

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/node/platform.dart
pkgs/test/pubspec.yaml

Closes #1264
Listening on both IPv6 and IPv4 allows for the case where `node` only
supports IPv4 but the OS supports IPv6, however this is not a situation
that should come up in the real world.
Bind to IPv6 and fall back to IPv4 if it doesn't work. The node side
calls `net.connect(port)` which should support either assuming OS
support.

Remove dependency on `http_multi_socket`.

---

pkgs/test_api/lib/src/backend/declarer.dart
pkgs/test_api/lib/src/backend/invoker.dart

There are two guarantees in play around outstanding callbacks:
-  `tearDown` callbacks are not called until after outstanding callbacks
from the test body are complete.
-  The overall test is not considered complete until after outstanding
callbacks from `tearDown` callbacks are also complete.
Previously these two guarantees were split in two locations. In
`Declarer` the setups and test body are wrapped with
`Invoker.waitForOutstandingCallbacks` to handle the first guarantee. In
`Invoker` a _separate_ outstanding callbacks counter wraps the zone
where the setups and test body are run, and it only counts the
callbacks from the teardown callbacks. It is immediately awaited after
spawning the future that runs the entire case - setups, test body, and
teardowns.
Now the two guarantees are …

Use a more consistent wait-for-callbacks pattern

---

pkgs/test_api/lib/src/remote_listener.dart

The linked issue is closed as fixed.

Remove a workaround for an old SDK bug

---

pkgs/test_api/lib/src/backend/invoker.dart

The error behavior described in the comment was removed in #643.

Rewrite a misleading comment

---

pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_api/test/backend/declarer_test.dart
pkgs/test_api/test/frontend/add_tear_down_test.dart

Previously the tests validated that an error Future which originates in
one zone is able to complete as an error in the other zone. Since errors
are not allowed to cross zone boundaries the future would never complete
and result in a test timeout.
Zones can indicate directly when they are in the same error zone. Using
this API means the test can fail fast instead of a waiting for a
timeout, and the API more directly expresses the intent of the test.

Refactor tests for consistent error zones

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/reporter/json.dart
pkgs/test_core/pubspec.yaml

The `StateError` had been put in with #1245 in order to facilitate
debugging this problem when it surfaces sometimes for flutter.
In #1258 Jake pointed out that there is a comment which mentions that
the `runnerSuite` may be null if it is unavailable due to a load error.
I'm still not sure exactly the conditions that lead to this behavior,
but it should ideally come with some other more clear error, so ignoring
it here should hopefully make things less confusing.

Ignore a null runner suite in json reporter

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/node/platform.dart

Fixes #1278
Copy the `_loopback` code from `package:multi_server_socket` but model
it as a `List<ServerSocket>` instead of a single server. Remove the
unnecessary arguments for handling anything other than port 0.
Use a `finally` block to ensure the socket servers are always closed.

Add back multi server for node platform

---

pkgs/test_api/lib/src/backend/invoker.dart

Very minor - allows jumping to definition on `_handleError` which makes
things slightly easier to navigate around.

Add a cast on the Invoker pulled from the zone

---

.travis.yml
pkgs/test/mono_pkg.yaml
pkgs/test/test/runner/hybrid_test.dart
pkgs/test_api/lib/src/backend/invoker.dart
pkgs/test_core/lib/src/runner/configuration.dart
pkgs/test_core/lib/src/runner/configuration/load.dart
pkgs/test_core/lib/src/runner/parse_metadata.dart
pkgs/test_core/lib/src/runner/reporter/json.dart
pkgs/test_core/lib/src/util/io.dart
tool/travis.sh

- Add nullable types to the Configuration.loadFromString API which was
added on the master branch.
- Remove the extra copy of `rootPackageLanguageVersionComment` since
it was defined in different libraries on the master branch and
null_safety branch.
- Remove erroneously added `?` on a field in an opt-out library.

Fix some static errors after merge from master

---

pkgs/test_api/lib/src/backend/stack_trace_formatter.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/configuration.dart
pkgs/test_core/lib/src/runner/engine.dart
pkgs/test_core/lib/src/runner/live_suite_controller.dart
pkgs/test_core/lib/src/runner/suite.dart
pkgs/test_core/pubspec.yaml

These references don't work in the analysis server and would report an
error if we turn on the `comment_references` lint.

Remove some comment references to "[this]"

---

pkgs/test_core/lib/src/executable.dart
pkgs/test_core/lib/src/util/io.dart

Fuchsia doesn't have POSIX signals, and compons can't access stdin on
Fuchsia. Avoid accessing anything related to prevent test runner from
crashing for Fuchsia on-device tests.

Support Fuchsia in test_core executable.

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/test_core.dart
pkgs/test_core/pubspec.yaml

We have a definition of `unawaited` which is visible from of of the
`test_api/src/` imports to avoid a transitive dep on `pedeantic`. This
causes a static error onces `meta` has a method with the same name.
`pedantic` will be updated to export this method and `test_api` should
do the same until we migrate all usages to the definition from `meta`.
We can't migrate directly to the definition from `meta` since the
version which adds this has a lower SDK bound of `2.9.0` and we aren't
prepared to set our lower bound that high, especially since that SDK is
not yet published. An explicit show on the import of `meta` is backwards
and forward compatible.

Fix error when meta add unawaited

---

pkgs/test_api/lib/src/backend/invoker.dart
pkgs/test_api/pubspec.yaml
pkgs/test_api/test/backend/invoker_test.dart

The commented purpose and usage of this field are to avoid problems
where a `heartbeat` call is in a `Zone` which interferes with `Timer`
behavior. `Zone.root` should always have known behavior, or at the least
the `_invokerZone` would have always been a descendent of this root zone
anyway, so it shouldn't introduce any problems that weren't present
before.

Stop holding the InvokerZone on the Invoker

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Use an `any` constraint from `test_core` since the constraint from
`test_api` is already narrow.

Update dep on matcher and prepare to publish

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

I kept these as all non-breaking for now.
The main reason is that test_api and test_core do have some dependencies that are not migrated (mockito, build_test), and I don't want to have issues landing in flutter.

Prep for merge into master

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/fake.dart
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/fake.dart
pkgs/test_api/lib/src/frontend/fake.dart
pkgs/test_api/test/frontend/fake_test.dart

With null safety, making a class derived from Fake will become much
more widely useful, since it will no longer be possible to for a test
method to pass `null` into a non-nullable API.

Move `Fake` class from Mockito to the test API.

---

.travis.yml
pkgs/test/mono_pkg.yaml
pkgs/test/pubspec.yaml
pkgs/test_api/mono_pkg.yaml
pkgs/test_api/pubspec.yaml
pkgs/test_core/mono_pkg.yaml
pkgs/test_core/pubspec.yaml

This is in preparation for the actual 2.10 dev sdk release.
The tests are going to be failing until we update all transitive deps in a similar fashion (they need to declare a 2.10 language version).
The plan for lack of a better option is to just do these all as quickly as possible (and merge them into master), and then go re-run the travis jobs to get the build green again afterwords.

update for the 2.10 dev sdk

---

pkgs/test/pubspec.yaml
pkgs/test_api/pubspec.yaml
pkgs/test_core/pubspec.yaml

Bump the min SDK constraint to `2.10.0-0` so that they pick up the
`2.10` language version which is required to opt in to null safety with
the `2.10` SDKs.

Prepare for the 2.10 SDK

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

We accidentally did a breaking change and are changing it back to non-breaking

update source_maps constraint

---

pkgs/test/test/runner/runner_test.dart
pkgs/test_core/lib/test_core.dart

When I have a test like this:
```dart
import 'package:test/test.dart';
void main() async {
setUp(() {});
await otherSetUp();
test('a test', () {});
}
Future<void> otherSetUp() {}
```
Running it with `pub test $this_file` works, but running it with `pub run $this_file` throws the following error:
```
Unhandled exception:
Bad state: Can't call test() once tests have begun running.
#0      Declarer._checkNotBuilt (package:test_api/src/backend/declarer.dart:286:5)
#1      Declarer.test (package:test_api/src/backend/declarer.dart:142:5)
#2      test (package:test_core/test_core.dart:138:13)
#3      main (file:///Users/jiahaog/dev/hello_dart/test/hello_dart_test.dart:8:3)
<asynchronous suspension>
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#5 …
```

Fix declarer inconsistencies with async test setup

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/loader.dart
pkgs/test_core/pubspec.yaml

Since it's an empty stream it doesn't matter if it is a broadcast or
single-subscription stream. `Stream.empty` is more descriptive than
`Stream.fromIterable` with a hardcoded empty list.
Collapse the short-circuit checks into a single conditional.

Replace Stream.fromIterable([]) with Stream.empty()

---

pkgs/test_core/lib/src/runner/package_version.dart
pkgs/test_core/lib/src/util/detaching_future.dart

Fixes one reason that an instance of `Invoker` is always retained        
through the end of the test. Working towards making it easier to         
diagnose why the test runner sometimes fails to exit on travis for #599.

Add DetachingFuture utility

---

pkgs/test_core/lib/src/runner/reporter.dart
pkgs/test_core/lib/src/runner/reporter/compact.dart
pkgs/test_core/lib/src/runner/reporter/expanded.dart
pkgs/test_core/lib/src/runner/reporter/json.dart
pkgs/test_core/lib/src/runner/reporter/multiplex.dart

This method is never called from outside any reporter so it is
unnecessary to require it. The cancel method on `ExpandedReporter` was
never called before, add a call in `_onDone` to match the other
reporters.

Remove cancel from Reporter interface

---

pkgs/test_core/lib/src/runner/reporter/compact.dart
pkgs/test_core/lib/src/runner/reporter/expanded.dart
pkgs/test_core/lib/src/runner/reporter/json.dart

Resolves some TODOs from the migration, the `AsyncError` type in the SDK
now has non-nullable `stackTrace` field.

Rely on non-null stack trace from AsyncError

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/runner_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/configuration/args.dart
pkgs/test_core/lib/src/runner/configuration/reporters.dart
pkgs/test_core/pubspec.yaml

Clean up `--help` to better align with other commands captured in Dart CLI.
Closes https://github.com/dart-lang/test/issues/1330

Clean up --help

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/load_suite.dart
pkgs/test_core/pubspec.yaml

Change an import of `test_core.dart` to an import of `package:test_api`. 
Add an explicit show to make it more clear that only Timeout is used.
Other minor cleanup:
- Remove a stale ignore from when DDC struggled with conditional
imports.
- Fix some lints about unnecessary `this`.

Avoid importing all of test_core from load_suite

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/platform.dart

Towards #962
Make it easier to import the necessary things for writing a custom
platform. This does not expose `executable` so a custom test runner
would need to import at a minimum this and the executable. The symbols
exported here are the ones used by `flutter_tools` in
`flutter_platform.dart` and `test_wrapper.dart`, if other platforms need
other symbols we may need to expand this some.
The import remains a `src` import since these are not yet stable enough
to be fully public. Centralizing and adding `show` clauses will make it
easier to know what is used and for which intent.

Add a centralized platform import

---

pkgs/test/README.md

The documentation recommends adding `custom-html-template-path` to a configuration file to use custom HTML templates. However, this will not work - you actually have to add `custom_html_template_path` (See https://github.com/dart-lang/test/pull/1127/files#diff-b9a58c9d38842cb742b063d60ff6fb18R254)

Fix documentation over custom HTML templates

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/frontend/on_platform.dart
pkgs/test_api/lib/src/frontend/retry.dart
pkgs/test_api/lib/src/frontend/skip.dart
pkgs/test_api/lib/src/frontend/tags.dart
pkgs/test_api/lib/src/frontend/timeout.dart
pkgs/test_api/pubspec.yaml
pkgs/test_core/pubspec.yaml

This will allow the analyzer to emit diagnostics when the annotations
are used in places where they will not be honored by the test runner.
When used as annotations (as opposed to arguments to `test` or `group`)
the test runner only looks at the library level and all annotations
apply to an entire test suite.

Add Target annotations to annotation classes

---

pkgs/test/CHANGELOG.md
pkgs/test/test/runner/pause_after_load_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner.dart
pkgs/test_core/lib/src/runner/vm/platform.dart

Closes #1206
- Pass `silenceOutput` when calling `controlWebServer`.
- Drop the check and warning for missing `SILENT_OBSERVATORY`.
- Drop the test for the warning.

Drop need for SILENT_OBSERVATORY environment

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Now that we are rolling 2.11-dev SDKs to flutter, we need published
versions that allow the `2.11.0-dev` SDK.

Allow 2.10 stable and 2.11.0-dev SDKs

---

pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/declarer.dart
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/direct_run.dart
pkgs/test_core/lib/src/direct_run.dart
pkgs/test_core/pubspec.yaml

Towards #1310, #1328
Add `directRunTest` to configure a reporter and run tests directly in
the same isolate.
Add `enumerateTestCases` to collect test names without running them, and
`directRunSingleTest` to run a specific test by its full name. These
APIs ensure the uniqueness of test names to avoid ambiguity. This
restriction may be spread to tests run through the normal test runner as
well.
- Add `fullTestName` option on `Declarer`. When used, only the test (or
tests if uniqueness is not checked separately) will be considered as a
test case.
- Add `directRunTest`, `enumerateTestCases`, and `directRunSingleTest`
APIs. These are kept under a `lib/src/` import for now, and any other
package that uses these APIs should pin to a specific version of
`package:test_core`. The details of these …

Add capabilities for building direct test runners

---

pkgs/test_api/lib/src/frontend/throws_matcher.dart
pkgs/test_api/test/frontend/expect_async_test.dart
pkgs/test_core/lib/src/runner/live_suite.dart
pkgs/test_core/lib/src/runner/platform.dart
pkgs/test_core/lib/src/runner/plugin/remote_platform_helpers.dart
pkgs/test_core/lib/src/util/dart.dart

Since Dart 2.1, Future and Stream have been exported from dart:core

Remove unused dart:async imports

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/chrome.dart
pkgs/test/pubspec.yaml

The usage was unnecessary since the library it is used in is not cross
platform. The `package:http` is a little nicer, add a small extension to
give a similar API here.
Also reuse the HttpClient across both requests rather than create a
separate client for each one which is what the `package:http` top-level
APIs would do.

Remove dependency on package:http

---

pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/remote_listener.dart
pkgs/test_api/pubspec.yaml

This had been synchronous in order to respond to syntax errors when the
isolate tried to start running. In dart 2 the isolate will fail to start
entirely and no code will run.

Update comment referring to closed issue

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/reporter/compact.dart
pkgs/test_core/pubspec.yaml

Fixes https://github.com/dart-lang/test/issues/1362

fix crash if _lastProgressMessage is null when logging progress

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Use a 2.12.0 lower bound since pub does not understand allowed
experiments for earlier versions.
Use a 3.0.0 upper bound to avoid a warning in pub and to give some
flexibility in publishing for stable.

Bump SDK constraints for pub

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/bootstrap/browser.dart
pkgs/test/pubspec.yaml

This lifts a requirement that browser tests must be executed
inside an <iframe>.

Allow to inject a test channel for browser tests

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/browser.dart
pkgs/test/pubspec.yaml
pkgs/test/test/util/string_literal_iterator_test.dart
pkgs/test/tool/host.dart
pkgs/test_api/lib/src/remote_listener.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/loader.dart
pkgs/test_core/lib/src/runner/parse_metadata.dart
pkgs/test_core/lib/src/util/dart.dart
pkgs/test_core/pubspec.yaml

Cherry pick f0bc5c22aa031a6d178b4e46c014ab45e7f25308 to stop using the
removed import.
Bump dependencies to allow the latest analyzer.

Backport support for latest package:analyzer

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/platform.dart
pkgs/test/pubspec.yaml

Fixes https://github.com/dart-lang/build/issues/2901
This has no effect for DDC (a source map won't exist in that location), but does provide some mapping for dart2js source maps (although you see more unnecessary lines than you would normally).
Before:
```
Bad state: Oh no!
opted_in_test.dart.browser_test.dart.js 975:17    Object.wrapException
opted_in_test.dart.browser_test.dart.js 26226:15  main_closure0.call$0
opted_in_test.dart.browser_test.dart.js 23893:53  <fn>
opted_in_test.dart.browser_test.dart.js 4030:15   _wrapJsFunctionForAsync_closure.$protected
opted_in_test.dart.browser_test.dart.js 12766:12  _wrapJsFunctionForAsync_closure.call$2
opted_in_test.dart.browser_test.dart.js 22947:21  StackZoneSpecification__registerBinaryCallback__closure.call$0 …
```

set up stack trace mappers in precompiled mode if source maps exist

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/io.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/spawn_hybrid.dart
pkgs/test_core/pubspec.yaml

Previously we were getting uris like `file:///C:/C:/<stuff>`. I had to do some funky things to get rid of the leading `/` from the `C:` style uris as well.
I also noticed that the uris I get back from `Isolate.resolvePackageUri` are always posix style and not windows style paths, so this keeps the consistency with that where previously we ended up with mixes of `\` and `/` in some places.
This will also probably have to be backported.
Fixes https://github.com/dart-lang/test/issues/1382

Fix spawnHybridUri on windows

---

.travis.yml
pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/node/socket_channel.dart
pkgs/test/mono_pkg.yaml
pkgs/test/pubspec.yaml
tool/travis.sh

The `StreamChannelTransformer` has tricky edge cases around subtyping
since it's generic type arguments should be contravariant instead of
covariant. Since there are different subtype relationships necessary
between the `sink` and `stream` transforms it is easier to work with by
splitting the transformation steps rather than modeling it exclusively
with multiple `StreamChannelTransformer` steps.

Fix type errors for node socket channel

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

The breaking changes do not impact the usage from the package.

Expand constraints on package:yaml

---

pkgs/test_api/lib/src/frontend/async_matcher.dart
pkgs/test_api/lib/src/frontend/expect.dart
pkgs/test_api/lib/src/frontend/future_matchers.dart
pkgs/test_api/lib/src/frontend/stream_matcher.dart
pkgs/test_api/lib/src/frontend/stream_matchers.dart
pkgs/test_api/lib/src/frontend/utils.dart
pkgs/test_api/test/frontend/expect_test.dart
pkgs/test_api/test/frontend/never_called_test.dart
pkgs/test_api/test/frontend/tear_down_all_test.dart
pkgs/test_api/test/utils.dart

As of Dart 2.1, Future/Stream have been exported from dart:core.

test_api: Remove unused dart:async imports.

---

pkgs/test_core/lib/src/runner/compiler_pool.dart
pkgs/test_core/lib/src/runner/spawn_hybrid.dart

As of Dart 2.1, Future/Stream have been exported from dart:core.

test_core: Remove unused dart:async imports.

---

pkgs/test_api/lib/src/backend/metadata.dart
pkgs/test_core/lib/src/runner/engine.dart

The analyzer will start reporting this when dart-lang/sdk#44569 is implemented.

Remove unnecessary import

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

The pub solve still won't pick these up due to constraints from
`analyzer` and `coverage`.

Allow the latest package:args

---

pkgs/test/lib/src/runner/browser/browser.dart
pkgs/test/lib/src/runner/browser/browser_manager.dart
pkgs/test/lib/src/runner/browser/platform.dart
pkgs/test/lib/src/runner/node/platform.dart
pkgs/test/test/runner/compact_reporter_test.dart
pkgs/test/test/runner/expanded_reporter_test.dart
pkgs/test/test/runner/json_file_reporter_test.dart
pkgs/test/test/runner/json_reporter_test.dart
pkgs/test/test/runner/json_reporter_utils.dart
pkgs/test/test/runner/signal_test.dart
pkgs/test/test/runner/test_on_test.dart
pkgs/test/test/utils.dart
pkgs/test/tool/host.dart
pkgs/test_core/lib/src/runner/platform.dart
pkgs/test_core/lib/src/runner/vm/platform.dart

This mostly means adding a type argument to a function which returns "Future",
or a field which is ambiguously a "StreamSubscription" or a "Completer".
If you write `Future f = Future<int>.value(7)`, you have just created a
`Future<dynamic>`. The strict-raw-types analysis option helps here.
This CL does not enable strict-raw-types in analysis_options because the other packages need CLs too, and I didn't want this to be too big.

Comply with strict-raw-types in test package.

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Change all constraints with an upper bound which prevents the stable
version for null safety into caret constraints which allow them.
Expand constraint on `package_config` to allow `2.x`.

Expand null safe constraints

---

pkgs/test_api/lib/src/backend/metadata.dart
pkgs/test_api/lib/src/frontend/async_matcher.dart
pkgs/test_api/lib/src/frontend/expect.dart
pkgs/test_api/lib/src/frontend/future_matchers.dart
pkgs/test_api/lib/src/frontend/stream_matcher.dart
pkgs/test_api/lib/src/frontend/stream_matchers.dart
pkgs/test_api/lib/src/frontend/utils.dart
pkgs/test_api/test/frontend/expect_test.dart
pkgs/test_api/test/frontend/never_called_test.dart
pkgs/test_api/test/frontend/tear_down_all_test.dart
pkgs/test_api/test/utils.dart

Reverts https://github.com/dart-lang/test/commit/ce2a16c16f282acd6d1a2566c5dd64e70ea2f080 and https://github.com/dart-lang/test/commit/841254aaf24714f65cc5ab6e1755b60ad11c4453 for the stable release.
These changes never landed in a previous release and we want to ensure there are no code differences between the last null safety pre-release and stable.
These can be re-landed after publishing stable.

Revert import removals

---

pkgs/test_api/pubspec.yaml

This was missed in https://github.com/dart-lang/test/pull/1417

Bump test_api version in pubspec

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

- Drop the `-nullsafety` prerelease suffix from the version.
- Bump to the stable versions for all normal dependencies.
- Bump to the stable versions for all `test_api` dependencies from
`test` and `test_core`.
Only `test_api` is going stable for now. `test` and `test_core` will go
to stable after the remainder of their dependencies go stable.

Prepare to publish test_api for stable null safety

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/runner_suite.dart
pkgs/test_core/lib/src/runner/suite.dart
pkgs/test_core/pubspec.yaml

Remove extra casts that were used to work around bugs in the SDK. In one
case the cast had already been removed but the comment remained.

Remove references to fixed SDK issues

---

analysis_options.yaml

The upgrades to `error` are no longer necessary because we run the
analyzer with the `--fatal-infos` flag.
The ignore for TODO is no longer necessary because the analysis server
allows configuring whether to show TODO as diagnostics.

Drop explicit diagnostic upgrades

---

pkgs/test_core/lib/src/runner/debugger.dart

This version of the test package will never run with Dart 1.11 so the
message will never apply.

Remove a reference to a very old SDK version

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml

forgot to do this in 0.16.1 (hidden by dep overrides :( )

udpate test_core dep in test

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner.dart
pkgs/test_core/pubspec.yaml

The method is only called from one place with a consistently typed
argument, so the generics are not buying value. Remove them to make the
code simpler.

Drop an unnecessary generic on a method

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Also removes some unused deps from test_api, and unified quote style in pubspecs.
Waiting to publish until we can update node_preamble (or may just add that here if it lands soon and then remove the dev).
Then we can finish the migration to null safety after that 🎉

update test_core and test to allow latest published deps

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/browser.dart
pkgs/test/lib/src/runner/browser/browser_manager.dart
pkgs/test/lib/src/runner/browser/chrome.dart
pkgs/test/lib/src/runner/browser/default_settings.dart
pkgs/test/lib/src/runner/browser/firefox.dart
pkgs/test/lib/src/runner/browser/internet_explorer.dart
pkgs/test/lib/src/runner/browser/phantom_js.dart
pkgs/test/lib/src/runner/browser/platform.dart
pkgs/test/lib/src/runner/browser/safari.dart
pkgs/test/lib/src/runner/executable_settings.dart
pkgs/test/lib/src/runner/node/platform.dart
pkgs/test/lib/src/util/one_off_handler.dart
pkgs/test/lib/src/util/package_map.dart
pkgs/test/lib/src/util/path_handler.dart
pkgs/test/pubspec.yaml
pkgs/test/test/runner/browser/chrome_test.dart
pkgs/test/test/runner/browser/firefox_test.dart
pkgs/test/test/runner/browser/internet_explorer_test.dart
pkgs/test/test/runner/browser/loader_test.dart
pkgs/test/test/runner/browser/phantom_js_test.dart
pkgs/test/test/runner/browser/safari_test.dart
pkgs/test/test/runner/configuration/custom_platform_test.dart
pkgs/test/test/util/one_off_handler_test.dart
pkgs/test/test/util/path_handler_test.dart
pkgs/test/tool/host.dart
pkgs/test_api/lib/src/utils.dart
pkgs/test_core/lib/src/runner/engine.dart
pkgs/test_core/lib/src/runner/plugin/platform_helpers.dart
pkgs/test_core/lib/src/runner/vm/platform.dart

Enables many more sound null safe tests, and the only runner code opted out is the node platform and executable itself.

Migrate package:test except for the node platform

---

pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/frontend/expect.dart
pkgs/test_api/lib/src/util/remote_exception.dart
pkgs/test_api/pubspec.yaml

Once this lands internally we can send another pr to publish new versions of test_core and test to allow this version.

fix handling of null remote exception messages

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Also release a new test_core and test that depend on it.
Fixes an issue when `Error`s are serialized as remote exceptions. We now allow an empty message and properly de-serialize it.

prep to release the latest test_api

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/runner_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/configuration/args.dart
pkgs/test_core/pubspec.yaml

Closes #1358
Stack trace chaining has a negative impact on performance, and the VM
has improved async stack trace chaining by default so the value has
dropped significantly on the VM platform. Despite the value on the web,
it will still be better for the majority of users and use cases to run
tests faster by default, and allow for the `--chain-stack-traces` flag
which can be used when debugging a failure is the explicit goal.

Disable stack trace chaining by default

---

pkgs/test/lib/src/runner/browser/browser.dart
pkgs/test/lib/src/runner/browser/platform.dart
pkgs/test/lib/src/runner/node/platform.dart
pkgs/test_core/lib/src/direct_run.dart
pkgs/test_core/lib/src/executable.dart
pkgs/test_core/lib/src/runner/configuration/load.dart
pkgs/test_core/lib/src/runner/load_exception.dart
pkgs/test_core/lib/src/util/dart.dart
pkgs/test_core/lib/src/util/errors.dart
pkgs/test_core/lib/src/util/io.dart
pkgs/test_core/lib/src/util/os.dart
pkgs/test_core/lib/test_core.dart

Move out utilities which are imported from files which need to avoid
imports to `dart:io` or `dart:isolate`.

Separate out utilities from io required libraries

---

pkgs/test/README.md

The Dart compiler can't detect that the variable is set in setUp before
it's used.  Mark them late to let the compiler know that they'll be set.

Fix example for null safety

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/compact_reporter_test.dart
pkgs/test/test/runner/expanded_reporter_test.dart
pkgs/test/test/runner/json_file_reporter_test.dart
pkgs/test/test/runner/json_reporter_test.dart
pkgs/test/test/runner/runner_test.dart
pkgs/test/test/utils.dart
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/invoker.dart
pkgs/test_api/lib/src/backend/metadata.dart
pkgs/test_api/pubspec.yaml
pkgs/test_api/test/backend/invoker_test.dart
pkgs/test_api/test/utils.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Changing the default in the arg parser did not change the runner
behavior, and the test that changed was a false positive for the
behavior difference.
Change the default for `chainStackTraces` in the `Metadata` class which
is the real owner of the defaults. Enable stack trace chaining by
default when using `--verbose-trace`, otherwise default to off.
Remove the extra failure output about enabling stack trace chaining for
load "test" failures since they often have no stack trace.
The output is still very verbose - this commit does not reduce the
output to only once at the end of the tests, but that is something we
should consider doing.
Enable stack trace chaining in some tests where the output is checked in
the test.

Disable stack trace chains by default - for real

---

pkgs/test/test/runner/hybrid_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/hybrid_listener.dart

Mention explicitly that the first parameter must be a `StreamChannel<dynamic>` or a `StreamChannel<Object?>`.
Proposed resolution to https://github.com/dart-lang/test/issues/1469.

Improve the error message for hybridMain functions

---

pkgs/test_core/lib/src/runner/configuration.dart

Using the smallest pattern possible, rather than matching surround
fields, helps readability because the things that behave differently
look different.
Use a public final field over a private final with a public getter for
`coverage`. This is different from other getters in this class in that
it doesn't do null defaulting.
Use a `late final` over `??=` for lazy initialization of the `knownTags`
field. This is different from the `_knownPreset` use case, which
sometimes needs to be set an on an instance directly instead of falling
through to the default initializing expression.

Drop two unnecessary getters in Configuration

---

pkgs/test_api/lib/src/backend/invoker.dart

I missed this call in #1270
Since there is no longer a `_counterKey` in the zone values for this
call to `runZoned` it doesn't make sense for it to be stored in the list
of zones that have async counters.

Remove an erroneous _outstandingCallbackZone

---

pkgs/test/lib/src/runner/browser/browser_manager.dart
pkgs/test/lib/src/runner/browser/platform.dart
pkgs/test/lib/src/runner/node/platform.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/platform.dart
pkgs/test_core/lib/src/runner/plugin/platform_helpers.dart
pkgs/test_core/lib/src/runner/vm/platform.dart
pkgs/test_core/pubspec.yaml

Towards #1478
The argument to `PlatformPlugin.load` is always a `Map`. The intent is
always to pass it to `deserializeSuite`, where it is unconditionally
cast to `Map`. The loose `Object` argument type does not add any
capabilities.
Changing `PlatformPlugin.load` argument type is not likely to be
breaking since it is not intended for use from outside callers. Changing
the `deserializeSuite` argument is breaking for platform
implementations. Change `PlatformPlugin.load` now so implementations
can adjust before the change to `deserializeSuite`.

Make the `message` argument a Map

---

pkgs/test_api/lib/src/frontend/async_matcher.dart
pkgs/test_api/lib/src/frontend/expect.dart

We cannot update `flutter_test` imports until after we publish, but this
package needs to land internally before then. Re-export some
implementation libraries that are imported from `src` from `analyzer`
tests and from `flutter_test`.

Re-export some libraries from prior locations

---

pkgs/test_api/lib/hooks.dart
pkgs/test_api/lib/src/expect/async_matcher.dart
pkgs/test_api/lib/src/expect/expect.dart
pkgs/test_api/lib/src/expect/expect_async.dart
pkgs/test_api/pubspec.yaml
pkgs/test_api/test/frontend/expect_async_test.dart

The `mustWaitFor` API has tricky edges around futures created in a
`FakeAsync` zone. Return to a non-Future based API which abstracts the
trickiness around zones (other than that the `markPending` call must be
in the test zone, which is the case for all APIs) and errors.

Switch from mustWaitFor to markPending

---

pkgs/test_core/lib/src/executable.dart
pkgs/test_core/lib/src/runner/configuration/reporters.dart

Returns to the previous style for nested ternary conditional
expressions.

Reformat with the latest dartfmt

---

pkgs/test_api/lib/src/remote_listener.dart
pkgs/test_core/lib/src/runner/load_suite.dart

Avoid importing `test_api/test_api.dart` from `test_core` except in
`test_core.dart` which re-exports it. This allows a separate
`test_core:scaffolding` target with limited transitive dependencies.
Add back `test_api/lib/src/remote_listener.dart` to reduce churn.

More target split fixes

---

CONTRIBUTING.md

Fixes https://github.com/dart-lang/test/issues/1498
I would remove the sentence about the AUTHORS file but I don't want to touch the substance of the blurb even though its obviously not providing value right now.

Update year in example copyright blurb

---

pkgs/test_api/test/import_restrictions_test.dart

The goal of the changes to AnalysisSession is to make it easier to
understand when the result is valid, and when it is not. Previously
sometimes we throw an exception, sometimes return a result that returns
nulls, sometimes return a result that is not valid, so its getters
throw.
Since the result was previously assumed to be valid, continue making the
same assumption explicitly by immediately casting the result.

Replace use of deprecated AnalysisSession methods

---

.github/workflows/dart.yml
analysis_options.yaml
integration_tests/nnbd_opted_in/mono_pkg.yaml
integration_tests/nnbd_opted_in/pubspec.yaml
integration_tests/nnbd_opted_in/test/common/is_opted_out.dart
integration_tests/nnbd_opted_in/test/opted_in_test.dart
integration_tests/nnbd_opted_in/test/opted_out_test.dart
integration_tests/nnbd_opted_out/test/common/is_opted_out.dart
integration_tests/nnbd_opted_out/test/opted_in_test.dart
integration_tests/nnbd_opted_out/test/opted_out_test.dart
integration_tests/nnbd_opted_out/test/spawn_hybrid_code_test.dart
pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/vm/platform.dart
pkgs/test_core/lib/src/runner/vm/test_compiler.dart
pkgs/test_core/pubspec.yaml

Fixes an issue where all tests were compiled in either sound or unsound mode, depending on which type of test was encountered first.
We now create a separate compiler for each language version that we see in tests.

Fix mixed mode tests

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/vm/test_compiler.dart
pkgs/test_core/pubspec.yaml

Fixes https://github.com/dart-lang/test/issues/1506
I couldn't repro this locally on my windows box but I am testing the fix on github CI over at [mono_repo #317](https://github.com/google/mono_repo.dart/pull/317).
Basically my assumption here is that the `uri` we were grabbing off of the `Directory` object had a mix of forward/backward slashes.

fix sdk root path on windows

---

.github/workflows/dart.yml
integration_tests/nnbd_opted_in/mono_pkg.yaml
integration_tests/nnbd_opted_out/mono_pkg.yaml
pkgs/test/mono_pkg.yaml
pkgs/test_api/mono_pkg.yaml

~Enables all tests on windows, I may disable some of the tests after I see what the CI looks like.~
Enabled windows testing for test_api and integration tests, windows tests still failing for package:test due to xvfb issues. If/once we resolve that we can add those back also.

resume running tests on windows

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/runner_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/compiler_pool.dart
pkgs/test_core/lib/src/runner/vm/test_compiler.dart
pkgs/test_core/lib/src/util/dart.dart
pkgs/test_core/pubspec.yaml

This brings back the old behavior we got automatically with the data isolate loading strategy. I also added  a test to validate we don't break this in the future, which also covers the already implemented behavior for web.
Fixes https://github.com/dart-lang/sdk/issues/45835

forward language experiments args from the runner executable to the frontend server compiler

---

pkgs/test/README.md

Start some docs on the limitations and workarounds for configuration
compilation of the tests.

Start docs on configuration compilation

---

pkgs/test/CHANGELOG.md
pkgs/test/doc/json_reporter.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/runner_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/configuration/args.dart
pkgs/test_core/pubspec.yaml

Towards #1521
The argument causes an output to a file in _addition_ to the output on
stdout. Avoid the word "instead" to avoid confusion that this argument
disables reporting on stdout.

Tweak the phrasing for doc on file reporters

---

pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/configuration/retry.dart
pkgs/test_api/pubspec.yaml

Fixes #1529
Drop mention of `TestFailure` - there is no distinction between the
types of exceptions which are thrown.
Correct the phrasing to avoid making it seem like the annotation can be
applied to a single test - as an annotation it can only be applied to
the test suite, and for individual groups or tests a named argument is
used instead.

Correct docs for the Retry annotation

---

pkgs/test/README.md

Most of the links to the API documentation were leading to 404 pages. These have been fixed to point at the correct documentation pages. Also made some minor changes to cleanup grammar errors and add line breaks where they were missing for consistency.

Fixed links in README.md which were resolving to a 404 error page.

---

pkgs/test_api/lib/src/expect/async_matcher.dart
pkgs/test_api/test/utils.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/configuration.dart
pkgs/test_core/lib/src/runner/configuration/load.dart
pkgs/test_core/lib/src/runner/engine.dart
pkgs/test_core/lib/src/runner/live_suite.dart
pkgs/test_core/lib/src/runner/live_suite_controller.dart
pkgs/test_core/lib/src/runner/load_suite.dart
pkgs/test_core/lib/src/runner/runner_suite.dart
pkgs/test_core/pubspec.yaml

- Inline `loadFromString` into `load` and drop the extra `Configuration`
constructor.
- `Engine.liveSuites` had no readers.
- Initialize `LiveSuiteController.liveSuite` with a `late final` to
avoid an extra getter.
- `LiveSuiteController.isComplete` had no readers.
- `RunnerSuite.channel` had no callers.
- Various test utilities are likely remnants of the package split.

Drop some unused functions

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/scaffolding/utils.dart
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Closes #1340
This PR adds a check within `printOnFailure ` and throw an exception if there is no current invoker.
Please let me know if you want me to add some tests to check the behavior of the function.

Fix[test_api]: printOnFailure check current invoker

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/configuration.dart
pkgs/test_core/lib/src/runner/configuration/load.dart
pkgs/test_core/pubspec.yaml

This API is not used within the test runner, but is used from
`build_test`.
Rename what was `loadFromString` to `parse` and move the file reading to
the `Configuration.load` constructor.

Add back Configuration.loadFromString constructor

---

pkgs/test/CHANGELOG.md
pkgs/test/doc/json_reporter.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/reporter/json.dart
pkgs/test_core/pubspec.yaml

Fixes https://github.com/dart-lang/test/issues/1537
Fixes https://github.com/dart-lang/test/issues/1536
Note that this does add an extra `time` field to the `allSuites` event. That shouldn't be breaking though.

update json reporter docs for null safety, add `time` field to `AllSuitesEvent`

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/configuration/configuration_test.dart
pkgs/test/test/runner/configuration/suite_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner.dart
pkgs/test_core/lib/src/runner/configuration.dart
pkgs/test_core/lib/src/runner/engine.dart
pkgs/test_core/lib/src/runner/suite.dart
pkgs/test_core/pubspec.yaml

Resolves an issue discovered in #1539
This configuration was attached to the `SuiteConfig` likely because that
was the easiest way to communicate it through to the `Engine` where
required. This introduced a bug where a more specific `SuiteConfig` for
a tag configured in `dart_test.yaml` would always override the apparent
configuration for those suites with the default, which is unshuffled.
There was no indication when this happeened.
Remove `testRandomizedOrderingSeed` form the `SuiteCConfiguration` class
entirely instead of trying to track down where the inconsistency slips
in.

Move testRandomizeOrderingSeed to global level

---

pkgs/test_core/lib/src/runner.dart
pkgs/test_core/lib/src/runner/engine.dart

One internal reporter needs this information.

Make testRandomizeOrderingSeed public on Engine

---

pkgs/test/test/runner/configuration/randomize_order_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/configuration/args.dart

Fixes https://github.com/dart-lang/test/issues/1545
This is hacky but we don't have a good solution right now, added a TODO and filed an issue though.

dont log the --test-randomization-ordering-seed if using the json reporter

---

pkgs/test/test/runner/compact_reporter_test.dart
pkgs/test/test/runner/configuration/custom_platform_test.dart
pkgs/test/test/runner/configuration/tags_test.dart
pkgs/test/test/runner/configuration/top_level_test.dart
pkgs/test/test/runner/expanded_reporter_test.dart
pkgs/test/test/runner/name_test.dart
pkgs/test/test/runner/shard_test.dart
pkgs/test/test/runner/tag_test.dart
pkgs/test/test/runner/test_on_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/executable.dart
pkgs/test_core/lib/src/runner.dart
pkgs/test_core/lib/src/runner/no_tests_found_exception.dart
pkgs/test_core/lib/src/util/exit_codes.dart

Fixes https://github.com/dart-lang/test/issues/1546
I will update the tests and things if we decide this is a fine route to go. I simply used the next exit code in the sequence of special exit codes we have.
I also added some special logging for tags, similar to what existed for the name patterns. It will list the tag configuration, if one was provided.
~~Both of these end up with a different exit code, 65, which indicates some sort of data error in the input (this was used previously when you provided a name regex and there were no matches). I am not sure if we want to also re-use that exit code for the case where there simply weren't any tests.~~ All of these cases now use exit code 79.
We also may want to specialize for additional configuration like platforms? Not sure how deep that …

add a special exit code, 79, used when no tests were found

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

This also removes `-dev` from `test_core` and `test`, and increments `test_api` to `0.4.2` with anticipation that we will publish. If there is a reason not to publish, I can revert these version changes.

Update 'analyzer' constraints to include '2.0.0'.

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/engine.dart
pkgs/test_core/pubspec.yaml

Add a description of the named arguments `testRandomizeOrderingSeed` and
`coverage` to the doc comment for the `Engine` constructor.

Document testRandomizeOrderingSeed on Engine ctor

---

pkgs/test_core/lib/src/runner/configuration/reporters.dart
pkgs/test_core/lib/src/runner/reporter/json.dart

Remove the import to the entire `Configuration` class and pass
explicitly the value from the config that is used. This makes the data
flow explicit instead of through the zone scoped
`Configuration.current`.

Pass specific debug config to json reporter

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/json_reporter_utils.dart
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Copy the changelog from `matcher` into `test` since this is where most
users will see it.

Update matcher dependency and prepare to publish

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/runner_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/vm/test_compiler.dart
pkgs/test_core/pubspec.yaml

We were already caching this but weren't actually using it on subsequent runs 🤦‍♂️ . I also optimized it a bit to only copy the dill file once inside `dispose` instead of updating it repeatedly whenever we see a larger file.
This takes our `test_api` test runs from ~9 seconds to ~4 seconds.
Related to https://github.com/dart-lang/test/issues/1567.

reuse incremental dill files when possible

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/runner_test.dart
pkgs/test_core/pubspec.yaml

These constructors became identical in #650 so we can drop the private
copy altogether.

Remove duplicate private constructor

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/browser/code_server.dart

Closes #1277
Inline the parts of the package that are used in the single testing
library that uses them. Remove unused functionality and where possible
make things private.

Remove dependency on shelf_test_handler

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/suite.dart
pkgs/test_core/pubspec.yaml

Using a set literal with spreads over `.addAll` calls allows the entire
set to collapse to a single expression which lets us use `??=`.
Drop the `_children` getter since it's only used on one place and the
name is not more clear than the implementation.

Use a set literal for knownTags

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/tool/host.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/scaffolding.dart
pkgs/test_core/lib/src/runner/runner_test.dart
pkgs/test_core/pubspec.yaml

The class was removed in dc2fbc50c04ca7f593290a2a4a43f227dba4847a and
replaced with `RemoteListener`.

Replace references to IFrameListener

---

pkgs/test/test/runner/json_reporter_utils.dart

Use a semantically meaningful matcher so the error output is more useful
than seeing two unequal ints. Drop the reason message since the "actual"
output now includes everything we would have wanted from the message.

Use hasLength matcher

---

.gitattributes
.github/workflows/dart.yml
tool/ci.sh

Add a `.gitattributes` file to mark mono_repo outputs as generated files
which allows GitHub diff views to leave them collapsed by default.
Regenerate the file with the latest mono_repo.

Mark mono_repo outputs as generated

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Releases the dropping of the package:pedantic dependency as well as the allow_duplicate_test_names configuration.

prep to release

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/engine.dart
pkgs/test_core/lib/src/runner/reporter/compact.dart
pkgs/test_core/lib/src/runner/reporter/expanded.dart
pkgs/test_core/pubspec.yaml

Towards #1311
Removes a UX concern from `Engine` which no longer needs to worry about
how a reporter might display information about load suites. Makes the
interaction between the engine and reporters less subtle.
Use the term "suite load" over "load test" to start pushing terminology
away from conflating tests and loading.

Stop putting suite loads into active test

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Fixes #1594
We need to publish with an older SDK to work around changes to how pub
finds ignored files.

Prepare to publish again

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/compact_reporter_test.dart
pkgs/test/test/runner/expanded_reporter_test.dart
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/invoker.dart
pkgs/test_api/pubspec.yaml
pkgs/test_api/test/backend/invoker_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/reporter/compact.dart
pkgs/test_core/lib/src/runner/reporter/expanded.dart
pkgs/test_core/pubspec.yaml

Fixes https://github.com/dart-lang/test/issues/1505
Alternatively we could remove this log entirely, but this is one fairly easy solution.

move log about enabling stack trace chaining to the reporters

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/vm/platform.dart
pkgs/test_core/pubspec.yaml

Internally the test runner is run with
`--mark-main-isolate-as-system-isolate`, so when the main isolate exits
any paused-at-exit non-system isolates are also closed. This makes it
impossible to keep a debugger attached to, for instance, example the
state of the heap following the tests.
Wait for all started isolates to exit when closing the VM platform so
that the outer "system" isolate doesn't forcibly close them before they
are done.

Wait for isolate exits from VM platform

---

pkgs/test/lib/src/runner/browser/browser.dart
pkgs/test/lib/src/runner/browser/browser_manager.dart
pkgs/test/lib/src/runner/browser/chrome.dart

Towards #1616
If the process had started but the web page never loaded and connected
the websocket back to the runner we hit a timeout.
- Extend the timeout to see if it reduces the incidence of this failure.
- Add verbose logging flags when launching chrome on linux.
- Store the output from the browser and include it in the timeout message.

Extend timeout for launching browsers

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/runner_test.dart
pkgs/test/test/runner/timeout_test.dart
pkgs/test/test/utils.dart
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/invoker.dart
pkgs/test_api/lib/src/backend/remote_listener.dart
pkgs/test_api/lib/src/backend/suite.dart
pkgs/test_api/pubspec.yaml
pkgs/test_api/test/backend/declarer_test.dart
pkgs/test_api/test/backend/invoker_test.dart
pkgs/test_api/test/utils.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/configuration.dart
pkgs/test_core/lib/src/runner/configuration/args.dart
pkgs/test_core/lib/src/runner/load_suite.dart
pkgs/test_core/lib/src/runner/plugin/platform_helpers.dart
pkgs/test_core/lib/src/runner/runner_suite.dart
pkgs/test_core/pubspec.yaml

This reverts commit bb4f7e85e0e490cae61bbd13245bbd6dd811263d.
This needs to be reverted because it breaks us internally due to the addition of the `configuration.dart` import to some files that previously didn't transitively import `dart:io`.

Revert "add --ignore-timeouts flag (#1635)"

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/chrome.dart
pkgs/test/pubspec.yaml

Log to `stdout` instead of `stderr` so that it works on windows and we
can (hopefully) get more useful output.

Log to stdout from chrome

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/runner_test.dart
pkgs/test/test/runner/timeout_test.dart
pkgs/test/test/utils.dart
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/invoker.dart
pkgs/test_api/lib/src/backend/remote_listener.dart
pkgs/test_api/lib/src/backend/suite.dart
pkgs/test_api/pubspec.yaml
pkgs/test_api/test/backend/declarer_test.dart
pkgs/test_api/test/backend/invoker_test.dart
pkgs/test_api/test/utils.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/configuration.dart
pkgs/test_core/lib/src/runner/configuration/args.dart
pkgs/test_core/lib/src/runner/load_suite.dart
pkgs/test_core/lib/src/runner/plugin/platform_helpers.dart
pkgs/test_core/lib/src/runner/runner_suite.dart
pkgs/test_core/lib/src/runner/suite.dart
pkgs/test_core/pubspec.yaml

I moved the field from the `Configuration` class to the `SuiteConfiguration` class.
This avoids imports of `configuration.dart`, but otherwise doesn't change much except where we read the config from.
In theory this allows more targeted ignoring of timeouts in the future if we come up with a use case for it as well.

Re-land --ignore-timeouts with slight structure change

---

pkgs/test_api/lib/src/backend/suite.dart

This will ease the transition as flutter_test and some internal packages use this constructor.
We can move it back to required in a later release.

make ignoreTimeouts param on Suite not required

---

pkgs/test_core/lib/src/runner/vm/platform.dart

Avoid building URIs manually with brittle Strings. This also makes it
more clear that the Observatory URI is embedding a path and query string
into the fragment, instead of letting it look like part of the URI
itself.
Pull out `serverUri` as a separate variable and use `!` immediately. If
a null shows up this would be a more clear failure than trying to later
treat the string`'null'` as a URI.

Use URI class over manual string manipulation

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/dart.js

Create a policy which appends the test extensions to the URL.
This does not make the script safer, but it does limit the security risk
to the code inside the `createPolicy` call which, in theory, should be
easier to review.

Use trusted types for script URL

---

pkgs/test/test/runner/tag_test.dart

Found while considering usage of `sync*` in general.
In this case enhanced collection literals are more readable than an
immediately invoked `sync*`.

Refactor a sync* into a list literal

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/bootstrap/vm.dart
pkgs/test_core/lib/src/runner/vm/platform.dart

Enables use cases like checking memory usage after a test has run.
This is primarily aimed at an internal use case, if it turns out to be
more widely useful we can better document it. For now it is considered
experimental.
Add a separate channel for communication between the VM platform and the
test isolate bootstrapping. Use a virtual channel for the existing
communication between the `RemoteListener` and the test control helper.
The only messages that are sent across this channel for now are a signal
from the platform to the isolate to pause, and a signal back indicating
that the pause is complete and the isolate can be killed.
Register a service extension (once globally) when loading a test for the
VM platform. The setting is global, which may need to be changed if we
extend this to …

Add an extension to pause VM isolates after tests

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/configuration.dart
pkgs/test_core/lib/src/runner/suite.dart
pkgs/test_core/pubspec.yaml

This field was initialized lazily manually because it needs to refer
to other fields on `this`. Using a `late final` field with an
initializing expression is a more terse way to express this than an
additional private field.

Migrate a ??= getter to a late final field

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/configuration/load.dart
pkgs/test_core/lib/src/runner/util/iterable_set.dart
pkgs/test_core/pubspec.yaml

Recent Dart SDK versions surface an analyzer diagnostic for functions
which use an implicit return at the end for the `null` case.
Migrate from `@alwaysThrows` to a `Never` return type to correct flow
analysis.
Add an explicit `return null` in one method.

Fix implicit null returns

---

pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/expect/expect.dart
pkgs/test_api/pubspec.yaml

The `fail` method was updated with a return type of `Never` and does not
use `@alwaysThrows` anymore. This diagnostic is no longer present and
does not need to be ignored.

Remove a stale TODO and diagnostic ignore

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/vm/platform.dart
pkgs/test_core/pubspec.yaml

These turned out not to accomplish very much and they have been
superseded by the `pauseAfterTests` VM service extension.

Remove the isolate exit waits

---

pkgs/test/CHANGELOG.md
pkgs/test/test/runner/loader_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/loader.dart

Fixes #1667
The special treatment of `packages` as a directory name was from when
`pub` would create a directory with that name under the package root. I
think the intention was to avoid loading in tests from the packages pub
downloaded.
There are still cases where a directory named `packages` is created and
treated specially by Dart tooling, but those use cases are limited to
the web and should no longer have their `test` directories retained.

Stop treating `/packages/` specially

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/parse_metadata.dart
pkgs/test_core/pubspec.yaml

The `type2` api is now deprecated, breaking our CI. This requires a bump in analyzer min version, but we don't need to publish right away.

migrate back to ConstructorName.type from ConstructorName.type2

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/browser_manager.dart
pkgs/test/pubspec.yaml

Towards #1578
Recursively attempt to launch the browser on the first few timeouts
before throwing the ApplicationException.

Add some retry around browser launching

---

pkgs/test_core/lib/src/util/io.dart

https://dart-lang.github.io/linter/lints/null_check_on_nullable_type_parameter.html
Eagerly fixing before we start picking up the new lint package.

Fix an upcoming recommended lint

---

pkgs/test/README.md

Currently, links in the [Stream Matchers](https://github.com/dart-lang/test#stream-matchers) documentation section have the prefix: `https://pub.dev/documentation/test_api/latest/test_api/`. These links lead to 404 error pages.
This PR fixes this issue by updating the prefixes to `https://pub.dev/documentation/test_api/latest/test_api/expect`.

docs(test): fix broken links for 'Stream Matchers'

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Note that `test_api` does not need a version bump, as it has no public dep on analyzer

allow analyzer 4.x, and prepare to publish

---

pkgs/test/pubspec.yaml
pkgs/test_api/lib/src/backend/declarer.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/reporter/github.dart
pkgs/test_core/pubspec.yaml

It turns out test_core did rely on some changes in test_api that weren't documented in the changelog, I yanked version 0.4.12, and this will re-publish it as 0.4.13.
We don't want to do a release in test_api because flutter users won't pick up that version for a long time (on stable at least), so this removes the reliance on those new apis as well.

drop new constants from test_api and usages from test_core, re-publish test_core

---

pkgs/test/pubspec.yaml
pkgs/test_api/pubspec.yaml
pkgs/test_core/pubspec.yaml

- add pubspec `repository` fields to the pubspecs

add pubspec 'repository' fields to the pubspecs

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/chrome.dart
pkgs/test/pubspec.yaml
pkgs/test/test/runner/coverage_test.dart

After upgrade past version 1.15.7 of the test package I was no longer able to collect code coverage.
After working with several of my teammates we tracked down that it was due to a non utf-8 character in one of the javascript sources that are being used by our browser tests.
It looks like this got introduced with the move away from the http package because it looks like it was handling that type of problem [here](https://github.com/dart-lang/http/blob/69d6064dd92470ed7ccd50a808fc789ee7716fe8/lib/src/response.dart#L20-L28).
```
RangeError (index): Invalid value: Not in inclusive range 0..335531: 335532
dart:core                                            List.[]=
package:coverage/src/chrome.dart 137:21              _offsetCoverage
package:coverage/src/chrome.dart 48:28 …
```

Determine encoding of source files used for coverage

---

pkgs/checks/README.md
pkgs/checks/lib/checks.dart
pkgs/checks/lib/context.dart
pkgs/checks/lib/src/checks.dart
pkgs/checks/lib/src/describe.dart
pkgs/checks/lib/src/extensions/async.dart
pkgs/checks/lib/src/extensions/core.dart
pkgs/checks/lib/src/extensions/function.dart
pkgs/checks/lib/src/extensions/iterable.dart
pkgs/checks/lib/src/extensions/map.dart
pkgs/checks/lib/src/extensions/math.dart
pkgs/checks/pubspec.yaml

Implements the core mechanics for defining and using expectations, along
with some basic expectations for core types. Many more expectation
extensions will be added, including `deepEquals` which is already called
out in the docs as necessary to replace the behavior of `equals` from
Matcher.
High level design:
A `Check` is the target for extension methods. It may hold a value (if
it came from `checkThat`) or it may be a placeholder for a value that
could be checked (if it came from `describe`). In test code only the
extensions are visible, to write an expectation a second import exposes
a `context` field on the check which gives access to defining the
expectations.
Each expectation is synchronous or asynchronous, and may be a simple
clause on the value, or may extract a property from the …

Initial implementation of package:checks

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/retry_test.dart
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/configuration/test_on.dart
pkgs/test_core/pubspec.yaml

Closes https://github.com/dart-lang/sdk/issues/49071
Add a `Target` with the `TargetKind.library` so that the analyzer
understands that the annotation is logically applied to the library,
even when it is syntactically applied on an import. This fixes behavior
when sorting imports.
The same configuration was applied to other imports in #1345 and this
looks like it was an accidental omission.

Restrict TestOn to library level

---

pkgs/test/test/runner/runner_test.dart

Fixes https://github.com/dart-lang/test/issues/1707
The other 3 instances are intentional (related to testing opt out behavior and experimental behavior).

remove an unnecessary null safety opt out from a test

---

pkgs/test_api/pubspec.yaml
pkgs/test_api/test/frontend/matcher/throws_type_test.dart

The `NullThrownError` is deprecated.
It should not be possible to have it thrown by null safe Dart, and the type is being replaced by a `TypeError` in general.
A test here assumes that the `toString` of a `NullThrownError` is `Instance of 'NullThrownError'`, where it's now `Instance of 'TypeError'`.
In general, we do not promise that `toString` of error objects are stable. (Our breaking-change rules do not promise to not break programs which depend on specific `Error`s being thrown.)

Fix test which assumes `toString` of `NullThrownError()`.

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Just increased the upper bound because the last matcher release changed
no functionality

Support the latest pkg:matcher

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/reporter/compact.dart
pkgs/test_core/lib/src/runner/reporter/expanded.dart

Closes #1596
The ansi foreground color code `30` is "black", while `90` is "bright
black". This should show up as a more readable gray color for terminals
with dark backgrounds.
Drop the `1;` prefix, which is also setting bold, which has no effect
since `_gray` is only used following `_bold`.

Make load suite labels "bright black"

---

pkgs/test/CHANGELOG.md
pkgs/test/test/runner/precompiled_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/vm/platform.dart

Now that we don't support `.packages` files, if you pass one it won't fall back on the package_config.json any more, which we were apparently relying on.
I did retain support for `.packages` files for now as well, which we could drop eventually but I would want to wait until we can bump our min SDK to a stable version that also doesn't support it.

fix package config path when running precompiled vm tests from source

---

pkgs/test/CHANGELOG.md
pkgs/test/test/runner/compact_reporter_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/reporter/compact.dart

Closes https://github.com/dart-lang/test/issues/1734
Example output:

add a line to re-run the failed test after each failure in the compact reporter

---

pkgs/test/CHANGELOG.md
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/invoker.dart
pkgs/test_api/test/backend/invoker_test.dart

I recently discovered `printOnFailure`, and I love it! However, I noticed that the error messages it prints don't seem to be associated with the failing test, and show up under "loading \<test filename\>..." headers instead. For example:
```dart
import 'package:test/test.dart';
void main() {
test('1', () {
printOnFailure('printOnFailure content 1');
fail('failure');
});
test('2', () {
printOnFailure('printOnFailure content 2');
fail('failure');
});
}
```
The output looks like:
```
$ dart test test/foo_test.dart
00:00 +0 -1: 1 [E]
failure
package:test_api        fail
test/foo_test.dart 6:5  main.<fn>
00:00 +0 -1: loading test/foo_test.dart
printOnFailure content 1
00:00 +0 -2: 2 [E]
failure
package:test_api         fail
test/foo_test.dart 11:5  main.<fn>
00:00 +0 -2: loading …
```

Associate printOnFailure messages with the failing test

---

pkgs/test/CHANGELOG.md
pkgs/test/README.md
pkgs/test/pubspec.yaml

- Use `dart pub` instead of `pub`
- Point `--packages` to `.dart_tool/package_config.json` as suggested by the `coverage` package.

Update coverage usage example

---

.github/workflows/dart.yml
pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/mono_pkg.yaml
pkgs/test_core/pubspec.yaml
tool/ci.sh

Bump test_core SDK constraint to 2.18 since `test_api` and `test`
already have that constraint and it would not be possible to resolve
this `test_core` in a useful way on an older SDK.

Bump to the latest matcher and prepare to publish

---

pkgs/test/CHANGELOG.md
pkgs/test/test/runner/github_reporter_test.dart
pkgs/test_api/lib/src/backend/live_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/reporter/github.dart

- fix an issue with the github reporter
- fix https://github.com/dart-lang/test/issues/1756
This addresses an issue with the github reporter. With tests that fail asynchronously after they've completed, the main github reporter UI would show all the tests as green, but would report 'xx' failed tests at the end. So, users would know something failed, but wouldn't know which test.
This changes to re-report tests which fail asynchronously; they'll show as a passing line, but later show as an ❌ failure line (they'll show two failures since the framework also emits a message about how to test async code).
I'm not sure where to put the changelog entry for this / which package to bump.

fix an issue with the github reporter

---

pkgs/test/CHANGELOG.md
pkgs/test/doc/configuration.md
pkgs/test/pubspec.yaml

I noticed a lack of description for `ignore-timeouts`. 
https://github.com/dart-lang/test/issues/1634
https://github.com/dart-lang/test/blob/master/pkgs/test_api/CHANGELOG.md#049

add lack of description to configuration document

---

pkgs/checks/lib/src/checks.dart
pkgs/checks/test/extensions/async_test.dart

Enables better testing for failing asynchronous expectations. Keep behind a `lib/src/` import for now, until we have a use case to expose it more generally.
Fix fallback for continuing in an async expectation when the expectation failed, but the failure did not throw an exception.

Add support for async soft checks

---

.github/workflows/dart.yml

The ubuntu-latest selection switched to 22.04 which does not include firefox, so the tests which run firefox are failing. The image with 22.04 will be updated to include firefox soon. Until then, select `ubuntu-20.04` directly and disable the mono_repo self validate step.

Temporarily pin to ubuntu 20.04

---

pkgs/test/test/runner/compact_reporter_test.dart
pkgs/test_core/lib/src/runner/reporter/compact.dart

Closes #1798
The windows shell does not allow single quotes around arguments. Use
double quotes on windows, and escape double quotes with 3 double quotes
in a row. The escape sequence closes the quoted string, emits an
adjacent double quote, then opens a new quoted string.
If any quotes are escaped the command will not work for users of the
bash shell in VSCode, but there were already issue with the path
separators in that shell so this shouldn't introduce severe new
problems. Test names that don't have double quotes in them should work
in either place.

Use double quotes for test names on windows

---

pkgs/checks/lib/src/checks.dart
pkgs/checks/test/failure_message_test.dart

When creating a context which is an alias of another, at the same level
in the context tree, the parent was copied. When this happened on the
root in the tree, the alias would also appear to be a root, but it would
be missing some other important information from the root, like the root
label and reason. Separately, the reason which should have always been
read from the root, was not.
- Rename the first constructor from `_` to `_root` to more clearly
indicate where should be used.
- Add a doc that only the root constructor should have no parent.
- Treat the aliased context as the parent, instead of copying the
originals parent. This only matters when the aliased context is the
root, but it does not hurt for the parent references to have an extra
hop in other cases.
- Read the reason from …

Fix missing label and reason after isNotNull

---

pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_api/test/frontend/matcher/throws_type_test.dart

We need to continue testing thee matchers, even though the errors are
deprecated.

Ignore some usage of dperecated errors

---

pkgs/test/lib/src/executable.dart

Dart allows `void` here, but `Future<void>` seems better.

Improve return type of runner `main()`.

---

pkgs/checks/lib/context.dart
pkgs/checks/lib/src/checks.dart
pkgs/checks/lib/src/describe.dart

This will be useful for some condition extensions which want to do
formatting of mismatches from `softCheck`.

Make the prefixFirst utility public

---

pkgs/checks/lib/context.dart
pkgs/checks/lib/src/checks.dart
pkgs/checks/lib/src/describe.dart
pkgs/checks/test/extensions/async_test.dart
pkgs/checks/test/test_shared.dart

Rejections do not carry any context about where in the
Check tree a failure occurred, so they are not sufficient to describe the
difference between the expected and actual values like we use in the
messages for test failure exceptions.
Some conditions which do a `softCheck` may want to print more
detailed mismatch information, for example an `Iterable.every` check may
want to print why an element didn't match, in addition to which index
failed.
Change the `fail` callback from taking a formatted String message and
the Rejection, to taking a `CheckFailure` with the rejection and a lazy
details field. The `FailureDetail` has the `expected` and `actual` that
were previously computed in separate methods, as well as information
about how far to indent lines from the `Rejection` so they line up …

Add FailureDetail to allow expressive failures

---

pkgs/checks/lib/src/extensions/iterable.dart
pkgs/checks/test/extensions/iterable_test.dart

Re-implements `pairwiseCompare` from `matcher` which has limited, but
non-zero usage.
The callback gets a `Check` and the expected value, instead of the
actual and expected values, and causes a condition to fail instead of
returning `false` for mismatch.
Rejects iterables that have the wrong number of elements, or that fail
an individual condition for any element.

Add pairwiseCompare condition

---

pkgs/checks/test/failure_message_test.dart

Replace one test that only checked the first line of a failure with one
that checks the entire message.
Add a test with a failure on a nested check and compare the entire
message to check the indentation and partial "actual" printing.

Add some tests with full failure messages

---

pkgs/checks/pubspec.yaml

These tests do no currently rely on anything that isn't in the published
test runner. Remove the overrides and use the pub published test runner
for now to avoid recompiling on every run.

Drop dependency overrides from pkg:checks

---

pkgs/test/test/runner/line_and_col_test.dart

This test case is flaky on windows and occasionally times out. It is not
clear if it is slow, or if it sometimes gets stuck entirely. Try
doubling the timeout on windows to see if it stops flaking.

Allow slower node test on windows

---

pkgs/checks/lib/src/extensions/math.dart
pkgs/checks/test/extensions/iterable_test.dart
pkgs/checks/test/extensions/math_test.dart
pkgs/checks/test/failure_message_test.dart

- Add `<=` and `>=` to complement `<` and `>`.
- Add `isNaN` and `isNotNaN`.
- Add `closeTo`.
- Add tests for the new conditions.
- Use lowercase for the `which` on `<` and `>`.
- Add positive and negative conditions for `isNegative`, `isFinite`, and `isInfinite`.
- Split the test for less than and greater than into separate cases and
add an equal case.

Add more numeric matchers

---

pkgs/checks/lib/src/extensions/core.dart
pkgs/checks/test/extensions/core_test.dart

Extract the body of `String.equals` to reuse the detailed mismatch
reporting. Add a "display" version of the actual and expected strings to
keep more context form the input which may help identify the issue.

Add String.equalsIgnoringCase

---

pkgs/checks/lib/src/checks.dart

The intention is that one of the fields will always be non-null (or at
least if `T` isn't nullable) so each constructor takes one of the fields
as an argument and sets the other to null. Tighten the argument types
from the nullable field types to actually enforce this. Add a local
variable to allow promotion in one location.

Tighten types of Extracted constructors

---

pkgs/checks/lib/src/extensions/function.dart
pkgs/checks/test/extensions/function_test.dart

Add `returnsNormally` condition which allows chaining further conditions
on the returned value.
Tweak the phrasing for `throws` failures to match current patterns.
Split test for `throws` into multiple cases and nest within a `group`.

Add Function.returnsNormally condition

---

pkgs/checks/lib/src/extensions/string.dart
pkgs/checks/test/extensions/string_test.dart

Copy the `collapseWhitespace` utility from `package:matcher`. Add
`equalsIgnoringWhitespace` and tests. The collapsed version of the
strings needs to also be used for the "display" strings, since they may
have differing indexes.

Add String.equalsIgnoringWhitespace condition

---

pkgs/checks/lib/src/extensions/map.dart
pkgs/checks/test/extensions/map_test.dart

Allows performing validation on a specific key within a map. Expects
that a value with the given key is present, and returns a check on the
value.

Add a Map operator[] extension

---

pkgs/checks/lib/checks.dart
pkgs/checks/lib/context.dart
pkgs/checks/lib/src/checks.dart
pkgs/checks/lib/src/extensions/async.dart
pkgs/checks/lib/src/extensions/core.dart
pkgs/checks/lib/src/extensions/iterable.dart
pkgs/checks/lib/src/extensions/map.dart
pkgs/checks/test/extensions/async_test.dart
pkgs/checks/test/extensions/core_test.dart
pkgs/checks/test/extensions/function_test.dart
pkgs/checks/test/extensions/iterable_test.dart
pkgs/checks/test/extensions/map_test.dart
pkgs/checks/test/extensions/math_test.dart
pkgs/checks/test/extensions/string_test.dart

Previously, all "condition" arguments were callbacks that take a
`Check`. Now there is a `Condition` class which has an `apply` method
for the same purpose.
Add an `it()` Utility to get an object that is both a `Condition`, and a
`Check`. Expectations run against the check are recorded and played back
against the real check when the condition is applied. Expectations can
be chained with a cascade, so that the outermost object is the one
passed as an argument.
Add a factory constructor which takes a callback because there is
currently no way to express a numeric comparison expectation with a
cascade. This wouldn't be necessary if we had methods like
`.isGreaterThan` instead of `operator >`.
Move `skip` to an extension since there are now multiple implementations
of `Check`.

Add Condition abstraction

---

pkgs/checks/lib/src/checks.dart
pkgs/checks/lib/src/extensions/math.dart
pkgs/checks/test/extensions/iterable_test.dart
pkgs/checks/test/extensions/math_test.dart
pkgs/checks/test/failure_message_test.dart

Rename to `isGreaterThan`, `isGreaterOrEqual`, `isLessThan`,
`isLessOrEqual`.
Drop the `Condition` constructor which takes a callback since now more
conditions should be expressible with a cascade on `it()`.

Remove operator extensions

---

pkgs/checks/lib/context.dart
pkgs/checks/lib/src/checks.dart
pkgs/checks/lib/src/describe.dart
pkgs/checks/lib/src/extensions/async.dart
pkgs/checks/lib/src/extensions/core.dart
pkgs/checks/lib/src/extensions/function.dart
pkgs/checks/lib/src/extensions/iterable.dart
pkgs/checks/lib/src/extensions/map.dart
pkgs/checks/lib/src/extensions/math.dart
pkgs/checks/lib/src/extensions/string.dart
pkgs/checks/test/extensions/async_test.dart
pkgs/checks/test/extensions/core_test.dart
pkgs/checks/test/extensions/function_test.dart
pkgs/checks/test/extensions/iterable_test.dart
pkgs/checks/test/extensions/map_test.dart
pkgs/checks/test/extensions/math_test.dart
pkgs/checks/test/extensions/string_test.dart
pkgs/checks/test/test_shared.dart

Change the `actual` argument for rejections from a single String to an
`Iterable<String>`. This allows for maintaining alignment when a multi
line value is displayed with indentation. Change the `literal` utility
to return an Iterable, and update conditions passing something other
than the return from `literal` to pass a List to `Rejection.actual`.
Add a `postfixLast` utility to mirror `prefixFirst` and append content
to the last line of a value. Combining `prefixFirst` and `postfixLast`
with delimiters like quotes or braces allows wrapping content than may be
be 1 or more lines.
Flesh out the `literal` utility. The implementation is based on
`prettyPrint` from `matcher` with some simplifications and adapted to
return an Iterable instead of a String with newlines. One significant …

Improve output for collections and long strings

---

pkgs/test/test/runner/configuration/top_level_error_test.dart

A test was skipped because a URI which used to result in a `FormatError`
started getting accepted by the SDK. The linked issue is closed as
working as intended. Update the test to use a URI which is invalid
according to the current SDK.

Fix a test to use an still invalid URI

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/github_reporter_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/reporter/github.dart

A `::group::` will have an arrow in the Github UI. This is misleading in
the majority of cases where there are no extra lines, and masks the
cases where there is output from the test.
Only wrap in `::group::` when there is a non-empty set of messages or
errors, since those indicate that there will be additional lines in the
output.

Avoid empty `::group::` in Github reporter

---

pkgs/checks/lib/src/checks.dart

This was not updated with the name change `expectNoAsyncFailure` to
`expectUnawaited`.

Rename allowLateFailure -> allowUnawaited

---

pkgs/checks/lib/src/checks.dart
pkgs/checks/lib/src/collection_equality.dart
pkgs/checks/lib/src/extensions/iterable.dart
pkgs/checks/lib/src/extensions/map.dart
pkgs/checks/test/extensions/collection_equality_test.dart
pkgs/checks/test/test_shared.dart

Add a `deepCollectionEquals` utility to find the Rejection for any
collection type. Add extensions for `Iterable` and `Map` to use the new
utility.
Iterable checking is implemented with a Queue that tracks the path
within a deeply nested iterable and the elements that need to be
compared.
Set and Map checking are implemented by comparing the all combinations
of values or entries and checking that all elements or entries can be
paired between the expected and actual collections. This allows for
cases where a Condition matches more than one key or element, and the
specific pairing needs to be aligned correctly to allow matching all
elements. This flexibility for matching Map keys does cause less
specific failure for mismatches within the Map value.
Add `deepEqual` conditions for Iterable …

Implement deep collection equality

---

pkgs/checks/lib/src/collection_equality.dart
pkgs/checks/lib/src/extensions/iterable.dart
pkgs/checks/test/extensions/collection_equality_test.dart
pkgs/checks/test/extensions/iterable_test.dart

Pull the common parts of `_findSetDifference` and `_findMapDifference`
into a utility called `unorderedCompared` which can be reused for
`unorderedEquals` and `unorderedMatches`. This removes some specificity
from rejections for non-matching Maps - it will now always refer to an
unmatched entry in its entirety, and will not have a special message for
when there is a key with no matches, vs when there are matching keys but
those keys have non-matching values.
Change `_hasPerfectMatching` to `_findUnpaired`. Don't require that the
actual and expected vertex sets have the same cardinality, take the
cardinality of the actual vertex set as an argument. Return list of the
unmatched vertices in both sets. Allows more specific failures than
solely reporting unequal lengths or that the elements …

Add unordered iterable comparisons

---

pkgs/checks/lib/src/checks.dart
pkgs/checks/lib/src/collection_equality.dart
pkgs/checks/lib/src/extensions/core.dart
pkgs/checks/lib/src/extensions/iterable.dart
pkgs/checks/lib/src/extensions/map.dart
pkgs/checks/lib/src/extensions/math.dart
pkgs/checks/lib/src/extensions/string.dart

Wrap callbacks to look for rejections without an `actual` value, and
fill it in with a default. Remove all `actual` arguments that were
passing exactly `literal(actual)`.

Allow omitting the actual argument for rejections

---

pkgs/checks/lib/src/checks.dart
pkgs/checks/test/describe_test.dart

Add a test for the `describe` method with a few simple cases.
Remove one assert which does not hold up when describing a condition
without an expectations checked against it.

Fix description of conditions without expectations

---

pkgs/test/pubspec.yaml
pkgs/test/pubspec_overrides.yaml
pkgs/test_api/pubspec.yaml
pkgs/test_api/pubspec_overrides.yaml
pkgs/test_core/pubspec.yaml
pkgs/test_core/pubspec_overrides.yaml

`dart pub publish` will ignore these files, so it won't be necessary to manually change the files for each publish. `dart pub get` and `dart pub upgrade` will use the overrides from the files.

Use pubspec_overrides.yaml files

---

pkgs/checks/lib/src/checks.dart
pkgs/checks/lib/src/collection_equality.dart
pkgs/checks/lib/src/extensions/iterable.dart
pkgs/checks/lib/src/extensions/map.dart
pkgs/checks/test/extensions/async_test.dart
pkgs/checks/test/extensions/collection_equality_test.dart
pkgs/checks/test/extensions/core_test.dart
pkgs/checks/test/extensions/function_test.dart
pkgs/checks/test/extensions/iterable_test.dart
pkgs/checks/test/extensions/map_test.dart
pkgs/checks/test/extensions/math_test.dart
pkgs/checks/test/extensions/string_test.dart
pkgs/checks/test/test_shared.dart

The new structure has a few advantages over the previous pattern of
calling `softCheck` and passing the result to `checkThat`, we can omit
some generic type arguments, and the failure can carry more context when
the failure is caused by accepted a value that should be rejected.
With `softCheck` the generic must be explicit on the `it()` call, or
explicit on `softCheck` and then filled through downward inference.
Without an explicit generic the correct extension methods are not
available for the condition. With a value passed to `checkThat` instead,
the generic can be inferred, and then carried forward to `it()` through
downwards inference.
With `softCheck` the value and the `Condition` are both opaque to the
failure, because the check only sees the `Rejection?`. With
`isRejectedBy` we can …

Refactor tests to a new isRejectedBy utility

---

pkgs/checks/lib/checks.dart
pkgs/checks/lib/src/checks.dart
pkgs/checks/lib/src/extensions/async.dart
pkgs/checks/test/extensions/async_test.dart

Allow an empty `label` argument to `context.nest` to indicate that no
expectation is checked and no detail is relevant to the user seeing a
failure.
Add an extension on `Check<Stream>` to wrap the stream in a queue which
allows for the interesting expectations to be checked.

Add a withQueue utility

---

pkgs/test/test/runner/line_and_col_test.dart

The timeout does not seem to have reduced the flakes. Add a retry instead.

Retry instead of extend timeout for flaky Node tests

---

pkgs/checks/lib/src/extensions/async.dart
pkgs/checks/lib/src/extensions/core.dart
pkgs/checks/test/extensions/async_test.dart
pkgs/checks/test/extensions/collection_equality_test.dart
pkgs/checks/test/extensions/core_test.dart

Rename both the sync and async versions. "which" reads better in more
situations.
Fix the examples to use Condition instead of a function literal. Minor
wording change for the async version doc.

Rename `that` to `which`

---

pkgs/checks/lib/src/extensions/iterable.dart
pkgs/checks/test/extensions/iterable_test.dart

Check for expected values one by one, but allow any number of non-matching values in between.
Support elements with equality, conditions on the element type, or conditions on dynamic.

Add Iterable.containsInOrder condition

---

pkgs/checks/README.md
pkgs/checks/lib/checks.dart
pkgs/checks/lib/context.dart
pkgs/checks/lib/src/checks.dart
pkgs/checks/lib/src/extensions/async.dart
pkgs/checks/lib/src/extensions/core.dart
pkgs/checks/lib/src/extensions/function.dart
pkgs/checks/lib/src/extensions/iterable.dart
pkgs/checks/lib/src/extensions/map.dart
pkgs/checks/lib/src/extensions/math.dart
pkgs/checks/lib/src/extensions/string.dart
pkgs/checks/pubspec.yaml
pkgs/checks/test/failure_message_test.dart
pkgs/checks/test/test_shared.dart

The word "check" is a bit overused in the documentation, and it's a
little confusing to use it as a noun. "Subject" is unambiguously a noun,
and it makes the docs read nicer in some places.

Rename `Check` to `Subject`

---

pkgs/checks/README.md
pkgs/checks/pubspec.yaml

Add description and version to pubspec. Remove `publish_to: none`.
Remove the readme section about using a git dependency.
Add readme sections on writing tests and custom expectations.

Prepare to publish

---

pkgs/checks/lib/src/checks.dart
pkgs/checks/pubspec.yaml

It would never be useful to set up a `Subject` and not check any
expectations on it.

Annotate `checkThat` with `usResult`

---

pkgs/checks/CHANGELOG.md
pkgs/checks/README.md
pkgs/checks/example/example.dart
pkgs/checks/lib/checks.dart
pkgs/checks/lib/src/checks.dart
pkgs/checks/lib/src/extensions/async.dart
pkgs/checks/lib/src/extensions/core.dart
pkgs/checks/lib/src/extensions/iterable.dart
pkgs/checks/lib/src/extensions/string.dart
pkgs/checks/pubspec.yaml
pkgs/checks/test/describe_test.dart
pkgs/checks/test/extensions/async_test.dart
pkgs/checks/test/extensions/collection_equality_test.dart
pkgs/checks/test/extensions/core_test.dart
pkgs/checks/test/extensions/function_test.dart
pkgs/checks/test/extensions/iterable_test.dart
pkgs/checks/test/extensions/map_test.dart
pkgs/checks/test/extensions/math_test.dart
pkgs/checks/test/extensions/string_test.dart
pkgs/checks/test/failure_message_test.dart

Save 4 characters of typing millions of times. The line will not read as
nicely in many situations, but it doesn't make a significant difference.
The shorter name, with no capital letters, also draws the least possible
attention to this name, which carries the least information of any part
of the expression.

Rename checkThat to check

---

pkgs/checks/lib/src/checks.dart
pkgs/checks/lib/src/extensions/async.dart
pkgs/checks/lib/src/extensions/core.dart
pkgs/checks/lib/src/extensions/function.dart
pkgs/checks/lib/src/extensions/map.dart
pkgs/checks/test/extensions/map_test.dart
pkgs/checks/test/test_shared.dart

The main benefit is this brings more alignment with the
`clause` arguments for `expect` calls. The docs will be able to focus on
the difference in how the value is used (preceding "that" in the case of
labels, standing on its own in a list in the case of clauses) and can
use a consistent description for how it is passed.
A secondary benefit is that it allows multiline labels and avoids
workaround like joining with `r'\n'`.
A final benefit is that it saves some unnecessary String formatting
since the callback isn't called if no expectations fail on the Subject,
or when used as a soft check where the failure details are ignored.
- Make the `label` arguments to `nest` and `nestAsync`, and the _label
field in `_TestContext` an `Iterable<String> Function()`.
- Wrap strings that had been passed …

Make `label` arguments take callbacks

---

pkgs/checks/lib/checks.dart
pkgs/checks/lib/src/checks.dart
pkgs/checks/lib/src/extensions/async.dart
pkgs/checks/lib/src/extensions/core.dart
pkgs/checks/lib/src/extensions/function.dart

These are technically user facing, but not likely to be referenced.
Rename `ThrowsCheck` to `FunctionChecks`, and `NullabilityChecks` to
`NullableChecks`. All extensions that define expectation methods are
named `*Checks` based on the type they support, plus `CoreChecks` for
any type.
Rename `Skip` to `SkipExtension` to avoid conflict with `Skip` from
`package:test`.
Rename `StreamQueueWrap` to `WithQueueExtension`.

Rename some extensions for consistency

---

pkgs/test/CHANGELOG.md
pkgs/test/test/runner/configuration/platform_test.dart
pkgs/test/test/runner/configuration/randomize_order_test.dart
pkgs/test/test/runner/runner_test.dart
pkgs/test/test/runner/shard_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner.dart
pkgs/test_core/lib/src/runner/configuration/args.dart

Fixes https://github.com/dart-lang/test/issues/1891
Fixes https://github.com/dart-lang/test/issues/1899
For any path which looks like it has a scheme (contains "://"), parse it as a uri and grab the path from that. On windows, we also remove any leading `/` from the path because it will be followed by a drive letter, which we want to be the first part of the path (and not preceded by a `/`).
Open to better ideas here too, if you have them :)

Support running tests by absolute file: uri

---

pkgs/checks/CHANGELOG.md
pkgs/checks/README.md
pkgs/checks/pubspec.yaml

Link to the migration guide so that there is a link from the pub and
docs sites.
Fix an example usage of `completes` after #1896

Minor readme improvements

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/runner_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/configuration/args.dart
pkgs/test_core/pubspec.yaml

Since the latest `package:test` rolled into the SDK, some DAP tests started failing to run tests with `dart test`. They use absolute paths on Windows: https://github.com/dart-lang/sdk/issues/51348
This seems to fix the issue for me - it avoids using the URI to compute the file path if it's not a `file://` URI and instead uses the raw input (but chops it at the `?` to handle query params on non-URI paths).
@jakemac53

Handle absolute paths on Windows

---

pkgs/test_core/lib/src/runner/compiler_selection.dart
pkgs/test_core/lib/src/runner/configuration/args.dart

this cleans up the internal build rules a bit (avoids adding a new dep)

use test_api/backend.dart instead of test_core/backend.dart

---

pkgs/checks/CHANGELOG.md
pkgs/checks/README.md
pkgs/checks/doc/migrating_from_matcher.md
pkgs/checks/example/example.dart

Closes #1938
Add a description of `because` in the README and an example using it.
Add a `because` argument to one of the examples in `example.dart`.
Call out the rename from `reason` to `because` in the migration guide.

Add `because` usage in examples

---

pkgs/checks/doc/migrating_from_matcher.md

In the migration guide doc, add a question and answer about why the Dart
team is moving away from the matcher package. Describes how and why
`checks` can offer a better UX than we could possibly do with `matcher`.

Add note about why we are replacing matcher

---

pkgs/test/CHANGELOG.md
pkgs/test/test/runner/compiler_runtime_matrix_test.dart
pkgs/test/test/runner/runner_test.dart
pkgs/test_api/lib/src/backend/compiler.dart
pkgs/test_api/lib/src/backend/runtime.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/bootstrap/vm.dart
pkgs/test_core/lib/src/runner/plugin/shared_platform_helpers.dart
pkgs/test_core/lib/src/runner/vm/platform.dart

Only supported by the `vm` platform, usable with `--compiler exe`. I called it this to match `dart compile exe`.
I also added a test which covers basic behavior for the full matrix of supported runtimes and compilers.

Add exe compiler, supports running tests compiled to native executables

---

pkgs/checks/README.md
pkgs/checks/doc/migrating_from_matcher.md
pkgs/checks/test/extensions/async_test.dart

Towards #1928
Add a section in the README about async expectations. Give examples of
awaiting the result, and describe that when the result is not awaited
the test runner is still aware of the work. Describe that some
expectations cannot be awaited.
Describe the reason that `StreamQueue` is used for stream expectations
and give examples of using the `withQueue` and a manual wrapping.
Mention that both `expect` and `expectLater` are migrated to the same
`check` call in the migration guide. Give an example of migrated an
awaited expectation.

Add async examples to README

---

pkgs/checks/lib/src/extensions/core.dart
pkgs/checks/test/extensions/core_test.dart

The API is intended for extracting properties that cannot fail, and a
further expectation should always be made about the property.
This should solve one potential confusion in the usage compared to the
similar `TypeMatcher.having` which took a third matcher argument. This
may have prevented the confusion in #1930

Annotate `has` with `@useResult`

---

pkgs/checks/doc/migrating_from_matcher.md

There are some usage differences, and the rename should be mentioned. These are not a direct rename/replacement, but they are very close in usage and intent.

Mention .having and .has in migration guide

---

pkgs/test/test/runner/compiler_runtime_matrix_test.dart

On windows we sometimes see the stdout come with no newline between
`hello` and the test runner output for the first running test. Flush
stdout to see if it more reliably includes the newline.

Flush stdin before test

---

pkgs/checks/CHANGELOG.md
pkgs/checks/lib/src/checks.dart
pkgs/checks/test/soft_check_test.dart

The doc comments mention that the first failure is returned, but this
wasn't the behavior. Use a null aware assignment to only use the first
reported failure, and add tests for soft checks that fail for multiple
reasons.

Only grab the first failure in softCheck

---

pkgs/checks/lib/src/extensions/core.dart
pkgs/checks/test/extensions/core_test.dart

Makes the error more clear when `has` is used in a way that is not
intended.

Include stack trace for exception in has

---

pkgs/checks/lib/src/extensions/iterable.dart
pkgs/checks/test/extensions/iterable_test.dart

The `has` utility is intended for reading fields that cannot throw. For
`single`, `first`, and `last`, which may throw for unexpected numbers of
elements, implement with `context.next` and test with specific
rejections for the length.

Avoid exceptions for iterable getters

---

pkgs/checks/lib/src/checks.dart

A predicate or extraction callback is not supposed to throw - it should
return a Rejection to indicate a failure - however if an exception is
thrown the test should fail for that exception and immediately be done.
Move the `outstandingWork.complete()` call to a `finally` block so it
is never skipped. Move it after the nested condition is applied to also
fix a potential bug if the `Condition` is a callback that does any async
work outside calls to the context. This isn't a typical pattern, but
could become more typical if we drop the `Condition` abstraction.

Fix timeouts when async predicate throws

---

pkgs/checks/lib/src/collection_equality.dart

Mention in the doc comment that for deep collection equality checks the
condition must always be `Condition<dynamic>`, and suggest using `isA`
to add expectations for the specific type. This differs from
`Iterable.containsInOrder` which allow a condition on the element type.

Condition must have dynamic generic in deepEquals

---

pkgs/checks/lib/src/extensions/iterable.dart
pkgs/checks/test/extensions/iterable_test.dart

Saw this error which didn't make sense:
```
Expected: a DownloadFolder that:
has contents that:
is not empty
Actual: a DownloadFolder that:
has contents that:
Actual: []
Which: is not empty
```
This is a copy-paste oversight from `isEmpty`. The rejection should be inverted (as it is for `isEmpty`)!

[checks] Fix isNotEmpty rejection

---

pkgs/test/doc/architecture.md

The missing space was breaking the links section. Now it renders correctly.
**Before:**
**After:**

Fix typo in architecture.md

---

pkgs/test/lib/src/runner/browser/chrome.dart
pkgs/test/lib/src/runner/browser/firefox.dart
pkgs/test/lib/src/runner/browser/platform.dart
pkgs/test/lib/src/runner/browser/safari.dart
pkgs/test/lib/src/runner/node/platform.dart
pkgs/test/lib/src/runner/wasm/platform.dart
pkgs/test_core/lib/src/runner/vm/platform.dart
pkgs/test_core/lib/src/runner/vm/test_compiler.dart
pkgs/test_core/lib/src/util/io.dart

We frequently see CI failures with exceptions pointing to various
deletes which fail because of processes still having the file or
directory open. Add a synchronous retry to see if it helps at all.
It may become necessary to make it asynchronous and add a small backoff.

Retry filesystem deletes

---

pkgs/checks/lib/src/checks.dart
pkgs/checks/pubspec.yaml
pkgs/checks/pubspec_overrides.yaml
pkgs/checks/test/context_test.dart
pkgs/checks/test/test_shared.dart
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/hooks_testing.dart
pkgs/test_api/test/frontend/expect_async_test.dart
pkgs/test_api/test/frontend/expect_test.dart
pkgs/test_api/test/frontend/matcher/completion_test.dart
pkgs/test_api/test/frontend/matcher/prints_test.dart
pkgs/test_api/test/frontend/matcher/throws_test.dart
pkgs/test_api/test/frontend/matcher/throws_type_test.dart
pkgs/test_api/test/frontend/never_called_test.dart
pkgs/test_api/test/frontend/stream_matcher_test.dart
pkgs/test_api/test/utils.dart
pkgs/test_api/test/utils_new.dart

Previous test for methods like `expect`, `expectLater`, and
`expectAsync` used internal details of the test runner like `LiveTest`
to check behaviors such as holding the test open and specific failure
behavior.
Add an abstraction `TestCaseMonitor` to hide the implementation details
of creating and running a `LocalTest`. Expose only the parts of
`LiveTest` which are used by current tests - the status, result and
errors.
The new class is defined in a new library `hooks_testing` since it is
intended primarily for writing tests for code that uses the `hooks`
library.
Migrate tests under `test_api/test/frontend` for the tests which will be
migrating to `package:matcher` to use the new APIs. Move to a
`utils_new.dart` file which will be moved along with these tests, and
the old `utils.dart` …

Add a hooks_testing library

---

pkgs/test/lib/src/runner/browser/default_settings.dart
pkgs/test/lib/src/runner/executable_settings.dart
pkgs/test/test/runner/browser/firefox_test.dart

Add a new argument to the `ExectuableSettings` constructor to add an
environment variable that can override the specific executable, instead
of overriding for all uses of `ExectuableSettings`. Pass this variable
from the chrome browser.
Add a test that the override is ignored when running a firefox test.

Only use environment variable for chrome

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/suite_platform.dart
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Towards #1977
The constructor signature uses a nullable argument to smooth over the
compatibility across versions which allowed us to land in monolithic
repositories without needing to roll `test_api` and `flutter_test`
atomically. This extends the same backwards compatibility to the json
API used between the runner and tests to smooth over compatibility with
`flutter test` which may try to run test compiled against a newer API
than it uses to communicate with them.

More smoothly handle missing compiler info

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/dart.js
pkgs/test/pubspec.yaml

This propagates the nonce from any script on the page to the script created by dart.js.

Make tests compatible with Strict CSP

---

.github/workflows/dart.yml
tool/ci.sh

- regenerate mono_repo
- move back to using the latest stable version of the `setup-dart` action (from using a version from head)
- likely obsolete some of the recent dependabot PRs

regenerate mono_repo

---

pkgs/checks/doc/migrating_from_matcher.md

The link to the "Improvements you can expect" section was broken.

Fix "Improvements" link in `package:checks` migration guide

---

pkgs/test/CHANGELOG.md
pkgs/test/dart_test.yaml
pkgs/test/lib/src/executable.dart
pkgs/test/lib/src/runner/browser/browser_manager.dart
pkgs/test/lib/src/runner/browser/chrome.dart
pkgs/test/lib/src/runner/browser/chromium.dart
pkgs/test/lib/src/runner/browser/default_settings.dart
pkgs/test/lib/src/runner/browser/microsoft_edge.dart
pkgs/test/test/runner/browser/microsoft_edge_test.dart
pkgs/test/test/runner/runner_test.dart
pkgs/test_api/lib/src/backend/runtime.dart

This adds support for the (Chromium-based) Microsoft Edge browser as a test platform. Since the browser is so similar to Chrome in general, I've moved most of the code supplying the startup arguments to `chromium.dart`.  So most of the functionality is shared between Chrome and MS Edge. I wasn't sure if the debug protocol used by Chrome is supported by Edge as-is, so I opted to not support that for now.
Closes #1142

Add support for Microsoft Edge

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/backend.dart
pkgs/test_api/lib/scaffolding.dart
pkgs/test_api/lib/test_api.dart
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Closes #1990
The `scaffolding` library should not be deprecated to avoid marking the useful APIs as deprecated during autocomplete.
The `backend` library is no longer deprecated because it _is_ intended for use in `flutter_test`, and the deprecation isn't likely to be blocking any uses.
Export `registerException` from the scaffolding library. This had originally been held back from the focused libraries because it isn't a great API, but it's too entrenched to be worth deprecating at this point, so it may as well be fully supported.

Remove deprecation of test_api top level libraries

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/util/string_literal_iterator.dart
pkgs/test_core/pubspec.yaml

Otherwise in Dart language 3 there will be an error:
The class 'Iterator' can't be extended outside of its library because it's an interface class. [INVALID_USE_OF_TYPE_OUTSIDE_LIBRARY]

Dart 3 compatibility: change `extends Iterator` to `implements Iterator`

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/browser_manager.dart
pkgs/test/lib/src/runner/browser/platform.dart
pkgs/test/lib/src/runner/node/platform.dart
pkgs/test/lib/src/runner/wasm/platform.dart
pkgs/test/pubspec.yaml
pkgs/test/test/runner/compiler_runtime_matrix_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/backend.dart
pkgs/test_core/lib/scaffolding.dart
pkgs/test_core/lib/src/direct_run.dart
pkgs/test_core/lib/src/platform.dart
pkgs/test_core/lib/src/runner.dart
pkgs/test_core/lib/src/runner/compiler_selection.dart
pkgs/test_core/lib/src/runner/configuration.dart
pkgs/test_core/lib/src/runner/configuration/args.dart
pkgs/test_core/lib/src/runner/configuration/load.dart
pkgs/test_core/lib/src/runner/hybrid_listener.dart
pkgs/test_core/lib/src/runner/load_suite.dart
pkgs/test_core/lib/src/runner/parse_metadata.dart
pkgs/test_core/lib/src/runner/plugin/platform_helpers.dart
pkgs/test_core/lib/src/runner/plugin/remote_platform_helpers.dart
pkgs/test_core/lib/src/runner/runner_test.dart
pkgs/test_core/lib/src/runner/spawn_hybrid.dart
pkgs/test_core/lib/src/runner/suite.dart
pkgs/test_core/lib/src/runner/vm/platform.dart
pkgs/test_core/lib/src/runner/vm/test_compiler.dart
pkgs/test_core/lib/src/util/stack_trace_mapper.dart
pkgs/test_core/pubspec.yaml

The `scaffolding.dart` and `backend.dart` libraries are no longer deprecated in the latest release of `test_api`.

Remove ignores for undeprecated libraries

---

.github/workflows/dart.yml
integration_tests/wasm/mono_pkg.yaml
integration_tests/wasm/test/hello_world_test.dart
pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/tool/host.dart
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/metadata.dart
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/plugin/platform_helpers.dart
pkgs/test_core/lib/src/runner/runner_test.dart
pkgs/test_core/pubspec.yaml
tool/ci.sh

This fixes https://github.com/dart-lang/test/issues/2006

Don't do direct casts to int to prevent dart2wasm breakages.

---

.github/workflows/dart.yml
legacy_tests/nnbd_opted_out/mono_pkg.yaml
legacy_tests/spawn_hybrid_with_optout/mono_pkg.yaml
pkgs/test_core/lib/src/runner/parse_metadata.dart
tool/ci.sh

Unblock CI for now, filed #2013 to fix the usage.

Ignore some deprecated analyzer APIs

---

pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/expect.dart
pkgs/test_api/lib/src/expect/async_matcher.dart
pkgs/test_api/lib/test_api.dart
pkgs/test_api/pubspec.yaml
pkgs/test_api/pubspec_overrides.yaml
pkgs/test_core/lib/test_core.dart
pkgs/test_core/pubspec.yaml

`package:test` exports directly from `package:matcher`. Resolves a
cyclic dependency between `matcher` and `test_api`.

Remove the matcher export from test_api

---

pkgs/test_api/lib/src/backend/state.dart

These are used in the other test runner implementation packages, but the
usage should not be impacted. Implement the `parse` methods by iterating
over the values instead of a manual `switch` statement.

Make State and Result enums

---

pkgs/checks/test/context_test.dart

The `unorderedMatches` expectation takes an `Iterable<Condition<T>>` so
the `it()` call gets the generic inferred and does not force a
`Subject<dynamic>` like `deepEquals` would when using a condition to
compare with an element.

Remove redundant type checks

---

pkgs/test_api/lib/src/scaffolding/test_structure.dart
pkgs/test_core/lib/scaffolding.dart

The change from an implicit `dynamic` to `Object` is statically breaking
for any usage passing a variable or any expression with type `dynamic`
or `Object?`.

Allow null descriptions

---

pkgs/checks/README.md

Current docs point heavily towards using the `Context`, but for simple
cases there is less boilerplate by giving a name to multiple existing
checks.

Add example of composed checks in an extension

---

pkgs/checks/README.md

Under "Checking expectations" add subheadings for different chunks of
the content. Reorder some of the content and tweak wording.

Add subsections to readme

---

pkgs/test/test/runner/json_reporter_utils.dart

- Decode the output once instead of repeatedly decoding it for every
`expect` call.
- Use `=>` for single expression return methods.
- Use conditional collection elements where applicable.

Minor cleanup in json_reporter_utils

---

pkgs/test/CHANGELOG.md
pkgs/test/test/runner/json_reporter_test.dart
pkgs/test/test/runner/json_reporter_utils.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/reporter/json.dart

Fixes #2037
Canonicalize paths when checking whether a stack frame is coming from
the test suite root.
Add a test case which runs with an absolute path argument. On windows,
this situation would have resulted in the `root_` location information
being missing because of a difference in the stack frame paths and the
suite path before canonicalization. This test fails on windows without
the canonicalization.
Make the test utils more flexible to handle the new output differences
across operation systems.
Allow a `Matcher` value for the `path` argument to `suiteJson`. This
optional argument had previously been unused. Use `equalsIgnoreCase`
because on windows there is a difference in the case of the drive
letter.
Allow a `Matcher` value for the `name` argument to `testStartJson`. Take
an …

Fix root suite comparison on Windows

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/default_settings.dart
pkgs/test/test/runner/browser/firefox_test.dart
pkgs/test/test/runner/browser/microsoft_edge_test.dart
pkgs/test/test/runner/browser/safari_test.dart

adds `SAFARI_EXECUTABLE` and `FIREFOX_EXECUTABLE`
this allows you to use FF Developer Edition and Safari Technology Preview.
Also there are already `MS_EDGE_EXECUTABLE` that were missing test.
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- …

feat(runner): add env overrides for safari and ff

---

.github/dependabot.yml

- config dependabot to send daily PRs for major version bumps
We could choose to expand this to the 2 other packages in this mono-repo, but this at least captures the two packages w/ regular deps on package:analyzer.
@natebosch - this PR also assigns you as the reviewer; happy enough to leave this blank as well (or, switch to using an CODEOWNERS file in this repo to auto-assign PRs, ala https://github.com/dart-lang/tools/blob/main/CODEOWNERS).
---
<details>
- Contributions to our repos should follow the [Dart style …

config dependabot to send daily PRs for major version bumps

---

.github/workflows/dart.yml
tool/ci.sh

We recently had some dependabot cls that are failing due ([1](https://github.com/dart-lang/test/pull/2052), [2](https://github.com/dart-lang/test/pull/2051)) to the mono_repo self validate task, which I thought we had fixed. I am hoping that just updating the version of mono_repo that is used will fix that?

regenerate mono_repo with the latest

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/browser/runner_test.dart
pkgs/test/test/runner/compiler_runtime_matrix_test.dart
pkgs/test/test/runner/expanded_reporter_test.dart
pkgs/test/test/runner/json_file_reporter_test.dart
pkgs/test/test/runner/json_reporter_test.dart
pkgs/test/test/runner/node/runner_test.dart
pkgs/test/test/runner/pub_serve_test.dart
pkgs/test/test/runner/signal_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/loader.dart
pkgs/test_core/lib/src/runner/reporter/expanded.dart
pkgs/test_core/pubspec.yaml

All platforms will use the "loading" message. This had been a heuristic
for the dart2js tests because originally it was the standout amongst the
otherwise run-from-source options with the VM and dartium.
The number of platforms has since expanded, and flutter appears as a
dart2js platform that isn't precompiled, because the test runner has a
different way to trigger the precompiled path than `flutter test` which
precompiles always.

Remove "compiling" messages

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/static/host.dart.js
pkgs/test/tool/host.dart

Towards #2065
Handle the new communication pattern from the host side. Allows the
frame to send a single `'port'` message with a read `MessageChannel` in
stead of the `{'ready': true}` message signalling that the host should
send a message port. This will remove one hop in the communication
pattern.
Retains handling of the current pattern and does not update the frame
side yet. There are multiple implementations of both the host and the
frame behavior. All host implementations will be updated to allow either
pattern before the frame implementations are updated.
Change from a `if/else` chain to a `switch`. Use pattern matching to
destructure the `'data'` field in the case of exceptions.

Allow frame to send the message port

---

.github/workflows/publish.yaml

This is particularly important for the `labeled` type, otherwise adding
the `publish-ignore-warnings` will not get picked up until another
commit is pushed to the branch.

Rerun publish workflow on more PR changes

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

I published `test` without realizing I also needed to publish test_core 😱

publish test_core v0.5.6

---

pkgs/test/lib/src/runner/browser/browser.dart
pkgs/test/lib/src/runner/browser/browser_manager.dart

There are no browsers which override `observatoryUrl` to return
non-null. Remove the field entirely and override the field in the
browser `Environment` with a getter that always returns null.

Remove always null observatoryUrl for browsers

---

pkgs/test/CHANGELOG.md

Due to the `<`, these entries were cut off on pub.dev, potentially causing confusion. This PR switches the messages to code syntax so they are legible in both raw and rendered form.
**Original rendered output (from https://pub.dev/packages/test/changelog#1245):**

Fix improperly rendered changelog entry

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/vm/platform.dart
pkgs/test_core/pubspec.yaml

We cannot move to the new API until the minimum SDK can be safely
bumped.

Add an ignore for an SDK deprecation

---

pkgs/test/lib/src/runner/browser/dom.dart
pkgs/test/lib/src/runner/browser/post_message_channel.dart
pkgs/test/tool/host.dart

Add support for console log and warn level in the dom library.
Switch an existing `print` to a `console.warn` for an error. Use
`console.log` consistently otherwise. This is less important in the host
(where a `print` will anyways log to the console) than it is in the
remote listener (where a `print` could be intercepted and forwarded to
the test runner).
Refactor an `if`/`else` chain over a map field to a `switch` with
destructuring for all the patterns that can be handled. Add a default
case with a console warning instead of silently treating potentially
non-matching commands as `'closeSuite'`. This also changes some
potential cast failures into falling through to the warning case which
should be easier to debug.
Add a message from the frame when it is connecting back to the host.

Add some console logging to browser test startup

---

pkgs/test/test/runner/compiler_runtime_matrix_test.dart

This test invokes the test runner in each case, and when the outer test
timeout is faster than a timeout within the sub-process it prevents us
from getting potentially useful output. Double the outer timeout so that
any timeouts from the sub-process runner have a better chance at firing
and emitting output before the test is killed.

Extend the timeout for runtime_matrix_test

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/browser/runner_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/dart2js_compiler_pool.dart

Fixes https://github.com/dart-lang/test/issues/2088
Pass `--disable-program-split` so that no splitting actually happens.
I [first tried fixing this](https://github.com/dart-lang/test/pull/2089) more "properly" by serving all the output files but this was a lot more complex and supporting stack trace mapping in particular was looking very challenging.

Fix running browser tests that use deferred loading

---

pkgs/test/test/runner/compiler_runtime_matrix_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/configuration/args.dart
pkgs/test_core/lib/src/runner/configuration/reporters.dart
pkgs/test_core/lib/src/runner/reporter.dart

Resolve a flaky test by eliminating the reporter output as a
potential race condition.
Add a `hidden` flag to `ReporterDetails` since the reporter is not worth
showing in the CLI usage help. Request the silent reporter for a test
which is flaky due to interleaving of forwarded `stdout` with the
reporter's output. During flakes the `hello` and the newline can come as
separate events in the stream, so sometimes the newline is written
following unexpected reporter content.

Add a silent reporter

---

pkgs/test/lib/src/runner/browser/platform.dart

Starting the browser and running the first suite shouldn't be delayed by
compilation of all other suites. We may want to increase parallelization
of compiles at some point. I do not expect to make the change suggested
in the TODO.

Drop a TODO about running browser after compile

---

pkgs/test/lib/src/runner/browser/firefox.dart
pkgs/test/lib/src/runner/browser/internet_explorer.dart
pkgs/test/lib/src/runner/browser/safari.dart
pkgs/test/test/runner/browser/chrome_test.dart
pkgs/test/test/runner/browser/firefox_test.dart
pkgs/test/test/runner/browser/internet_explorer_test.dart
pkgs/test/test/runner/browser/safari_test.dart

Towards #2095
Restrict to Uri arguments instead of the looser `dynamic` which in
practice allowed Strings (which were correctly formatted) or Uri
instances. Take Uri so the format is enforced and the `.toString()` can
be trusted.
Update (unused in practice) test args from dart-lang.org to dart.dev

Add types to Browser implementation url arguments

---

pkgs/test/test/utils.dart
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_api/test/utils.dart

Towards #2095
Use `Queue.of` to infer the collection type from the argument instead of
`Queue.from` which ignores the argument type.
Expand a bare `Function` to a full signature function type.

Tighten types in test utils

---

pkgs/test_core/lib/src/runner.dart

Filtering by line number is hardcoded to assume that test cases are specified in `file://` uri. If the kernel is compiled with `--filesystem-scheme`, filtering by line did not work.
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to …

Filter test by line when kernel is compiled with --filesystem-scheme.

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

This will require a release to unblock rolling this new version of vm_service through to Flutter.

Update package:vm_service to 12.0.0

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/util/io.dart
pkgs/test_core/pubspec.yaml

Allow backwards compatibility with current callers. This might make it
easier to land https://github.com/flutter/engine/pull/46592

Make compiler optional in calls to currentPlatform

---

pkgs/test/lib/dart.js

Originally the href was added manually to the data to work around a
`dart:html` limitation. A different workaround for the host side was
implemented in #2066, but the frame side was not changed in the same
commit to allow some cross-compatibility. Remove the final manual href
field now that no host implementations would read it.

Remove unused href field from error report

---

pkgs/test_core/lib/src/runner/dart2js_compiler_pool.dart

- Remove a TODO referencing a closed issue. The issue was deduped to
another which was closed without changes. Manual testing in a browser
shows that the rewriting is still necessary.
- Extract a variable for the source map path as a Uri instead of
computing it within the loop.
- Directly return URIs which are already `file://`. This would be a
slight behavior change for the `runInBrowser.dart` synthetic source if
it was ever put in the source map file with an absolute `file://`
URI, but with the current (and apparently planned) dart2js output they
do not have the file scheme. This is not a behavior change for any
other cases where the source is a `file` URI, since it is no necessary
to call `resolveUri` with an absolute path, and all `file` URI are
absolute.
A sample run with a …

Tweak dart2js source map rewriting

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/configuration/args.dart
pkgs/test_core/lib/src/runner/vm/platform.dart
pkgs/test_core/lib/src/util/io.dart
pkgs/test_core/pubspec.yaml

Pull out a small utility for stripping leading slashes on windows from
the arg parsing code so it can be reused when spawning isolates by path.
It's still not clear what specific conditions lead to paths which look
like this, but the behavior is triggering for this path in another CI
system.

Strip leading slash when spawning isolate

---

pkgs/test/lib/src/runner/browser/compilers/dart2wasm.dart
pkgs/test/test/runner/compiler_runtime_matrix_test.dart

See https://github.com/dart-lang/test/issues/2150
Also removes an accidental debug print that was landed

mark flaky windows test as skipped

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Updating to `package:frontend_server_client v4.0.0` is only a breaking change for dependents that set the `debug` argument of `FrontendServerClient.start` to true, and`package:test_core` never does that.

Update frontend_server_client constraint to allow version 4.0.0

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/compilers/dart2js.dart
pkgs/test/pubspec.yaml
pkgs/test/tool/host.dart

We see are getting some logs from the browser that shows some of the
test suites have a "Starting suite" output but no "sending channel to
host" output. Add more logging to the console to further narrow down
where things may be getting stuck.
- Add a log statement after appending the iframe to the page.
- Add a log statement at the beginning of the `main` that is loaded in
the iframe.

Add more logging around iframe startup

---

pkgs/test/CHANGELOG.md
pkgs/test/test/runner/runner_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/configuration/args.dart
pkgs/test_core/lib/src/runner/configuration/reporters.dart

Towards #2162
Unhide the silent reporter. This was originally introduced hidden
because we expected it to only be useful for our own CI infrastructure,
since a failure without any output cannot be investigated - it must be
reproduced in a separate run to even find which test case failed.
We now have an external request for failing without any output on stdio
and there is no strong reason to keep the silent reporter hidden.
Remove the support for hidden reporters entirely - it can easily be
reintroduced if we have another reporter which isn't user facing.
Expand the reporter description. Break a long description string into a
adjacent literals to avoid lines over 80 columns.

Document the silent reporter

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/compilers/compiler_support.dart
pkgs/test/lib/src/runner/browser/compilers/dart2js.dart
pkgs/test/lib/src/runner/browser/compilers/dart2wasm.dart
pkgs/test/lib/src/runner/browser/compilers/precompiled.dart
pkgs/test/lib/src/runner/browser/platform.dart
pkgs/test/pubspec.yaml

I think this should fix the failures we have been seeing on the bots for package:build.
Moved the logic for the test html wrapper into the base class for all modes of browser tests, so that it can be shared with the precompiled mode.  The dart2wasm mode overrides that behavior since it does things a bit different.

fix a bug where test html files were not created in precompiled mode

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/compilers/dart2js.dart
pkgs/test/pubspec.yaml

Fixes #2176
On windows a path can include a `\` followed by a letter that is not a
valid escape code in a Dart string. Prefix the string with `r` to make
it a raw string and log the path directly.

Use a raw string for console logging with path

---

pkgs/checks/CHANGELOG.md
pkgs/checks/pubspec.yaml

Expand constraint on `package:test_api` to allow the latest
`package:test`.

Prepare to publish package:checks

---

pkgs/test/CHANGELOG.md
pkgs/test/README.md
pkgs/test/pubspec.yaml

This section was removed: https://github.com/dart-lang/test/commit/cc0598b2c3bf3a7439f10f9542a8d01ff50b69e9#diff-c97f9e0d4b6adec304ed041e0063f78a4842c22d03bcaa5086a66c9d49aeab98
I have no idea what else should be removed or added from the ToC, and I have no idea how you would maintain this ToC.
Fixes https://github.com/dart-lang/test/issues/2188
---
<details>
- Most changes should add an entry to …

Update README.md, remove link to Stream Matchers

---

pkgs/test/pubspec.yaml
pkgs/test/test/runner/failures_only_reporter_test.dart
pkgs/test/test/runner/runner_test.dart
pkgs/test_core/lib/src/runner/configuration/reporters.dart
pkgs/test_core/lib/src/runner/reporter/failures_only.dart

Closes #829
Copies the expanded reporter and test and removes output unrelated to
failed tests.

Add failure only reporter

---

pkgs/test_core/lib/src/runner/vm/platform.dart

The `IsolateChannel` should close the receive port when we call
`outerChannel.sink.close` which is also added to the `cleanupCallbacks`.
This was originally added in #1280 to try to fix cases where the test
runner could hang after running some tests specifically on the test
runner CI when running the test as a subprocess. It looks like when
it was introduced there was no call to `outerChannel.sink.close()`.
A cleanup callback to close the sink was added in #1941 which made
this unnecessary.

Let the IsolateChannel close the RecievePort

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/wasm_compiler_pool.dart

We don't appear to have any tests for experiments right now, nor any really good way of adding them. I did manually test though 🤷‍♂️

support enabling experiments when using the dart2wasm compiler

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml

This is part of a [plan to simplify the web_socket_channel implementation](https://github.com/dart-lang/web_socket_channel/issues/340)
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding …

Allow the next semver major versions of shelf_web_socket and web_socket_channel

---

pkgs/test/CHANGELOG.md
pkgs/test/README.md
pkgs/test/doc/architecture.md
pkgs/test/doc/configuration.md
pkgs/test/pubspec.yaml

Closes #2218
These links were to the defining library, which can change without a
user visible breaking change or major version bump. Link instead to the
`package:test/test.dart` library docs for all APIs. The export makes the
dartdoc links work, and these are more stable since they are user facing
and will only change in a major version release.

Point README links to the test library

---

.github/workflows/dart.yml
integration_tests/wasm/mono_pkg.yaml
integration_tests/wasm/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/wasm_compiler_pool.dart

`package:test` should not depend and use Dart SDK internal scripts, files, flags or other internal things.
=> Use supported `dart compile wasm` command to compile tests.
Closes https://github.com/dart-lang/test/issues/2210

Fix `dart run test -p chrome -c dart2wasm`

---

pkgs/test_core/lib/src/runner/console.dart

The `dynamic` was used to satisfy the purpose that is more directly
expressed with `FutureOr`.
Replace the private `_Command` class with a typedef record with named fields.

Remove an unnecessary `dynamic`

---

.github/workflows/dart.yml
integration_tests/spawn_hybrid/pubspec.yaml
pkgs/checks/CHANGELOG.md
pkgs/checks/pubspec.yaml
pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/vm/test_compiler.dart
pkgs/test_core/pubspec.yaml

Before 3.4.0:
```console
Could not find an option with short name "-O".
Usage: dart compile wasm [arguments] <dart entry point>
```
This option was added in commit [92d53c426f9b4764e5c34d33ef7bbcf5fd3b12a6](https://github.com/dart-lang/sdk/commit/92d53c426f9b4764e5c34d33ef7bbcf5fd3b12a6)

Bump min Dart version to 3.4.0 for WASM

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/package_version.dart

Fixes https://github.com/dart-lang/test/issues/2243
I can't explain why this would only break on 3.4.0 and later, still looking into that.

try to fix windows failures

---

.github/workflows/dart.yml
pkgs/test_core/lib/src/runner/vm/platform.dart
pkgs/test_core/lib/src/runner/vm/test_compiler.dart
pkgs/test_core/mono_pkg.yaml
pkgs/test_core/pubspec.yaml
pkgs/test_core/pubspec_overrides.yaml
pkgs/test_core/test/runner/vm/test_compiler_test.dart

Towards #2246 
This will allow a client of the VM service to evaluate the top level
variable and locate the package config used by the test runner.
Add a public `testBootstapContents` function in `test_compiler.dart`
which centralizes the bootstrap templates. Add an argument for the
package config URI and a `VmTestType` which is either "Vm" or
"Native".
Add the first test case in `test_core`. Add the pub dependency and
override for `package:test`, as well as the mono_repo configuration to
run unit tests. Other tests for `test_core` code is under the `test`
package but should be moved eventually.

Add package config URI into VM test entrypoints

---

pkgs/test_api/lib/src/backend/declarer.dart
pkgs/test_core/lib/src/scaffolding.dart

Add suggestions for fixing the declared tests. Differentiate the message
based on whether the test `main` is running within the test runner, or
as a standalone executable.

Expand error message for async test declaration

---

pkgs/checks/CHANGELOG.md
pkgs/checks/lib/src/describe.dart
pkgs/checks/test/extensions/iterable_test.dart

These will break across lines and they read more easily when wrapped
with angle brackets, regardless of whether they are the top level of the
literal.

Always wrap Condition descriptions

---

pkgs/checks/lib/src/checks.dart
pkgs/test_core/lib/src/runner/hack_register_platform.dart

Replace `<` and `>` in documentation comments with `&lt` and `&gt` so
that they won't be interpreted as HTML tags and will render as expected.
In one place where we show Dart code with angle bracket I've replaced
the wrapping `[` and `]` with backticks.
Fixes CI.

Fix documentation rendering issues

---

pkgs/test_core/lib/src/runner/wasm_compiler_pool.dart

fixes #2231
Thanks to @d-markey https://github.com/dart-lang/test/issues/2231#issuecomment-2282283629 for figuring it out.
This fix uses the same technique as in precompiled tests:
https://github.com/dart-lang/test/blob/9fbbfdbee18a686e3f84a386a01960ea0543ba01/pkgs/test/test/runner/precompiled_test.dart#L54
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the …

fix: use `toFilePath` in package config Uri

---

.github/workflows/health.yaml
.github/workflows/post_summaries.yaml

This should cut down on the number of comments we need to leave regarding changelog updates etc.

add health check job

---

.github/CODEOWNERS

Trying out the CODEOWNERS workflows, we can remove this if it is annoying.
Any dart-lang admin can edit that group so we can always get something landed if needed that way, but it will require some explicit steps from an admin.

require approval from core-package-admins for anything under /pkgs

---

.github/workflows/health.yaml

The `breaking` and `leaking` health checks are not currently compatible
with repos using pub workspaces.
The `coverage` health check is too slow to be worth using in this repo.
Run only `version`, `changelog`, and `do-not-submit` checks.

Limit which health checks run

---

.github/workflows/dart.yml
integration_tests/regression/pubspec.yaml
integration_tests/spawn_hybrid/pubspec.yaml
integration_tests/wasm/dart_test.yaml
integration_tests/wasm/pubspec.yaml
pkgs/checks/pubspec.yaml
pkgs/test/CHANGELOG.md
pkgs/test/lib/src/bootstrap/node.dart
pkgs/test/lib/src/runner/node/platform.dart
pkgs/test/lib/src/runner/node/socket_channel.dart
pkgs/test/pubspec.yaml
pkgs/test/test/runner/node/runner_test.dart
pkgs/test/test/runner/runner_test.dart
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/runtime.dart
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/wasm_compiler_pool.dart
pkgs/test_core/pubspec.yaml
pubspec.yaml
tool/ci.sh

Support `dart2wasm` as a compiler for tests running in Node.js. `dart2wasm` emits a `.mjs` file exporting definitions to load generated wasm modules, the only additional thing we have to do is wrap that in a simple entrypoint file compiling the wasm module and invoking the startup wrapper.
There's no support for stack trace maps yet. We also don't support precompiled node wasm tests yet (`dart2wasm` is also not currently supported by `build_web_compilers`, so we're blocked on that either way).
In the test runtime, I had to migrate off `require` as that function is not in the global context for `.mjs` files. It looks like we can use `await import` instead though. If we need to support ancient Node versions that lack `import` support, I can adapt that to still use `require` when compiled …

Support dart2wasm in node.js tests

---

.github/workflows/dart.yml
pkgs/test/mono_pkg.yaml
pkgs/test/test/runner/browser/safari_test.dart
pkgs/test/test/runner/compiler_runtime_matrix_test.dart

This will exercise things like launching browsers (where they are
currently working on CI).
Add `osx` to the sharded `package:test` tests alongside `windows`. These
exercise the majority of OS specific behavior.
Skip existing safari tests due to a bug running tests in non-interactive
environments. (#1253)
Skip existing firefox tests due to a changed executable path. (Planned
fix in #2276)
Refactor a ternary chain to an if/else chain to add the extra
conditions for firefox and safari.

Run package:test tests on mac

---

pkgs/test/lib/src/runner/browser/static/run_wasm_chrome.js

Update dart2wasm module instantiation, compilation, and invoking `main` to support all the ways dart2wasm implemented.

Update dart2wasm module runner

---

pkgs/checks/CHANGELOG.md
pkgs/checks/doc/migrating_from_matcher.md
pkgs/checks/lib/src/describe.dart
pkgs/checks/lib/src/extensions/iterable.dart
pkgs/checks/test/extensions/iterable_test.dart

The joined behavior in `containsInOrder` has some usability issues:
- It mimics the arguments for `deepEquals`, but it doesn't have the same
behavior for collection typed elements. Checking that a nested
collection is contained in order requires a `Condition` callback that
uses `.deepEquals` explicitly.
- The `Object?` signature throws away inference on the `Condition`
callback arguments. With a method that supports only conditions the
argument type can be tightened and allow inference.
Deprecate the old `containsInOrder` and plan to remove it before stable.
This is a bit more restrictive, but it's not too noisy to fit a few
`(it) => it.equals(foo)` in a collection that needs mixed behavior and
the collection of two methods is less confusing to document than the
joined behavior.
Lean on …

Add containsMatchingInOrder  containsEqualInOrder

---

pkgs/checks/lib/src/extensions/async.dart

Resolves rendering issues with this doc on the hosted doc site.

Add a missed / in a doc comment

---

pkgs/test/test/runner/precompiled_test.dart

This was intended as a regression test for https://github.com/dart-lang/test/issues/2294 but it actually passes 😭

write a test for running two precompiled browser tests

---

pkgs/test/test/utils.dart

This file was forked during the package split and some of the APIs are
unused in the test package tests. Remove or make private all members of
the utils library that are unused in other test suites.

Remove some unused testing utilities

---

pkgs/fake_async/analysis_options.yaml
pkgs/matcher/CHANGELOG.md
pkgs/matcher/analysis_options.yaml
pkgs/matcher/lib/src/core_matchers.dart
pkgs/matcher/lib/src/expect/throws_matcher.dart
pkgs/matcher/lib/src/iterable_matchers.dart
pkgs/matcher/lib/src/map_matchers.dart
pkgs/matcher/lib/src/numeric_matchers.dart
pkgs/matcher/lib/src/operator_matchers.dart
pkgs/matcher/lib/src/order_matchers.dart
pkgs/matcher/lib/src/string_matchers.dart
pkgs/matcher/pubspec.yaml
pkgs/matcher/test/expect_async_test.dart
pkgs/matcher/test/matcher/throws_type_test.dart
pkgs/matcher/test/mirror_matchers_test.dart

Add argument types to `typedMatches` arguments which were unnecessarily
widening it back to `dynamic`. 
Add some missing `as dynamic` and `as Function` which is the pattern the
lint uses to allow intentional dynamic calls.
Ignore some dynamic calls in a test for a legacy API.
Ignore a couple false positives for calling methods (as opposed to
getters) on a cast expression. The false positive was fixed in
https://dart-review.googlesource.com/c/sdk/+/390640
but not yet published.
Remove the deprecated lint `package_api_docs`.
Replaces https://github.com/dart-lang/matcher/pull/205

Enable avoid_dynamic_calls lint

---

pkgs/matcher/lib/src/map_matchers.dart

Allow using `containsKey` and `containsValue` on non-map types like
built collection maps which do not implement the core `Map` but has the
required methods and operators.

Use dynamic methods for map matchers

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/platform.dart
pkgs/test/pubspec.yaml
pkgs/test/test/runner/precompiled_test.dart
pkgs/test_core/CHANGELOG.md
pkgs/test_core/pubspec.yaml

Fixes #2294
Avoid creating extra unexpected BrowserManager instances by caching the
future in the `_browserManagers` map without any async delay. Previously
it was possible for two managers to be created if the second suite is
loaded before the first suite's `compilerSupport` was resolved. This was
not a problem for tests that get compiled by the test runner because the
compilation would delay the second suite load until after the first
suite's `compilerSupport` has resolved. It is not a problem when running
without concurrency because that delays the second suite load.
Add a concurrency argument to the regression test, otherwise the default
is to run with concurrency 1 which works around the bug.

Fix hang after multiple precompiled browser tests

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml

Eliminates the noisy outdated dep warning for anyone using pkg:test

test: allow latest pkg:matcher

---

pkgs/fake_async/CHANGELOG.md
pkgs/fake_async/pubspec.yaml

Release fake_async v1.3.3

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml

[test] allow the latest version of pkg:shelf_web_socket

---

pkgs/checks/README.md

Then we don't have to update the version number in the `README.md` every time we make publish a new release.

Suggest using `dart pub add dev:checks`

---

pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/configuration/reporters.dart
pkgs/test_core/pubspec.yaml

Previous versions of `package:args` alphabetically sorted the
`allowedHelp` entries for help output. The latest release removes the
sorting and breaks the change-detection tests for the help output.
https://github.com/dart-lang/core/pull/852
Manually sort the keys of the reporters map to match the alpha sort of
the old output.

Sort reporter options

---

pkgs/test/lib/src/runner/browser/compilers/dart2js.dart
pkgs/test/lib/src/runner/browser/dom.dart
pkgs/test/lib/src/runner/browser/post_message_channel.dart
pkgs/test/test/runner/coverage_test.dart
pkgs/test/test/runner/test_on_test.dart
pkgs/test/tool/host.dart

Migrate from deprecated `dart:js`, `dart:js_util`, `package:js_util` to `dart:js_interop`

---

pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/vm/test_compiler.dart

Closes: https://github.com/dart-lang/test/issues/2483
Tested in `dartdev`: https://dart-review.googlesource.com/c/sdk/+/422080
Packages must opt in to a new version of package test to adopt this fix. (`dartdev` uses the version of `package:test` that's in the users' pubspec, rather than the one that's rolled in the Dart SDK!)
In the test for `dartdev` I manually applied the edits to `third_party/pkg/test/pkgs/test_core` and overrode the dependencies.

[native assets] Add support for pub workspaces

---

pkgs/test/doc/json_reporter.md

Fix two minor typos in the documentation for the `json_reporter`.
Several tools parse this documentation and therefore use the incorrect comments.
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require …

Fix typos in json_reporter documentation

---

.github/workflows/dart.yml
pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/vm/platform.dart
pkgs/test_core/pubspec.yaml

The Dart VM treats the main isolate specially. When the main isolate shuts down, the entire VM shuts down, even if there are other isolates still running.
package:coverage needs to collect coverage for all isolates. To do this, the VM is run with `--pause-isolates-on-exit`, and package:coverage waits for each isolate to pause, collects the coverage, then resumes the isolate and allows it to exit. But since the main isolate exiting would cause all isolates to exit, some of which may not have been collected yet, package:coverage needs to treat the main isolate specially, and avoid resuming it until every other isolate is collected.
Unfortunately there's no reliable way of determining which isolate is the main isolate using the VM service API. So package:coverage uses a heuristic: the first …

Set a debug name for test isolates

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test/test/runner/set_up_all_test.dart
pkgs/test/test/runner/tear_down_all_test.dart
pkgs/test_api/CHANGELOG.md
pkgs/test_api/lib/src/backend/group.dart
pkgs/test_api/lib/src/backend/group_entry.dart
pkgs/test_api/lib/src/backend/invoker.dart
pkgs/test_api/lib/src/backend/test.dart
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/runner_test.dart
pkgs/test_core/pubspec.yaml

When groups are filtered using `filter()` and not `onPlatform`, we would clone the group and tests without also cloning `setUpAll`/`tearDownAll`, which led to an assertion failure when trying to set the parents.
This change ensures we clone tests in `filter()` like we do in `forPlatform()`.
Fixes https://github.com/dart-lang/test/issues/2498

Fix an issue with failed assertions using setUpAll/tearDownAll

---

pkgs/matcher/CHANGELOG.md
pkgs/matcher/lib/src/iterable_matchers.dart
pkgs/matcher/test/iterable_matchers_test.dart

Add sorting related matchers for iterables.
* isSorted
* isSortedUsing
* isSortedBy
* isSortedByCompare
These match the functions available in https://github.com/dart-lang/core/blob/main/pkgs/collection/lib/src/iterable_extensions.dart
---
- [✅ ] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

Add isSorted and related matchers

---

pkgs/test/CHANGELOG.md
pkgs/test/pubspec.yaml
pkgs/test_api/CHANGELOG.md
pkgs/test_api/pubspec.yaml
pkgs/test_core/CHANGELOG.md
pkgs/test_core/lib/src/runner/parse_metadata.dart
pkgs/test_core/pubspec.yaml

Prepare to publish with no other package changes.

Expand Analyzer constraints to allow 8.x

---

pkgs/test/test/runner/precompiled_test.dart

Closes #2527
During the null safety migration there were `dart` level flags that
needed to be kept in sync for precompiled JS tests so the platform
executable arguments were forwarded direclty. This is currently causing
a test failure, and there are no null safety related `dart` level flags
so drop the forwarding.

Drop executable arguments forwarding

---

pkgs/test/CHANGELOG.md
pkgs/test/lib/src/runner/browser/compilers/dart2wasm.dart

dart2wasm generates a source map file at the same location with the .wasm file. Serve it to help with debugging in the browser with `--pause-after-load`.
Note: somehow the source map file is not requested by the browser when testing with just `test -p chrome -c dart2wasm` (without `--pause-after-load` and manually adding breakpoints). I'm investigating why the source map isn't requested by default. When I run the same failing test with `-c dart2js` the source map is used.

Serve dart2wasm source map files

---

pkgs/test/test/io.dart

Similar to #2528
This case of argument forwarding existed since the test runner was first
written. It's not clear exactly why it was necessary, and it should be safe
to remove.
The existing argument forwarding breaks some tests on CI where an
unexpected argument is passed to some dart invocations.

Remove executable argument forwarding in tests

---

pkgs/test_core/lib/src/runner/coverage.dart
pkgs/test_core/lib/src/runner/coverage_stub.dart
pkgs/test_core/lib/src/runner/engine.dart

The `package:coverage` library imports `dart:io` directly and cannot be
a dependency of apps compiled to platforms without `dart:io`. All
imports and uses of `package:coverage` must be through platform specific
imports. Add extra indirection in the `coverage.dart` and
`coverage_stub.dart` libraries so that `engine.dart` does not need to
import `package:coverage` or refer to the `HitMap` type it exports. Add
a forwarding implementation of the `merge` extension.

Make all package:coverage imports conditional
